// SPDX-FileCopyrightText: 2026 The dynG Authors
// SPDX-License-Identifier: Apache-2.0
/**
 * @file dynamic_bfs_traits.hpp
 * @brief The conformance-kit traits of dynamic_bfs (PLAN Section 8.2; cpp/tests/conformance;
 *        generated by scripts/new_algorithm.py).
 */
#pragma once

#include "conformance/test_traits.hpp"
#include "conformance/type_list.hpp"

#include <dyng/core/backend.hpp>
#include <dyng/core/copy.hpp>
#include <dyng/core/resources.hpp>
#include <dyng/core/types.hpp>
#include <dyng/dynamic_bfs.hpp>
#include <dyng/graph/edge_batch.hpp>
#include <dyng/graph/edge_list.hpp>
#include <dyng/graph/graph.hpp>
#include <dyng/graph/graph_properties.hpp>

#include <cstddef>
#include <cstdint>
#include <deque>
#include <functional>
#include <string_view>
#include <vector>

namespace dyng::conformance {

/// dynamic_bfs: the kit compares the levels (exactly) and the invalidation counters.
template <>
struct test_traits<tags::dynamic_bfs> {
  static constexpr std::string_view name = "dynamic_bfs";         ///< as in the manifest
  static constexpr oracle_kind oracle = oracle_kind::compute;     ///< update chain == compute
  static constexpr determinism level = determinism::exact_value;  ///< identical values
  static constexpr bool history_independent = true;               ///< the result of a graph
  /// The instantiated graph types (DYNG_FOR_EACH_GRAPH_TYPE and
  /// DYNG_FOR_EACH_UNWEIGHTED_GRAPH_TYPE).
  using graph_types = type_list<graph<std::int32_t, std::int32_t, std::int32_t>,
                                graph<std::int32_t, std::int64_t, std::int32_t>,
                                graph<std::int64_t, std::int64_t, std::int32_t>,
                                graph<std::int32_t, std::int32_t, unweighted>,
                                graph<std::int32_t, std::int64_t, unweighted>>;
  template <typename graph_t>
  using result = dynamic_bfs::result;          ///< the result
  using stats = dynamic_bfs::stats;            ///< update()'s stats
  using snapshot = std::vector<std::int64_t>;  ///< the levels

  /// The graph requirements: the in-edges are stored (the seed pulls along them).
  static void require(graph_properties& props) {
    props.store_transposed = true;
  }
  /// The generated graphs.
  static graph_shape shape(size_class size) {
    switch (size) {
      case size_class::tiny:
        return {6, 10, 5};
      case size_class::small:
        return {30, 100, 9};
      case size_class::medium:
        return {120, 500, 9};
    }
    return {};
  }
  /// compute() (one engine).
  template <typename graph_t>
  static result<graph_t> compute(const resources& res, const graph_t& g, engine /*e*/) {
    return dynamic_bfs::compute(res, g);
  }
  /// update().
  template <typename graph_t>
  static stats update(
      const resources& res, graph_t& g,
      const edge_batch_view<typename graph_t::vertex_type, typename graph_t::weight_type>& batch,
      result<graph_t>& r) {
    return dynamic_bfs::update(res, g, batch, r);
  }
  /// The result on the host.
  template <typename graph_t>
  static snapshot take(const resources& res, const result<graph_t>& r) {
    return to_vector(res, r.levels());
  }
  /// The independent oracle (C2): a textbook queue BFS from vertex 0 over a host copy of the
  /// out-edges, written here without the library's engine.
  template <typename graph_t>
  static snapshot oracle_of(const resources& res, const graph_t& g) {
    const auto csr = g.to_csr(res);
    const auto n = static_cast<std::size_t>(csr.num_vertices());
    std::vector<std::int64_t> levels(n, -1);
    std::deque<std::size_t> queue;
    if (n > 0) {
      levels[0] = 0;
      queue.push_back(0);
    }
    while (!queue.empty()) {
      const std::size_t u = queue.front();
      queue.pop_front();
      for (auto e = csr.row_ptr[u]; e < csr.row_ptr[u + 1]; ++e) {
        const auto v = static_cast<std::size_t>(csr.col_ind[static_cast<std::size_t>(e)]);
        if (levels[v] < 0) {
          levels[v] = levels[u] + 1;
          queue.push_back(v);
        }
      }
    }
    return levels;
  }
  /// The counters that are equal across runs and backends (besides the common ones): the
  /// invalidation follows the BFS tree, whose parents every backend chooses by the same rule.
  static std::vector<std::int64_t> deterministic(const stats& s) {
    return {s.invalidated, s.invalidation_rounds};
  }
  /// Options and graphs compute() and set_options() reject.
  template <typename graph_t>
  static std::vector<std::function<void()>> invalid_options(const resources& res,
                                                            const graph_t& g) {
    return {
        [&] {
          dynamic_bfs::options opt;
          opt.source = -1;
          (void)dynamic_bfs::compute(res, g, opt);
        },
        [&] {
          dynamic_bfs::options opt;
          opt.source = static_cast<std::int64_t>(g.num_vertices());
          (void)dynamic_bfs::compute(res, g, opt);
        },
        [&] {
          auto r = dynamic_bfs::compute(res, g);
          dynamic_bfs::options opt = r.get_options();
          opt.source = 1;  // fixed at compute()
          r.set_options(opt);
        },
    };
  }
  /// C8: host synchronizations of the algorithm phase: none on the host backends; on cuda one
  /// per count the host reads (each invalidation pass, the seed, each loop round, two in
  /// finalize).
  static std::int64_t host_sync_budget(backend b, const stats& s) {
    return b == backend::cuda ? s.invalidation_rounds + s.iterations + 3 : 0;
  }
};

}  // namespace dyng::conformance
