// SPDX-FileCopyrightText: 2026 The dynG Authors
// SPDX-License-Identifier: Apache-2.0
/**
 * @file dynamic_bfs_traits.hpp
 * @brief The conformance-kit traits of dynamic_bfs (PLAN Section 8.2; cpp/tests/conformance;
 *        generated by scripts/new_algorithm.py).
 */
#pragma once

#include "conformance/test_traits.hpp"
#include "conformance/type_list.hpp"

#include <dyng/core/backend.hpp>
#include <dyng/core/copy.hpp>
#include <dyng/core/resources.hpp>
#include <dyng/core/types.hpp>
#include <dyng/dynamic_bfs.hpp>
#include <dyng/graph/edge_batch.hpp>
#include <dyng/graph/edge_list.hpp>
#include <dyng/graph/graph.hpp>
#include <dyng/graph/graph_properties.hpp>

#include <cstdint>
#include <functional>
#include <string_view>
#include <vector>

namespace dyng::conformance {

/// dynamic_bfs (TODO(dynamic_bfs): what the kit compares).
template <>
struct test_traits<tags::dynamic_bfs> {
  static constexpr std::string_view name = "dynamic_bfs";         ///< as in the manifest
  static constexpr oracle_kind oracle = oracle_kind::compute;     ///< update chain == compute
  static constexpr determinism level = determinism::exact_value;  ///< identical values
  static constexpr bool history_independent = true;               ///< the result of a graph
  /// The instantiated graph types (DYNG_FOR_EACH_GRAPH_TYPE).
  using graph_types = type_list<graph<std::int32_t, std::int32_t, std::int32_t>,
                                graph<std::int32_t, std::int64_t, std::int32_t>,
                                graph<std::int64_t, std::int64_t, std::int32_t>>;
  template <typename graph_t>
  using result = dynamic_bfs::result;          ///< the result
  using stats = dynamic_bfs::stats;            ///< update()'s stats
  using snapshot = std::vector<std::int64_t>;  ///< the levels

  /// The graph requirements.
  static void require(graph_properties& props) {
    (void)props;
  }
  /// The generated graphs.
  static graph_shape shape(size_class size) {
    switch (size) {
      case size_class::tiny:
        return {6, 10, 5};
      case size_class::small:
        return {30, 100, 9};
      case size_class::medium:
        return {120, 500, 9};
    }
    return {};
  }
  /// compute() (one engine).
  template <typename graph_t>
  static result<graph_t> compute(const resources& res, const graph_t& g, engine /*e*/) {
    return dynamic_bfs::compute(res, g);
  }
  /// update().
  template <typename graph_t>
  static stats update(
      const resources& res, graph_t& g,
      const edge_batch_view<typename graph_t::vertex_type, typename graph_t::weight_type>& batch,
      result<graph_t>& r) {
    return dynamic_bfs::update(res, g, batch, r);
  }
  /// The result on the host.
  template <typename graph_t>
  static snapshot take(const resources& res, const result<graph_t>& r) {
    return to_vector(res, r.levels());
  }
  /// The counters that are equal across runs and backends (besides the common ones).
  static std::vector<std::int64_t> deterministic(const stats& /*s*/) {
    return {};
  }
  /// Options and graphs compute() and set_options() reject.
  template <typename graph_t>
  static std::vector<std::function<void()>> invalid_options(const resources& res,
                                                            const graph_t& g) {
    return {
        [&] {
          dynamic_bfs::options opt;
          opt.source = -1;
          (void)dynamic_bfs::compute(res, g, opt);
        },
        [&] {
          dynamic_bfs::options opt;
          opt.source = static_cast<std::int64_t>(g.num_vertices());
          (void)dynamic_bfs::compute(res, g, opt);
        },
        [&] {
          auto r = dynamic_bfs::compute(res, g);
          dynamic_bfs::options opt = r.get_options();
          opt.source = 1;  // fixed at compute()
          r.set_options(opt);
        },
    };
  }
  /// C8: host synchronizations of the algorithm phase (none: host backends only).
  static std::int64_t host_sync_budget(backend /*b*/) {
    return 0;
  }
};

}  // namespace dyng::conformance
