// SPDX-FileCopyrightText: 2026 The dynG Authors
// SPDX-License-Identifier: Apache-2.0
/**
 * @file dynamic_bfs_test.cpp
 * @brief Hand cases of dynamic_bfs: the worked example of the tutorial and the edge cases (PLAN
 *        Section 4.8, file 12; first generated by scripts/new_algorithm.py).
 */
#include <dyng/core/backend.hpp>
#include <dyng/core/copy.hpp>
#include <dyng/core/error.hpp>
#include <dyng/core/resources.hpp>
#include <dyng/dynamic_bfs.hpp>
#include <dyng/graph/edge_batch.hpp>
#include <dyng/graph/edge_list.hpp>
#include <dyng/graph/graph.hpp>
#include <dyng/graph/graph_properties.hpp>

#include <gtest/gtest.h>

#include <cstdint>
#include <string>
#include <utility>
#include <vector>

namespace {

using graph_t = dyng::graph<std::int32_t, std::int32_t, std::int32_t>;
using batch_t = dyng::edge_batch<std::int32_t, std::int32_t>;
using levels_t = std::vector<std::int64_t>;

graph_t make_graph(const dyng::resources& res, std::int32_t n,
                   const std::vector<std::pair<std::int32_t, std::int32_t>>& edges,
                   dyng::graph_properties props = {}) {
  dyng::edge_list<std::int32_t, std::int32_t> list;
  list.num_vertices = n;
  list.num_weights = 1;
  for (const auto& [u, v] : edges) {
    list.add_edge(u, v, {1});
  }
  return graph_t::from_edges(res, list.view(), props);
}

/// The host backends of this build.
std::vector<dyng::resources> host_backends() {
  std::vector<dyng::resources> out{dyng::resources::sequential()};
  if (dyng::backend_available(dyng::backend::openmp)) {
    out.push_back(dyng::resources::openmp(4));
  }
  return out;
}

// The worked example of the tutorial (docs/tutorials/your_first_dynamic_algorithm.md):
//
//     0 -> 1 -> 3 -> 4        levels 0 1 1 2 3; the parent of 3 is 1 (the lower id of 1 and 2)
//     0 -> 2 -> 3
TEST(DynamicBfs, TheTutorialExample) {
  for (const dyng::resources& res : host_backends()) {
    SCOPED_TRACE(std::string(dyng::to_string(res.get_backend())));
    graph_t g = make_graph(res, 5, {{0, 1}, {0, 2}, {1, 3}, {2, 3}, {3, 4}});
    auto r = dyng::dynamic_bfs::compute(res, g);
    EXPECT_EQ(dyng::to_vector(res, r.levels()), (levels_t{0, 1, 1, 2, 3}));

    // Deleting the tree edge 1 -> 3 invalidates 3 and its subtree {4}; 3 pulls level 2 from 2,
    // then 4 gets level 3 again: nothing changed.
    batch_t remove;
    remove.delete_edge(1, 3);
    const auto s = dyng::dynamic_bfs::update(res, g, remove.view(), r);
    EXPECT_FALSE(s.fallback_used);
    EXPECT_EQ(s.invalidated, 2);
    EXPECT_EQ(s.invalidation_rounds, 3);  // the root, its child, and the empty pass below
    EXPECT_EQ(s.affected, 0);
    EXPECT_EQ(dyng::to_vector(res, r.levels()), (levels_t{0, 1, 1, 2, 3}));

    // Inserting 0 -> 4 offers level 1 to 4.
    batch_t shortcut;
    shortcut.insert_edge(0, 4, {1});
    const auto t = dyng::dynamic_bfs::update(res, g, shortcut.view(), r);
    EXPECT_EQ(t.invalidated, 0);
    EXPECT_EQ(t.invalidation_rounds, 0);
    EXPECT_EQ(t.affected, 1);
    EXPECT_EQ(dyng::to_vector(res, r.levels()), (levels_t{0, 1, 1, 2, 1}));

    // Deleting 0 -> 2 and 2 -> 3 cuts 3 off: 4 keeps its shortcut.
    batch_t cut;
    cut.delete_edge(0, 2);
    cut.delete_edge(2, 3);
    const auto u = dyng::dynamic_bfs::update(res, g, cut.view(), r);
    EXPECT_EQ(u.affected, 2);
    EXPECT_EQ(dyng::to_vector(res, r.levels()), (levels_t{0, 1, -1, -1, 1}));
    EXPECT_EQ(dyng::to_vector(res, r.levels()),
              dyng::to_vector(res, dyng::dynamic_bfs::compute(res, g).levels()));
    EXPECT_EQ(r.graph_version(), g.version());
  }
}

TEST(DynamicBfs, NewVerticesStartUnreached) {
  for (const dyng::resources& res : host_backends()) {
    graph_t g = make_graph(res, 3, {{0, 1}, {1, 2}});
    auto r = dyng::dynamic_bfs::compute(res, g);
    batch_t grow;
    grow.insert_edge(4, 5, {1});  // vertices 3, 4 and 5 appear, none reachable
    grow.insert_edge(2, 3, {1});  // 3 is reachable
    (void)dyng::dynamic_bfs::update(res, g, grow.view(), r);
    EXPECT_EQ(dyng::to_vector(res, r.levels()), (levels_t{0, 1, 2, 3, -1, -1}));
  }
}

TEST(DynamicBfs, AParallelEdgeKeepsTheLevel) {
  dyng::graph_properties props;
  props.order = dyng::row_order::append;
  props.parallel_edges = dyng::multi_edges::allow;
  for (const dyng::resources& res : host_backends()) {
    graph_t g = make_graph(res, 3, {{0, 1}, {0, 1}, {1, 2}}, props);
    auto r = dyng::dynamic_bfs::compute(res, g);
    batch_t remove;
    remove.delete_edge(0, 1);  // removes one of the two parallel edges
    const auto s = dyng::dynamic_bfs::update(res, g, remove.view(), r);
    EXPECT_EQ(dyng::to_vector(res, r.levels()),
              dyng::to_vector(res, dyng::dynamic_bfs::compute(res, g).levels()));
    EXPECT_EQ(s.affected, 0);
  }
}

TEST(DynamicBfs, RejectsBadInput) {
  const dyng::resources res = dyng::resources::sequential();
  const graph_t g = make_graph(res, 3, {{0, 1}});
  dyng::dynamic_bfs::options opt;
  opt.source = 3;
  EXPECT_THROW((void)dyng::dynamic_bfs::compute(res, g, opt), dyng::invalid_argument_error);
  dyng::graph_properties props;
  props.store_transposed = false;
  const graph_t no_in_edges = make_graph(res, 3, {{0, 1}}, props);
  EXPECT_THROW((void)dyng::dynamic_bfs::compute(res, no_in_edges), dyng::invalid_argument_error);
  auto r = dyng::dynamic_bfs::compute(res, g);
  EXPECT_THROW(r.set_options(opt), dyng::invalid_argument_error);
}

TEST(DynamicBfs, CloneCopiesTheLevels) {
  const dyng::resources res = dyng::resources::sequential();
  graph_t g = make_graph(res, 3, {{0, 1}, {1, 2}});
  const auto r = dyng::dynamic_bfs::compute(res, g);
  auto c = r.clone(res);
  EXPECT_EQ(dyng::to_vector(res, c.levels()), dyng::to_vector(res, r.levels()));
  batch_t remove;
  remove.delete_edge(1, 2);
  (void)dyng::dynamic_bfs::update(res, g, remove.view(), c);
  EXPECT_EQ(dyng::to_vector(res, c.levels()), (levels_t{0, 1, -1}));
}

}  // namespace
