// SPDX-FileCopyrightText: 2026 The dynG Authors
// SPDX-License-Identifier: Apache-2.0
/**
 * @file my_bfs_test.cpp
 * @brief Hand cases of my_bfs, the tutorial's reference solution: an update equals compute(),
 *        and an edge inserted and deleted in one batch (generated by scripts/new_algorithm.py).
 */
#include <dyng/core/copy.hpp>
#include <dyng/core/resources.hpp>
#include <dyng/graph/edge_batch.hpp>
#include <dyng/graph/edge_list.hpp>
#include <dyng/graph/graph.hpp>
#include <dyng/my_bfs.hpp>

#include <gtest/gtest.h>

#include <cstdint>
#include <utility>
#include <vector>

namespace {

using graph_t = dyng::graph<std::int32_t, std::int32_t, std::int32_t>;

graph_t make_graph(const dyng::resources& res, std::int32_t n,
                   const std::vector<std::pair<std::int32_t, std::int32_t>>& edges) {
  dyng::edge_list<std::int32_t, std::int32_t> list;
  list.num_vertices = n;
  list.num_weights = 1;
  for (const auto& [u, v] : edges) {
    list.add_edge(u, v, {1});
  }
  return graph_t::from_edges(res, list.view());
}

// A deleted shortest-path edge cuts 2 and 3 off; the inserted 3 -> 2 does not reach them.
TEST(MyBfs, AnUpdateEqualsCompute) {
  const dyng::resources res = dyng::resources::sequential();
  graph_t g = make_graph(res, 4, {{0, 1}, {1, 0}, {1, 2}, {2, 3}});
  auto r = dyng::my_bfs::compute(res, g);
  dyng::edge_batch<std::int32_t, std::int32_t> batch;
  batch.delete_edge(1, 2);
  batch.insert_edge(3, 2, {1});
  const auto s = dyng::my_bfs::update(res, g, batch.view(), r);
  EXPECT_FALSE(s.fallback_used);  // incremental: no recomputation
  const auto fresh = dyng::my_bfs::compute(res, g);
  EXPECT_EQ(dyng::to_vector(res, r.levels()), dyng::to_vector(res, fresh.levels()));
  EXPECT_EQ(dyng::to_vector(res, r.levels()), (std::vector<std::int64_t>{0, 1, -1, -1}));
  EXPECT_EQ(r.graph_version(), g.version());
}

// [tutorial: hand test]
// With deletions_first = false a batch that inserts 0 -> 2 and deletes it again leaves the graph
// as it was: applied.delta still lists the insertion, but the edge is not in G_{t+1}, so it must
// not offer level 1 to 2.
TEST(MyBfs, AnEdgeInsertedThenDeletedOffersNoLevel) {
  const dyng::resources res = dyng::resources::sequential();
  dyng::edge_list<std::int32_t, std::int32_t> list;
  list.num_vertices = 3;
  list.num_weights = 1;
  list.add_edge(0, 1, {1});
  list.add_edge(1, 2, {1});
  dyng::graph_properties props;
  props.semantics.deletions_first = false;  // the insertions first, then the deletions
  graph_t g = graph_t::from_edges(res, list.view(), props);
  auto r = dyng::my_bfs::compute(res, g);
  dyng::edge_batch<std::int32_t, std::int32_t> batch;
  batch.insert_edge(0, 2, {1});
  batch.delete_edge(0, 2);
  (void)dyng::my_bfs::update(res, g, batch.view(), r);
  EXPECT_EQ(dyng::to_vector(res, r.levels()), (std::vector<std::int64_t>{0, 1, 2}));
}
// [tutorial: hand test end]

}  // namespace
