// SPDX-FileCopyrightText: 2026 The dynG Authors
// SPDX-License-Identifier: Apache-2.0
/**
 * @file my_bfs.cpp
 * @brief my_bfs: argument validation, the result, compute() and update() through the
 *        framework's enactors, the hooks of the problem, and the explicit instantiations
 *        (generated by scripts/new_algorithm.py; PLAN Section 4.8, file 4).
 */
#include "algorithms/my_bfs/problem.hpp"
#include "core/budget_counters.hpp"
#include "framework/composition.hpp"
#include "framework/context.hpp"
#include "framework/enactor.hpp"
#include "framework/views.hpp"
#include "graph/graph_impl.hpp"
#include "graph/instantiate.hpp"

#include <dyng/core/backend.hpp>
#include <dyng/core/error.hpp>
#include <dyng/core/memory.hpp>
#include <dyng/my_bfs.hpp>
#include <dyng/update.hpp>

#include <algorithm>
#include <cstddef>
#include <cstdint>
#include <memory>
#include <string>
#include <utility>

namespace dyng::detail {

namespace {

/// The backends of the manifest that this algorithm implements.
bool implemented(backend b) {
  return b == backend::sequential || b == backend::openmp;
}

/// Throws not_supported_error unless the backend of `res` is implemented and built.
void expect_backend(const resources& res, const char* function) {
  const backend b = res.get_backend();
  if (!implemented(b) || !backend_available(b)) {
    throw not_supported_error(concat_message("dyng: ", function, ": the ", to_string(b),
                                             " backend is not available for "
                                             "my_bfs (available: sequential",
                                             backend_available(backend::openmp) ? ", openmp" : "",
                                             ")"));
  }
}

/// Throws stale_result_error for a poisoned result.
void expect_not_poisoned(const my_bfs_state& st, const char* function) {
  if (st.poisoned) {
    throw stale_result_error(concat_message(
        "dyng: ", function, ": a failed update left this result unusable; recompute it"));
  }
}

/// The state of a result, or invalid_argument_error for a moved-from one.
template <typename state_t>
state_t& checked(state_t* st, const char* function) {
  DYNG_EXPECTS(st != nullptr, function, ": the result was moved from");
  expect_not_poisoned(*st, function);
  return *st;
}

}  // namespace

my_bfs_state& my_bfs_access::state(my_bfs::result& r) {
  DYNG_EXPECTS(r.impl_ != nullptr, "my_bfs: the result was moved from");
  return *r.impl_;
}

const my_bfs_state& my_bfs_access::state(const my_bfs::result& r) {
  DYNG_EXPECTS(r.impl_ != nullptr, "my_bfs: the result was moved from");
  return *r.impl_;
}

my_bfs::result my_bfs_access::make(std::unique_ptr<my_bfs_state> st) {
  return my_bfs::result(std::move(st));
}

// [tutorial: reserve]
void my_bfs_workspace::reserve(std::size_t n) {
  if (queue.capacity() < n || before.capacity() < n || queued.size() < n) {
    note_reservation();  // invariant I9: a reserving run (core/budget_counters.hpp)
    queue.reserve(n);
    before.reserve(n);
    lists[0].reserve(n);
    lists[1].reserve(n);
    queued.resize(n, 0);
  }
}

std::size_t my_bfs_workspace::bytes() const noexcept {
  return (queue.capacity() + before.capacity() + lists[0].capacity() + lists[1].capacity()) *
             sizeof(std::int64_t) +
         queued.capacity();
}
// [tutorial: reserve end]

// ------------------------------------------------------------------------------------------------
// The problem
// ------------------------------------------------------------------------------------------------

template <typename vertex_t, typename edge_t, typename weight_t>
void my_bfs_problem<vertex_t, edge_t, weight_t>::begin_update(framework::context& ctx, old_graph g,
                                                              const requested& /*batch*/) {
  expect_backend(ctx.res(), "my_bfs::update");
  graph_access::expect_placement(ctx.res(), g.get(), "my_bfs::update");
  expect_not_poisoned(*state_, "my_bfs::update");
  framework::expect_current_result("my_bfs::update", state_->version, state_->graph_state, g.get());
  // [tutorial: requirement]
  DYNG_EXPECTS(g->properties().store_transposed,
               "my_bfs::update: the graph must store its in-edges");
  // [tutorial: requirement end]
}

template <typename vertex_t, typename edge_t, typename weight_t>
void my_bfs_problem<vertex_t, edge_t, weight_t>::resume(framework::context& ctx, new_graph g,
                                                        const applied& applied) {
  applied_ = &applied;  // [tutorial: resume]
  const auto n = static_cast<std::size_t>(g->num_vertices());
  ws_.emplace(ctx.lease_workspace<my_bfs_workspace>());
  (*ws_)->reserve(n);
  if (state_->levels.capacity() < n) {
    note_reservation();  // the result grows with the graph (invariant I9)
  }
  state_->levels.resize(n, -1);  // new vertices start unreached
  (*ws_)->before.assign(state_->levels.begin(), state_->levels.end());
}

template <typename vertex_t, typename edge_t, typename weight_t>
void my_bfs_problem<vertex_t, edge_t, weight_t>::end_update(framework::context& /*ctx*/,
                                                            new_graph g,
                                                            const stats_type& /*stats*/) {
  framework::stamp_result(state_->version, state_->graph_state, g.get());
  ws_.reset();
}

template <typename vertex_t, typename edge_t, typename weight_t>
void my_bfs_problem<vertex_t, edge_t, weight_t>::solve(framework::context& ctx,
                                                       const container_type& g) {
  if (!ws_) {
    ws_.emplace(ctx.lease_workspace<my_bfs_workspace>());
    (*ws_)->reserve(static_cast<std::size_t>(g.num_vertices()));
  }
  const auto out = graph_access::out_view(g);
  if (ctx.res().get_backend() == backend::openmp) {
    my_bfs_openmp(ctx.res(), out, state_->opt.source, state_->levels, ws_->get());
    return;
  }
  my_bfs_sequential(out, state_->opt.source, state_->levels, ws_->get());
}

// [tutorial: identify_affected]
template <typename vertex_t, typename edge_t, typename weight_t>
void my_bfs_problem<vertex_t, edge_t, weight_t>::identify_affected(framework::context& /*ctx*/,
                                                                   new_graph g,
                                                                   const applied& applied,
                                                                   frontier_type& /*f*/) {
  // A deleted edge u -> v on a shortest path (before[v] == before[u] + 1) may have pushed v
  // farther from the source, and with it every vertex below v on a shortest path. Invalidate
  // them all (level -1); ws.before keeps the old levels, and the queue every invalidated vertex.
  const auto out = graph_access::out_view(g.get());
  std::vector<std::int64_t>& levels = state_->levels;
  const std::vector<std::int64_t>& before = (*ws_)->before;
  std::vector<std::int64_t>& queue = (*ws_)->queue;
  queue.clear();
  const apply_delta<vertex_t>& delta = applied.delta;
  for (std::size_t i = 0; i < delta.delete_src.size(); ++i) {
    const auto u = static_cast<std::size_t>(delta.delete_src[i]);
    const auto v = static_cast<std::size_t>(delta.delete_dst[i]);
    if (before[u] >= 0 && before[v] == before[u] + 1 && levels[v] != -1) {
      levels[v] = -1;
      queue.push_back(static_cast<std::int64_t>(v));
    }
  }
  for (std::size_t head = 0; head < queue.size(); ++head) {
    const auto x = static_cast<std::size_t>(queue[head]);
    for (auto e = out.row_ptr[x]; e < out.row_ptr[x + 1]; ++e) {
      const auto y = static_cast<std::size_t>(out.col_ind[static_cast<std::size_t>(e)]);
      if (before[y] == before[x] + 1 && levels[y] != -1) {
        levels[y] = -1;
        queue.push_back(static_cast<std::int64_t>(y));
      }
    }
  }
}
// [tutorial: identify_affected end]

// [tutorial: offer]
template <typename vertex_t, typename edge_t, typename weight_t>
void my_bfs_problem<vertex_t, edge_t, weight_t>::offer(std::int64_t from, std::int64_t v,
                                                       frontier_type& f) {
  std::int64_t& level = state_->levels[static_cast<std::size_t>(v)];
  if (from < 0 || (level >= 0 && level <= from + 1)) {
    return;  // nothing to offer, or not shorter
  }
  level = from + 1;
  std::uint8_t& queued = (*ws_)->queued[static_cast<std::size_t>(v)];
  if (queued == 0) {  // each vertex once per frontier
    queued = 1;
    f.items->push_back(v);
  }
}
// [tutorial: offer end]

// [tutorial: seed]
template <typename vertex_t, typename edge_t, typename weight_t>
void my_bfs_problem<vertex_t, edge_t, weight_t>::seed(framework::context& ctx, new_graph g,
                                                      frontier_type& f) {
  // The first frontier. Every invalidated vertex takes the best level its in-neighbours offer
  // (an in-neighbour that is still invalid offers nothing), and every inserted edge u -> v
  // offers level[u] + 1 to v.
  my_bfs_workspace& ws = ws_->get();
  f.items = &ws.lists[0];
  f.items->clear();
  const auto view = graph_access::view(ctx.res(), g.get());
  const std::vector<std::int64_t>& levels = state_->levels;
  for (const std::int64_t x : ws.queue) {
    const auto row = static_cast<std::size_t>(x);
    for (auto e = view.in.row_ptr[row]; e < view.in.row_ptr[row + 1]; ++e) {
      const auto u = static_cast<std::size_t>(view.in.col_ind[static_cast<std::size_t>(e)]);
      offer(levels[u], x, f);
    }
  }
  // applied.delta lists the insertions the batch REQUESTED. A batch may insert u -> v and delete
  // it again (batch_semantics::deletions_first = false), so offer only along an edge that is
  // still in G_{t+1}: look for v in u's out-row.
  const apply_delta<vertex_t>& delta = applied_->delta;
  for (std::size_t i = 0; i < delta.insert_src.size(); ++i) {
    const auto u = static_cast<std::size_t>(delta.insert_src[i]);
    const auto v = static_cast<std::int64_t>(delta.insert_dst[i]);
    for (auto e = view.out.row_ptr[u]; e < view.out.row_ptr[u + 1]; ++e) {
      if (static_cast<std::int64_t>(view.out.col_ind[static_cast<std::size_t>(e)]) == v) {
        offer(levels[u], v, f);
        break;
      }
    }
  }
}
// [tutorial: seed end]

// [tutorial: loop]
template <typename vertex_t, typename edge_t, typename weight_t>
void my_bfs_problem<vertex_t, edge_t, weight_t>::loop(framework::context& /*ctx*/, new_graph g,
                                                      frontier_type& in, frontier_type& out) {
  // One round: every frontier vertex u offers level[u] + 1 to its out-neighbours. The enactor
  // calls loop again, with the two frontiers swapped, until the frontier is empty.
  my_bfs_workspace& ws = ws_->get();
  out.items = in.items == &ws.lists[0] ? &ws.lists[1] : &ws.lists[0];
  out.items->clear();
  for (const std::int64_t u : *in.items) {
    ws.queued[static_cast<std::size_t>(u)] = 0;  // u may join the next frontier again
  }
  const auto graph = graph_access::out_view(g.get());
  for (const std::int64_t u : *in.items) {
    const auto row = static_cast<std::size_t>(u);
    for (auto e = graph.row_ptr[row]; e < graph.row_ptr[row + 1]; ++e) {
      offer(state_->levels[row], graph.col_ind[static_cast<std::size_t>(e)], out);
    }
  }
}
// [tutorial: loop end]

// [tutorial: seed_static]
template <typename vertex_t, typename edge_t, typename weight_t>
void my_bfs_problem<vertex_t, edge_t, weight_t>::seed_static(framework::context& ctx, new_graph g,
                                                             frontier_type& /*f*/) {
  // compute(): the static solve (sequential.cpp) sets every level at once, so the frontier stays
  // empty and the loop does not run.
  solve(ctx, g.get());
}
// [tutorial: seed_static end]

template <typename vertex_t, typename edge_t, typename weight_t>
void my_bfs_problem<vertex_t, edge_t, weight_t>::finalize(framework::context& /*ctx*/,
                                                          stats_type& stats) {
  if (computing_) {
    return;
  }
  const std::vector<std::int64_t>& before = (*ws_)->before;
  std::int64_t changed = 0;
  for (std::size_t v = 0; v < state_->levels.size(); ++v) {
    changed += (v >= before.size() || before[v] != state_->levels[v]) ? 1 : 0;
  }
  stats.affected = changed;
}

template <typename vertex_t, typename edge_t, typename weight_t>
void my_bfs_problem<vertex_t, edge_t, weight_t>::reset(framework::context& /*ctx*/) {
  computing_ = true;
}

}  // namespace dyng::detail

// ------------------------------------------------------------------------------------------------
// The public functions
// ------------------------------------------------------------------------------------------------

namespace dyng::my_bfs {

result::result(std::unique_ptr<detail::my_bfs_state> state) noexcept : impl_(std::move(state)) {}
result::result(result&& other) noexcept = default;
result& result::operator=(result&& other) noexcept = default;
result::~result() = default;

array_view<const std::int64_t> result::levels() const {
  const auto& st = detail::checked(impl_.get(), "my_bfs::result::levels");
  return host_view(st.levels);
}

const options& result::get_options() const {
  return detail::checked(impl_.get(), "my_bfs::result::get_options").opt;
}

void result::set_options(const options& opt) {
  auto& st = detail::checked(impl_.get(), "my_bfs::result::set_options");
  DYNG_EXPECTS(opt.source == st.opt.source,
               "my_bfs::result::set_options: the source is fixed at compute()");
  st.opt = opt;
}

std::uint64_t result::graph_version() const noexcept {
  return impl_ == nullptr ? 0 : impl_->version;
}

memory_space result::space() const noexcept {
  return memory_space::host;
}

result result::clone(const resources& res) const {
  const auto& st = detail::checked(impl_.get(), "my_bfs::result::clone");
  detail::expect_backend(res, "my_bfs::result::clone");
  return result(std::make_unique<detail::my_bfs_state>(st));
}

}  // namespace dyng::my_bfs

namespace dyng::detail {

// compute() and update() behind the public wrappers of the header (which static_assert the
// supported graph types).
template <typename vertex_t, typename edge_t, typename weight_t>
my_bfs::result my_bfs_compute(const resources& res, const graph<vertex_t, edge_t, weight_t>& g,
                              const my_bfs::options& opt) {
  using problem_t = detail::my_bfs_problem<vertex_t, edge_t, weight_t>;
  detail::expect_backend(res, "my_bfs::compute");
  detail::graph_access::expect_placement(res, g, "my_bfs::compute");
  DYNG_EXPECTS(opt.source >= 0 && opt.source < static_cast<std::int64_t>(g.num_vertices()),
               "my_bfs::compute: the source ", opt.source, " is not a vertex of the graph (",
               g.num_vertices(), " vertices)");
  const detail::framework::hook_stages& names = detail::framework::stages_of<problem_t>();
  scoped_stage stage(res, names.compute);
  auto st = std::make_unique<detail::my_bfs_state>();
  st->opt = opt;
  problem_t p(*st);
  detail::framework::context ctx(res, problem_t::name);
  detail::framework::static_enactor<problem_t> enactor(p);
  (void)enactor.run(ctx, detail::framework::new_view<graph<vertex_t, edge_t, weight_t>>(g));
  detail::framework::stamp_result(st->version, st->graph_state, g);
  return detail::my_bfs_access::make(std::move(st));
}

template <typename vertex_t, typename edge_t, typename weight_t>
my_bfs::stats my_bfs_update(const resources& res, graph<vertex_t, edge_t, weight_t>& g,
                            const edge_batch_view<vertex_t, weight_t>& batch, my_bfs::result& r) {
  using problem_t = detail::my_bfs_problem<vertex_t, edge_t, weight_t>;
  return detail::framework::update_one<problem_t>(res, g, batch, r);
}

template <typename vertex_t, typename edge_t, typename weight_t>
std::unique_ptr<update_participant<vertex_t, edge_t, weight_t>> make_my_bfs_participant(
    my_bfs::result& r, my_bfs::stats& out) {
  using problem_t = my_bfs_problem<vertex_t, edge_t, weight_t>;
  return framework::make_participant<problem_t>(out, r);
}

// Explicit instantiations (PLAN Section 4.4.3).
#define DYNG_INSTANTIATE_MY_BFS(V, E, W)                                                   \
  template class my_bfs_problem<V, E, W>;                                                  \
  template std::unique_ptr<update_participant<V, E, W>> make_my_bfs_participant<V, E, W>(  \
      my_bfs::result&, my_bfs::stats&);                                                    \
  template my_bfs::result my_bfs_compute<V, E, W>(const resources&, const graph<V, E, W>&, \
                                                  const my_bfs::options&);                 \
  template my_bfs::stats my_bfs_update<V, E, W>(const resources&, graph<V, E, W>&,         \
                                                const edge_batch_view<V, W>&, my_bfs::result&);
DYNG_FOR_EACH_GRAPH_TYPE(DYNG_INSTANTIATE_MY_BFS)
#undef DYNG_INSTANTIATE_MY_BFS

}  // namespace dyng::detail
