// SPDX-FileCopyrightText: 2026 The dynG Authors
// SPDX-License-Identifier: Apache-2.0
/**
 * @file problem.hpp
 * @brief The my_bfs problem on the framework (cpp/src/framework): its hooks, its
 *        state and its workspace (generated by scripts/new_algorithm.py).
 *
 * Template card (PLAN Section 4.5.2; docs/developer/framework.md):
 *
 *     normalize -> prepare -> before_apply -> commit ->
 *     identify_affected -> seed -> { loop until is_converged } -> finalize
 *
 * A fixed-point problem, made incremental by the tutorial "Your first dynamic algorithm"
 * (docs/tutorials/your_first_dynamic_algorithm.md; this is its reference solution).
 * identify_affected invalidates every vertex below a deleted shortest-path edge (level -1); seed
 * puts on the first frontier the invalidated vertices that an in-neighbour reaches and the heads
 * of the inserted edges that are in G_{t+1}; loop offers level + 1 to the out-neighbours of the
 * frontier, round after round, until the frontier is empty; finalize counts the changed levels.
 * update() never recomputes (stats::fallback_used stays false).
 *
 * compute() is the static enactor with the same hooks (reset first). Lifecycle members without a
 * stage: begin_update (the checks before anything changes), resume (bind G_{t+1}, grow the
 * result, lease the workspace), end_update (record the graph state), poison.
 */
#pragma once

#include "framework/budgets.hpp"
#include "framework/composition.hpp"
#include "framework/context.hpp"
#include "framework/frontier.hpp"
#include "framework/policies.hpp"
#include "framework/problem.hpp"
#include "framework/views.hpp"
#include "framework/workspace.hpp"

#include <dyng/core/backend.hpp>
#include <dyng/core/resources.hpp>
#include <dyng/graph/csr.hpp>
#include <dyng/graph/graph.hpp>
#include <dyng/my_bfs.hpp>

#include <cstddef>
#include <cstdint>
#include <optional>
#include <string_view>
#include <vector>

namespace dyng::detail {

/// The state behind an my_bfs::result.
struct my_bfs_state {
  my_bfs::options opt;               ///< the options
  std::vector<std::int64_t> levels;  ///< the hop level of every vertex, -1 if unreachable
  std::uint64_t version = 0;         ///< graph version matched
  std::uint64_t graph_state = 0;     ///< graph state matched (ADR 0006, "Graph identity")
  bool poisoned = false;             ///< a failed update left the result unusable
};

/// Access to the state of a result.
struct my_bfs_access {
  /// The state of `r`.
  static my_bfs_state& state(my_bfs::result& r);
  /// The state of `r`.
  static const my_bfs_state& state(const my_bfs::result& r);
  /// A result owning `st`.
  static my_bfs::result make(std::unique_ptr<my_bfs_state> st);
};

/// Scratch space of the engines, leased from the workspace pool of the resources handle (ADR 0015).
struct my_bfs_workspace final : pooled_workspace {
  std::vector<std::int64_t> queue;   ///< the search queue
  std::vector<std::int64_t> before;  ///< the levels before the update (the stats)
  // [tutorial: workspace]
  std::vector<std::int64_t> lists[2];  ///< the two frontier lists (a loop round's in and out)
  std::vector<std::uint8_t> queued;    ///< 1 while a vertex waits on the next frontier
  // [tutorial: workspace end]

  /// Size the arrays for `n` vertices (a reservation when they grow, invariant I9).
  void reserve(std::size_t n);

  /// Bytes of the arrays' capacities.
  [[nodiscard]] std::size_t bytes() const noexcept override;
};

/**
 * @brief The static solve on the sequential backend: hop levels from `source` (breadth-first).
 * @tparam vertex_t Vertex id type.
 * @tparam edge_t   Edge offset type.
 * @tparam weight_t Weight type.
 * @param[in]     out    The out-edges (host).
 * @param[in]     source The source vertex.
 * @param[out]    levels One level per vertex (resized to the vertex count).
 * @param[in,out] ws     The workspace (reserved for the vertex count).
 */
template <typename vertex_t, typename edge_t, typename weight_t>
void my_bfs_sequential(const csr_view<vertex_t, edge_t, weight_t>& out, std::int64_t source,
                       std::vector<std::int64_t>& levels, my_bfs_workspace& ws);

/**
 * @brief The static solve on the OpenMP backend (as my_bfs_sequential()).
 * @tparam vertex_t Vertex id type.
 * @tparam edge_t   Edge offset type.
 * @tparam weight_t Weight type.
 * @param[in]     res    The resources (their thread count).
 * @param[in]     out    The out-edges (host).
 * @param[in]     source The source vertex.
 * @param[out]    levels One level per vertex.
 * @param[in,out] ws     The workspace.
 */
template <typename vertex_t, typename edge_t, typename weight_t>
void my_bfs_openmp(const resources& res, const csr_view<vertex_t, edge_t, weight_t>& out,
                   std::int64_t source, std::vector<std::int64_t>& levels, my_bfs_workspace& ws);

// [tutorial: frontier]
/// The frontier of the loop: a list of vertices kept in the workspace. The enactor owns two
/// frontier objects (a round's in and out), so the type must be default-constructible without
/// allocating; empty() is the enactor's convergence test.
struct my_bfs_frontier {
  std::vector<std::int64_t>* items = nullptr;  ///< the vertices (a list of the workspace)

  /// Whether the frontier is empty (the loop stops).
  [[nodiscard]] bool empty() const noexcept {
    return items == nullptr || items->empty();
  }
};
// [tutorial: frontier end]

/// The update family of my_bfs.
inline constexpr framework::family my_bfs_family = framework::family::fixed_point;

/**
 * @brief The my_bfs problem (see the file comment).
 * @tparam vertex_t Vertex id type.
 * @tparam edge_t   Edge offset type.
 * @tparam weight_t Weight type.
 */
template <typename vertex_t, typename edge_t, typename weight_t>
class my_bfs_problem final
    : public framework::problem_base<my_bfs_problem<vertex_t, edge_t, weight_t>, my_bfs_family> {
 public:
  static constexpr std::string_view name = "my_bfs";         ///< stages "<name>.<hook>"
  using container_type = graph<vertex_t, edge_t, weight_t>;  ///< the container
  using stats_type = my_bfs::stats;                          ///< the stats of update()
  using frontier_type = my_bfs_frontier;  ///< the loop's frontier (the workspace's lists)
  using old_graph = framework::old_view<container_type>;             ///< G_t
  using new_graph = framework::new_view<container_type>;             ///< G_{t+1}
  using requested = framework::requested_batch<vertex_t, weight_t>;  ///< the batch before commit
  using applied = framework::applied_batch<vertex_t>;                ///< what the commit did

  /// The problem of one update of `r`.
  explicit my_bfs_problem(my_bfs::result& r) : state_(&my_bfs_access::state(r)), target_(&r) {}
  /// The problem of one compute() filling `st`.
  explicit my_bfs_problem(my_bfs_state& st) : state_(&st) {}

  // ---- lifecycle (no stage) ----

  /// The result this problem updates (nullptr for compute()).
  [[nodiscard]] const void* target() const noexcept {
    return target_;
  }
  /// The checks before anything changes: backend, poisoned and stale result.
  void begin_update(framework::context& ctx, old_graph g, const requested& batch);
  /// Bind G_{t+1}: grow the result for new vertices, lease the workspace.
  void resume(framework::context& ctx, new_graph g, const applied& applied);
  /// Record the graph state the result matches; return the workspace.
  void end_update(framework::context& ctx, new_graph g, const stats_type& stats);
  /// Mark the result unusable (a failed algorithm phase).
  void poison() noexcept {
    state_->poisoned = true;
  }
  /// The seed reads the in-edges: the commit builds them once for every result.
  [[nodiscard]] bool reads_prepared_graph() const noexcept {
    return true;
  }
  /// The budget of the algorithm phase (invariant I9, conformance check C8): nothing allocated
  /// once reserved, no host synchronization.
  [[nodiscard]] framework::budget algorithm_budget(framework::context& /*ctx*/) const noexcept {
    return framework::budget::steady_state(0);
  }

  // [tutorial: hooks]
  // ---- Step 1b ----

  /// my_bfs.identify_affected: invalidate what the deletions may have made farther.
  void identify_affected(framework::context& ctx, new_graph g, const applied& applied,
                         frontier_type& f);
  /// my_bfs.seed: the first frontier (the invalidated vertices and the inserted edges).
  void seed(framework::context& ctx, new_graph g, frontier_type& f);

  // ---- Step 2 ----

  /// my_bfs.loop: one round of offers from the frontier `in` into the frontier `out`.
  void loop(framework::context& ctx, new_graph g, frontier_type& in, frontier_type& out);
  // [tutorial: hooks end]
  /// my_bfs.finalize: the stats (the number of vertices whose level changed).
  void finalize(framework::context& ctx, stats_type& stats);

  // ---- compute() ----

  /// my_bfs.reset: start the static solve.
  void reset(framework::context& ctx);
  /// my_bfs.seed (static): the static solve; nothing is left for the loop.
  void seed_static(framework::context& ctx, new_graph g, frontier_type& f);

 private:
  /// The static solve of `g` into the state.
  void solve(framework::context& ctx, const container_type& g);
  /// Offer the level `from + 1` to `v` (`from`: the level of an in-neighbour, -1 if unreached).
  void offer(std::int64_t from, std::int64_t v, frontier_type& f);

  my_bfs_state* state_ = nullptr;
  const my_bfs::result* target_ = nullptr;
  bool computing_ = false;
  std::optional<workspace_pool::lease<my_bfs_workspace>> ws_;
  const applied* applied_ = nullptr;  ///< what the commit did (identify_affected, seed)
};

}  // namespace dyng::detail
