# SPDX-FileCopyrightText: 2026 The dynG Authors
# SPDX-License-Identifier: Apache-2.0
# Generated by scripts/regen.py from the manifests; do not edit.
"""The registered algorithms (from the manifests): each is the module ``dyng.<name>``."""

from __future__ import annotations

#: name -> title, first release, container and maturity of every algorithm with a manifest.
ALGORITHMS: dict[str, dict[str, str]] = {
    "sssp": {
        "title": "Dynamic single-source shortest paths",
        "since": "0.1",
        "container": "graph",
        "maturity": "stable",
    },
    "cycle_count": {
        "title": "Exact k-bounded directed simple-cycle histograms",
        "since": "0.1",
        "container": "graph",
        "maturity": "stable",
    },
    "mosp": {
        "title": "Dynamic multi-objective shortest paths",
        "since": "0.2",
        "container": "graph",
        "maturity": "experimental",
    },
    "dynamic_bfs": {
        "title": "Dynamic breadth-first search levels (tutorial)",
        "since": "0.2",
        "container": "graph",
        "maturity": "tutorial",
    },
    "triangle_delta": {
        "title": "Dynamic triangle count (tutorial)",
        "since": "0.2",
        "container": "graph",
        "maturity": "tutorial",
    },
}
