# SPDX-FileCopyrightText: 2026 The dynG Authors
# SPDX-License-Identifier: Apache-2.0
# The stubs of the extension module dyng._core, generated by nanobind.stubgen
# (python scripts/regen.py --stubs); do not edit.
"""
dynG's native module (private: use the `dyng` package; these names may change in any release).
"""

import enum
from typing import Annotated, Any, overload

import numpy
from numpy.typing import NDArray


class Backend(enum.Enum):
    """An execution backend."""

    sequential = 0

    openmp = 1

    cuda = 2

class MemorySpace(enum.Enum):
    """A memory space."""

    host = 0

    pinned_host = 1

    device = 2

    managed = 3

class CopyPolicy(enum.Enum):
    """What to do before an implicit copy of an input."""

    allow = 0

    warn = 1

    error = 2

class Engine(enum.Enum):
    """An update engine."""

    automatic = 0

    fused = 1

    operators = 2

class Determinism(enum.Enum):
    """What two runs agree on."""

    bitwise = 0

    exact_value = 1

    tolerance = 2

class LogLevel(enum.Enum):
    """A log level."""

    off = 0

    error = 1

    warn = 2

    info = 3

    debug = 4

    trace = 5

def backend_available(backend: Backend) -> bool:
    """Whether a backend is compiled in (and, for cuda, a device is visible)."""

def default_backend() -> Backend:
    """The backend of default resources."""

def set_log_level(level: LogLevel) -> None:
    """Set the library's log level."""

def get_log_level() -> LogLevel:
    """The library's log level."""

class Resources:
    """Execution resources (a shared handle)."""

    def __init__(self) -> None:
        """Resources of the default backend."""

    @staticmethod
    def sequential() -> Resources:
        """The sequential backend."""

    @staticmethod
    def openmp(num_threads: int = 0) -> Resources:
        """The OpenMP backend (0 threads: the OpenMP default)."""

    @staticmethod
    def cuda(device: int = 0, stream: int = 0, host_threads: int = 0) -> Resources:
        """
        The CUDA backend (stream: a cudaStream_t as an integer, 0 = per-thread default).
        """

    @property
    def backend(self) -> Backend: ...

    @property
    def device(self) -> int: ...

    @property
    def stream(self) -> int: ...

    @property
    def num_threads(self) -> int: ...

    @property
    def default_space(self) -> MemorySpace: ...

    @property
    def copy_policy(self) -> CopyPolicy: ...

    @copy_policy.setter
    def copy_policy(self, arg: CopyPolicy, /) -> None: ...

    @property
    def workspace_bytes(self) -> int: ...

    def release_workspaces(self) -> None: ...

    def warm_up(self) -> None: ...

    def synchronize(self) -> None: ...

    def attach_profiler(self, profiler: Profiler | None) -> None:
        """
        Attach a profiler to the handle (None detaches); the profiler is kept alive by this object.
        """

    def has_profiler(self) -> bool: ...

def library_version() -> str:
    """The version of the compiled library."""

build_config: dict = ...

def openmp_max_threads() -> int: ...

class Profiler:
    """Records the library's stages and counters."""

    def __init__(self, sync_stages: bool = False, nvtx: bool = False, cuda_events: bool = False) -> None: ...

    def stages(self) -> list[tuple[str, int, int, float, float]]:
        """
        (name, depth, calls, host_ms, device_ms) per stage, in first-call order.
        """

    def samples(self) -> list[tuple[str, int, float, float]]:
        """
        (name, depth, host_ms, device_ms) per completed call, in completion order.
        """

    def counters(self) -> list[tuple[str, int]]:
        """(name, value) per counter."""

    def reset(self) -> None: ...

    def to_csv(self) -> str: ...

    def to_json(self) -> str: ...

class RowLayout(enum.Enum):
    """The storage layout of the rows."""

    compact = 0

    slotted = 1

    slack = 2

class RowOrder(enum.Enum):
    """The order of the neighbours in a row."""

    sorted = 0

    append = 1

class MultiEdges(enum.Enum):
    """Whether parallel edges may exist."""

    forbid = 0

    allow = 1

class ExistingInsert(enum.Enum):
    """What an insertion of an existing edge does."""

    upsert = 0

    error = 1

    ignore = 2

class MissingDelete(enum.Enum):
    """What a deletion of a missing edge does."""

    ignore = 0

    error = 1

class SelfLoop(enum.Enum):
    """What a self-loop in a batch does."""

    keep = 0

    drop = 1

    error = 2

class BatchSemantics:
    """How a batch of edge changes is interpreted."""

    def __init__(self) -> None: ...

    @property
    def on_existing_insert(self) -> ExistingInsert: ...

    @on_existing_insert.setter
    def on_existing_insert(self, arg: ExistingInsert, /) -> None: ...

    @property
    def on_missing_delete(self) -> MissingDelete: ...

    @on_missing_delete.setter
    def on_missing_delete(self, arg: MissingDelete, /) -> None: ...

    @property
    def on_self_loop(self) -> SelfLoop: ...

    @on_self_loop.setter
    def on_self_loop(self, arg: SelfLoop, /) -> None: ...

    @property
    def deletions_first(self) -> bool: ...

    @deletions_first.setter
    def deletions_first(self, arg: bool, /) -> None: ...

    @property
    def allow_vertex_growth(self) -> bool: ...

    @allow_vertex_growth.setter
    def allow_vertex_growth(self, arg: bool, /) -> None: ...

    @property
    def as_sets(self) -> bool: ...

    @as_sets.setter
    def as_sets(self, arg: bool, /) -> None: ...

    @staticmethod
    def upsert_last_wins() -> BatchSemantics: ...

    @staticmethod
    def set() -> BatchSemantics: ...

class GraphProperties:
    """The properties of a graph."""

    def __init__(self) -> None: ...

    @property
    def directed(self) -> bool: ...

    @directed.setter
    def directed(self, arg: bool, /) -> None: ...

    @property
    def store_transposed(self) -> bool: ...

    @store_transposed.setter
    def store_transposed(self, arg: bool, /) -> None: ...

    @property
    def num_weights(self) -> int: ...

    @num_weights.setter
    def num_weights(self, arg: int, /) -> None: ...

    @property
    def layout(self) -> RowLayout: ...

    @layout.setter
    def layout(self, arg: RowLayout, /) -> None: ...

    @property
    def headroom(self) -> float: ...

    @headroom.setter
    def headroom(self, arg: float, /) -> None: ...

    @property
    def order(self) -> RowOrder: ...

    @order.setter
    def order(self, arg: RowOrder, /) -> None: ...

    @property
    def parallel_edges(self) -> MultiEdges: ...

    @parallel_edges.setter
    def parallel_edges(self, arg: MultiEdges, /) -> None: ...

    @property
    def semantics(self) -> BatchSemantics: ...

    @semantics.setter
    def semantics(self, arg: BatchSemantics, /) -> None: ...

    @staticmethod
    def mosp_compatible() -> GraphProperties: ...

    @staticmethod
    def cycle_enum_compatible() -> GraphProperties: ...

class ApplySummary:
    """What applying a batch did to a graph."""

    @property
    def inserted_edges(self) -> int: ...

    @property
    def updated_edges(self) -> int: ...

    @property
    def deleted_edges(self) -> int: ...

    @property
    def ignored_deletions(self) -> int: ...

    @property
    def dropped_self_loops(self) -> int: ...

    @property
    def cancelled_pairs(self) -> int: ...

    @property
    def inserted_vertices(self) -> int: ...

    @property
    def deleted_vertices(self) -> int: ...

    @property
    def num_vertices_after(self) -> int: ...

    @property
    def ignored_insertions(self) -> int: ...

class GraphI32I32I32:
    """A dyng::graph instantiation (private)."""

    @staticmethod
    def from_edges(resources: Resources, num_vertices: int, src: Annotated[NDArray[numpy.int32], dict(shape=(None,), order='C', device='cpu', writable=False)], dst: Annotated[NDArray[numpy.int32], dict(shape=(None,), order='C', device='cpu', writable=False)], weights: Annotated[NDArray[numpy.int32], dict(shape=(None,), order='C', device='cpu', writable=False)] | None, num_weights: int, properties: GraphProperties) -> GraphI32I32I32:
        """Build a graph from an edge list (edge-major weights)."""

    @staticmethod
    def from_csr(resources: Resources, row_ptr: Annotated[NDArray[numpy.int32], dict(shape=(None,), order='C', device='cpu', writable=False)], col_ind: Annotated[NDArray[numpy.int32], dict(shape=(None,), order='C', device='cpu', writable=False)], weights: Annotated[NDArray[numpy.int32], dict(shape=(None,), order='C', device='cpu', writable=False)] | None, num_weights: int, properties: GraphProperties) -> GraphI32I32I32:
        """Build a graph from a CSR of the out-edges (objective-major weights)."""

    @property
    def num_vertices(self) -> int: ...

    @property
    def num_edges(self) -> int: ...

    @property
    def num_weights(self) -> int: ...

    @property
    def directed(self) -> bool: ...

    @property
    def has_transposed(self) -> bool: ...

    @property
    def space(self) -> MemorySpace: ...

    @property
    def version(self) -> int: ...

    @property
    def properties(self) -> GraphProperties: ...

    def to_csr(self, resources: Resources) -> tuple:
        """
        (row_ptr, col_ind, weights of shape (K, m) or None): a host copy of the out-edges.
        """

    def apply(self, resources: Resources, batch: EdgeBatchI32I32) -> ApplySummary:
        """Apply a batch to the graph."""

    def clone(self, resources: Resources) -> GraphI32I32I32:
        """A deep copy for `resources`."""

    def to_backend(self, resources: Resources) -> GraphI32I32I32:
        """The graph for the backend of `resources`."""

    def reserve(self, resources: Resources, edge_capacity: int) -> None: ...

    def check_integrity(self, resources: Resources) -> None: ...

class GraphI32I64I32:
    """A dyng::graph instantiation (private)."""

    @staticmethod
    def from_edges(resources: Resources, num_vertices: int, src: Annotated[NDArray[numpy.int32], dict(shape=(None,), order='C', device='cpu', writable=False)], dst: Annotated[NDArray[numpy.int32], dict(shape=(None,), order='C', device='cpu', writable=False)], weights: Annotated[NDArray[numpy.int32], dict(shape=(None,), order='C', device='cpu', writable=False)] | None, num_weights: int, properties: GraphProperties) -> GraphI32I64I32:
        """Build a graph from an edge list (edge-major weights)."""

    @staticmethod
    def from_csr(resources: Resources, row_ptr: Annotated[NDArray[numpy.int64], dict(shape=(None,), order='C', device='cpu', writable=False)], col_ind: Annotated[NDArray[numpy.int32], dict(shape=(None,), order='C', device='cpu', writable=False)], weights: Annotated[NDArray[numpy.int32], dict(shape=(None,), order='C', device='cpu', writable=False)] | None, num_weights: int, properties: GraphProperties) -> GraphI32I64I32:
        """Build a graph from a CSR of the out-edges (objective-major weights)."""

    @property
    def num_vertices(self) -> int: ...

    @property
    def num_edges(self) -> int: ...

    @property
    def num_weights(self) -> int: ...

    @property
    def directed(self) -> bool: ...

    @property
    def has_transposed(self) -> bool: ...

    @property
    def space(self) -> MemorySpace: ...

    @property
    def version(self) -> int: ...

    @property
    def properties(self) -> GraphProperties: ...

    def to_csr(self, resources: Resources) -> tuple:
        """
        (row_ptr, col_ind, weights of shape (K, m) or None): a host copy of the out-edges.
        """

    def apply(self, resources: Resources, batch: EdgeBatchI32I32) -> ApplySummary:
        """Apply a batch to the graph."""

    def clone(self, resources: Resources) -> GraphI32I64I32:
        """A deep copy for `resources`."""

    def to_backend(self, resources: Resources) -> GraphI32I64I32:
        """The graph for the backend of `resources`."""

    def reserve(self, resources: Resources, edge_capacity: int) -> None: ...

    def check_integrity(self, resources: Resources) -> None: ...

class GraphI64I64I32:
    """A dyng::graph instantiation (private)."""

    @staticmethod
    def from_edges(resources: Resources, num_vertices: int, src: Annotated[NDArray[numpy.int64], dict(shape=(None,), order='C', device='cpu', writable=False)], dst: Annotated[NDArray[numpy.int64], dict(shape=(None,), order='C', device='cpu', writable=False)], weights: Annotated[NDArray[numpy.int32], dict(shape=(None,), order='C', device='cpu', writable=False)] | None, num_weights: int, properties: GraphProperties) -> GraphI64I64I32:
        """Build a graph from an edge list (edge-major weights)."""

    @staticmethod
    def from_csr(resources: Resources, row_ptr: Annotated[NDArray[numpy.int64], dict(shape=(None,), order='C', device='cpu', writable=False)], col_ind: Annotated[NDArray[numpy.int64], dict(shape=(None,), order='C', device='cpu', writable=False)], weights: Annotated[NDArray[numpy.int32], dict(shape=(None,), order='C', device='cpu', writable=False)] | None, num_weights: int, properties: GraphProperties) -> GraphI64I64I32:
        """Build a graph from a CSR of the out-edges (objective-major weights)."""

    @property
    def num_vertices(self) -> int: ...

    @property
    def num_edges(self) -> int: ...

    @property
    def num_weights(self) -> int: ...

    @property
    def directed(self) -> bool: ...

    @property
    def has_transposed(self) -> bool: ...

    @property
    def space(self) -> MemorySpace: ...

    @property
    def version(self) -> int: ...

    @property
    def properties(self) -> GraphProperties: ...

    def to_csr(self, resources: Resources) -> tuple:
        """
        (row_ptr, col_ind, weights of shape (K, m) or None): a host copy of the out-edges.
        """

    def apply(self, resources: Resources, batch: EdgeBatchI64I32) -> ApplySummary:
        """Apply a batch to the graph."""

    def clone(self, resources: Resources) -> GraphI64I64I32:
        """A deep copy for `resources`."""

    def to_backend(self, resources: Resources) -> GraphI64I64I32:
        """The graph for the backend of `resources`."""

    def reserve(self, resources: Resources, edge_capacity: int) -> None: ...

    def check_integrity(self, resources: Resources) -> None: ...

class GraphI32I32U:
    """A dyng::graph instantiation (private)."""

    @staticmethod
    def from_edges(resources: Resources, num_vertices: int, src: Annotated[NDArray[numpy.int32], dict(shape=(None,), order='C', device='cpu', writable=False)], dst: Annotated[NDArray[numpy.int32], dict(shape=(None,), order='C', device='cpu', writable=False)], weights: Annotated[NDArray[numpy.int32], dict(shape=(None,), order='C', device='cpu', writable=False)] | None, num_weights: int, properties: GraphProperties) -> GraphI32I32U:
        """Build a graph from an edge list (edge-major weights)."""

    @staticmethod
    def from_csr(resources: Resources, row_ptr: Annotated[NDArray[numpy.int32], dict(shape=(None,), order='C', device='cpu', writable=False)], col_ind: Annotated[NDArray[numpy.int32], dict(shape=(None,), order='C', device='cpu', writable=False)], weights: Annotated[NDArray[numpy.int32], dict(shape=(None,), order='C', device='cpu', writable=False)] | None, num_weights: int, properties: GraphProperties) -> GraphI32I32U:
        """Build a graph from a CSR of the out-edges (objective-major weights)."""

    @property
    def num_vertices(self) -> int: ...

    @property
    def num_edges(self) -> int: ...

    @property
    def num_weights(self) -> int: ...

    @property
    def directed(self) -> bool: ...

    @property
    def has_transposed(self) -> bool: ...

    @property
    def space(self) -> MemorySpace: ...

    @property
    def version(self) -> int: ...

    @property
    def properties(self) -> GraphProperties: ...

    def to_csr(self, resources: Resources) -> tuple:
        """
        (row_ptr, col_ind, weights of shape (K, m) or None): a host copy of the out-edges.
        """

    def apply(self, resources: Resources, batch: EdgeBatchI32U) -> ApplySummary:
        """Apply a batch to the graph."""

    def clone(self, resources: Resources) -> GraphI32I32U:
        """A deep copy for `resources`."""

    def to_backend(self, resources: Resources) -> GraphI32I32U:
        """The graph for the backend of `resources`."""

    def reserve(self, resources: Resources, edge_capacity: int) -> None: ...

    def check_integrity(self, resources: Resources) -> None: ...

class GraphI32I64U:
    """A dyng::graph instantiation (private)."""

    @staticmethod
    def from_edges(resources: Resources, num_vertices: int, src: Annotated[NDArray[numpy.int32], dict(shape=(None,), order='C', device='cpu', writable=False)], dst: Annotated[NDArray[numpy.int32], dict(shape=(None,), order='C', device='cpu', writable=False)], weights: Annotated[NDArray[numpy.int32], dict(shape=(None,), order='C', device='cpu', writable=False)] | None, num_weights: int, properties: GraphProperties) -> GraphI32I64U:
        """Build a graph from an edge list (edge-major weights)."""

    @staticmethod
    def from_csr(resources: Resources, row_ptr: Annotated[NDArray[numpy.int64], dict(shape=(None,), order='C', device='cpu', writable=False)], col_ind: Annotated[NDArray[numpy.int32], dict(shape=(None,), order='C', device='cpu', writable=False)], weights: Annotated[NDArray[numpy.int32], dict(shape=(None,), order='C', device='cpu', writable=False)] | None, num_weights: int, properties: GraphProperties) -> GraphI32I64U:
        """Build a graph from a CSR of the out-edges (objective-major weights)."""

    @property
    def num_vertices(self) -> int: ...

    @property
    def num_edges(self) -> int: ...

    @property
    def num_weights(self) -> int: ...

    @property
    def directed(self) -> bool: ...

    @property
    def has_transposed(self) -> bool: ...

    @property
    def space(self) -> MemorySpace: ...

    @property
    def version(self) -> int: ...

    @property
    def properties(self) -> GraphProperties: ...

    def to_csr(self, resources: Resources) -> tuple:
        """
        (row_ptr, col_ind, weights of shape (K, m) or None): a host copy of the out-edges.
        """

    def apply(self, resources: Resources, batch: EdgeBatchI32U) -> ApplySummary:
        """Apply a batch to the graph."""

    def clone(self, resources: Resources) -> GraphI32I64U:
        """A deep copy for `resources`."""

    def to_backend(self, resources: Resources) -> GraphI32I64U:
        """The graph for the backend of `resources`."""

    def reserve(self, resources: Resources, edge_capacity: int) -> None: ...

    def check_integrity(self, resources: Resources) -> None: ...

class EdgeBatchI32I32:
    """A batch of edge changes over arrays (private)."""

    def __init__(self, insert_src: Annotated[NDArray[numpy.int32], dict(shape=(None,), order='C', device='cpu', writable=False)], insert_dst: Annotated[NDArray[numpy.int32], dict(shape=(None,), order='C', device='cpu', writable=False)], insert_weights: Annotated[NDArray[numpy.int32], dict(shape=(None,), order='C', device='cpu', writable=False)] | None, delete_src: Annotated[NDArray[numpy.int32], dict(shape=(None,), order='C', device='cpu', writable=False)], delete_dst: Annotated[NDArray[numpy.int32], dict(shape=(None,), order='C', device='cpu', writable=False)], num_weights: int, insert_vertices: Annotated[NDArray[numpy.int32], dict(shape=(None,), order='C', device='cpu', writable=False)] | None, insert_vertex_labels: Annotated[NDArray[numpy.int8], dict(shape=(None,), order='C', device='cpu', writable=False)] | None, delete_vertices: Annotated[NDArray[numpy.int32], dict(shape=(None,), order='C', device='cpu', writable=False)] | None) -> None: ...

    @property
    def num_insertions(self) -> int: ...

    @property
    def num_deletions(self) -> int: ...

    @property
    def num_weights(self) -> int: ...

class EdgeBatchI64I32:
    """A batch of edge changes over arrays (private)."""

    def __init__(self, insert_src: Annotated[NDArray[numpy.int64], dict(shape=(None,), order='C', device='cpu', writable=False)], insert_dst: Annotated[NDArray[numpy.int64], dict(shape=(None,), order='C', device='cpu', writable=False)], insert_weights: Annotated[NDArray[numpy.int32], dict(shape=(None,), order='C', device='cpu', writable=False)] | None, delete_src: Annotated[NDArray[numpy.int64], dict(shape=(None,), order='C', device='cpu', writable=False)], delete_dst: Annotated[NDArray[numpy.int64], dict(shape=(None,), order='C', device='cpu', writable=False)], num_weights: int, insert_vertices: Annotated[NDArray[numpy.int64], dict(shape=(None,), order='C', device='cpu', writable=False)] | None, insert_vertex_labels: Annotated[NDArray[numpy.int8], dict(shape=(None,), order='C', device='cpu', writable=False)] | None, delete_vertices: Annotated[NDArray[numpy.int64], dict(shape=(None,), order='C', device='cpu', writable=False)] | None) -> None: ...

    @property
    def num_insertions(self) -> int: ...

    @property
    def num_deletions(self) -> int: ...

    @property
    def num_weights(self) -> int: ...

class EdgeBatchI32U:
    """A batch of edge changes over arrays (private)."""

    def __init__(self, insert_src: Annotated[NDArray[numpy.int32], dict(shape=(None,), order='C', device='cpu', writable=False)], insert_dst: Annotated[NDArray[numpy.int32], dict(shape=(None,), order='C', device='cpu', writable=False)], insert_weights: Annotated[NDArray[numpy.int32], dict(shape=(None,), order='C', device='cpu', writable=False)] | None, delete_src: Annotated[NDArray[numpy.int32], dict(shape=(None,), order='C', device='cpu', writable=False)], delete_dst: Annotated[NDArray[numpy.int32], dict(shape=(None,), order='C', device='cpu', writable=False)], num_weights: int, insert_vertices: Annotated[NDArray[numpy.int32], dict(shape=(None,), order='C', device='cpu', writable=False)] | None, insert_vertex_labels: Annotated[NDArray[numpy.int8], dict(shape=(None,), order='C', device='cpu', writable=False)] | None, delete_vertices: Annotated[NDArray[numpy.int32], dict(shape=(None,), order='C', device='cpu', writable=False)] | None) -> None: ...

    @property
    def num_insertions(self) -> int: ...

    @property
    def num_deletions(self) -> int: ...

    @property
    def num_weights(self) -> int: ...

class SsspOptions:
    """sssp::options."""

    def __init__(self) -> None: ...

    @property
    def delta(self) -> int: ...

    @delta.setter
    def delta(self, arg: int, /) -> None: ...

    @property
    def objective(self) -> int: ...

    @objective.setter
    def objective(self, arg: int, /) -> None: ...

    @property
    def cuda_engine(self) -> Engine: ...

    @cuda_engine.setter
    def cuda_engine(self, arg: Engine, /) -> None: ...

    @property
    def validate_inputs(self) -> bool: ...

    @validate_inputs.setter
    def validate_inputs(self, arg: bool, /) -> None: ...

class SsspStats:
    """sssp::stats."""

    @property
    def affected(self) -> int: ...

    @property
    def iterations(self) -> int: ...

    @property
    def frontier_visits(self) -> int: ...

    @property
    def fallback_used(self) -> bool: ...

    @property
    def converged(self) -> bool: ...

    @property
    def engine_used(self) -> Engine: ...

    @property
    def batch(self) -> ApplySummary: ...

    @property
    def invalidated(self) -> int: ...

    @property
    def epochs(self) -> int: ...

    @property
    def pushes(self) -> int: ...

    @property
    def packed_parents(self) -> bool: ...

class SsspResultI32:
    """An sssp::result (private)."""

    @property
    def source(self) -> int: ...

    def distances(self) -> Annotated[Any, dict(dtype='int64', shape=(None,), writable=False)]: ...

    def parents(self) -> Annotated[Any, dict(dtype='int32', shape=(None,), writable=False)]: ...

    @property
    def generation(self) -> int:
        """The number of updates of this result (dyng.Array's staleness check)."""

    @property
    def options(self) -> SsspOptions: ...

    def set_options(self, options: SsspOptions) -> None: ...

    @property
    def graph_version(self) -> int: ...

    @property
    def space(self) -> MemorySpace: ...

    def clone(self, resources: Resources) -> SsspResultI32: ...

class SsspResultI64:
    """An sssp::result (private)."""

    @property
    def source(self) -> int: ...

    def distances(self) -> Annotated[Any, dict(dtype='int64', shape=(None,), writable=False)]: ...

    def parents(self) -> Annotated[Any, dict(dtype='int64', shape=(None,), writable=False)]: ...

    @property
    def generation(self) -> int:
        """The number of updates of this result (dyng.Array's staleness check)."""

    @property
    def options(self) -> SsspOptions: ...

    def set_options(self, options: SsspOptions) -> None: ...

    @property
    def graph_version(self) -> int: ...

    @property
    def space(self) -> MemorySpace: ...

    def clone(self, resources: Resources) -> SsspResultI64: ...

@overload
def sssp_compute(resources: Resources, graph: GraphI32I32I32, source: int, options: SsspOptions) -> SsspResultI32: ...

@overload
def sssp_compute(resources: Resources, graph: GraphI32I64I32, source: int, options: SsspOptions) -> SsspResultI32: ...

@overload
def sssp_compute(resources: Resources, graph: GraphI64I64I32, source: int, options: SsspOptions) -> SsspResultI64: ...

@overload
def sssp_update(resources: Resources, graph: GraphI32I32I32, batch: EdgeBatchI32I32, result: SsspResultI32) -> SsspStats: ...

@overload
def sssp_update(resources: Resources, graph: GraphI32I64I32, batch: EdgeBatchI32I32, result: SsspResultI32) -> SsspStats: ...

@overload
def sssp_update(resources: Resources, graph: GraphI64I64I32, batch: EdgeBatchI64I32, result: SsspResultI64) -> SsspStats: ...

@overload
def sssp_from_arrays(resources: Resources, graph: GraphI32I32I32, source: int, distances: Annotated[NDArray[numpy.int64], dict(shape=(None,), order='C', device='cpu', writable=False)], parents: Annotated[NDArray[numpy.int32], dict(shape=(None,), order='C', device='cpu', writable=False)], canonicalize: bool, options: SsspOptions) -> SsspResultI32: ...

@overload
def sssp_from_arrays(resources: Resources, graph: GraphI32I64I32, source: int, distances: Annotated[NDArray[numpy.int64], dict(shape=(None,), order='C', device='cpu', writable=False)], parents: Annotated[NDArray[numpy.int32], dict(shape=(None,), order='C', device='cpu', writable=False)], canonicalize: bool, options: SsspOptions) -> SsspResultI32: ...

@overload
def sssp_from_arrays(resources: Resources, graph: GraphI64I64I32, source: int, distances: Annotated[NDArray[numpy.int64], dict(shape=(None,), order='C', device='cpu', writable=False)], parents: Annotated[NDArray[numpy.int64], dict(shape=(None,), order='C', device='cpu', writable=False)], canonicalize: bool, options: SsspOptions) -> SsspResultI64: ...

class SearchMethod(enum.Enum):
    """cycle_count::search_method."""

    johnson = 0

class CycleMode(enum.Enum):
    """cycle_count::cycle_mode."""

    simple = 0

class CudaScheduler(enum.Enum):
    """cycle_count::cuda_scheduler."""

    work_queue = 0

    naive = 1

class CudaWorkItems(enum.Enum):
    """cycle_count::cuda_work_items."""

    automatic = 0

    roots = 1

    edges = 2

    two_hop = 3

class CycleCountOptions:
    """cycle_count::options."""

    def __init__(self) -> None: ...

    @property
    def max_length(self) -> int: ...

    @max_length.setter
    def max_length(self, arg: int, /) -> None: ...

    @property
    def method(self) -> SearchMethod: ...

    @method.setter
    def method(self, arg: SearchMethod, /) -> None: ...

    @property
    def mode(self) -> CycleMode: ...

    @mode.setter
    def mode(self, arg: CycleMode, /) -> None: ...

    @property
    def cuda_engine(self) -> Engine: ...

    @cuda_engine.setter
    def cuda_engine(self, arg: Engine, /) -> None: ...

    @property
    def scheduler(self) -> CudaScheduler: ...

    @scheduler.setter
    def scheduler(self, arg: CudaScheduler, /) -> None: ...

    @property
    def work_items(self) -> CudaWorkItems: ...

    @work_items.setter
    def work_items(self, arg: CudaWorkItems, /) -> None: ...

class CycleCountStats:
    """cycle_count::stats."""

    @property
    def affected(self) -> int: ...

    @property
    def iterations(self) -> int: ...

    @property
    def frontier_visits(self) -> int: ...

    @property
    def fallback_used(self) -> bool: ...

    @property
    def converged(self) -> bool: ...

    @property
    def engine_used(self) -> Engine: ...

    @property
    def batch(self) -> ApplySummary: ...

    @property
    def deletions(self) -> int: ...

    @property
    def insertions(self) -> int: ...

    @property
    def cycles_removed(self) -> int: ...

    @property
    def cycles_added(self) -> int: ...

class CycleCountResult:
    """A cycle_count::result (private)."""

    def counts(self) -> Annotated[Any, dict(dtype='uint64', shape=(None,), writable=False)]: ...

    def count(self, length: int) -> int: ...

    @property
    def total(self) -> int: ...

    @property
    def bound(self) -> int: ...

    @property
    def generation(self) -> int:
        """The number of updates of this result (dyng.Array's staleness check)."""

    @property
    def options(self) -> CycleCountOptions: ...

    def set_options(self, options: CycleCountOptions) -> None: ...

    @property
    def graph_version(self) -> int: ...

    @property
    def space(self) -> MemorySpace: ...

    def clone(self, resources: Resources) -> CycleCountResult: ...

@overload
def cycle_count_compute(resources: Resources, graph: GraphI32I32I32, options: CycleCountOptions) -> CycleCountResult: ...

@overload
def cycle_count_compute(resources: Resources, graph: GraphI32I64I32, options: CycleCountOptions) -> CycleCountResult: ...

@overload
def cycle_count_compute(resources: Resources, graph: GraphI32I32U, options: CycleCountOptions) -> CycleCountResult: ...

@overload
def cycle_count_compute(resources: Resources, graph: GraphI32I64U, options: CycleCountOptions) -> CycleCountResult: ...

@overload
def cycle_count_update(resources: Resources, graph: GraphI32I32I32, batch: EdgeBatchI32I32, result: CycleCountResult) -> CycleCountStats: ...

@overload
def cycle_count_update(resources: Resources, graph: GraphI32I64I32, batch: EdgeBatchI32I32, result: CycleCountResult) -> CycleCountStats: ...

@overload
def cycle_count_update(resources: Resources, graph: GraphI32I32U, batch: EdgeBatchI32U, result: CycleCountResult) -> CycleCountStats: ...

@overload
def cycle_count_update(resources: Resources, graph: GraphI32I64U, batch: EdgeBatchI32U, result: CycleCountResult) -> CycleCountStats: ...

@overload
def update(resources: Resources, graph: GraphI32I32I32, batch: EdgeBatchI32I32, results: list) -> list: ...

@overload
def update(resources: Resources, graph: GraphI32I64I32, batch: EdgeBatchI32I32, results: list) -> list: ...

@overload
def update(resources: Resources, graph: GraphI64I64I32, batch: EdgeBatchI64I32, results: list) -> list: ...

@overload
def update(resources: Resources, graph: GraphI32I32U, batch: EdgeBatchI32U, results: list) -> list: ...

@overload
def update(resources: Resources, graph: GraphI32I64U, batch: EdgeBatchI32U, results: list) -> list:
    """Apply one batch and update every result (a list of result objects)."""

class VertexIds(enum.Enum):
    """io::vertex_ids."""

    compact = 0

    as_is = 1

class DuplicateEdges(enum.Enum):
    """io::duplicate_edges."""

    merge = 0

    keep = 1

class MatrixMarketWeights(enum.Enum):
    """io::matrix_market_weights."""

    automatic = 0

    none = 1

    from_file = 2

    random = 3

class EdgeListOptions:
    """io::edge_list_options."""

    def __init__(self) -> None: ...

    @property
    def num_weights(self) -> int: ...

    @num_weights.setter
    def num_weights(self, arg: int, /) -> None: ...

    @property
    def ids(self) -> VertexIds: ...

    @ids.setter
    def ids(self, arg: VertexIds, /) -> None: ...

    @property
    def index_base(self) -> int: ...

    @index_base.setter
    def index_base(self, arg: int, /) -> None: ...

    @property
    def symmetrize(self) -> bool: ...

    @symmetrize.setter
    def symmetrize(self, arg: bool, /) -> None: ...

    @property
    def drop_self_loops(self) -> bool: ...

    @drop_self_loops.setter
    def drop_self_loops(self, arg: bool, /) -> None: ...

    @property
    def duplicates(self) -> DuplicateEdges: ...

    @duplicates.setter
    def duplicates(self, arg: DuplicateEdges, /) -> None: ...

    @property
    def threads(self) -> int: ...

    @threads.setter
    def threads(self, arg: int, /) -> None: ...

class MatrixMarketOptions:
    """io::matrix_market_options."""

    def __init__(self) -> None: ...

    @property
    def weights(self) -> MatrixMarketWeights: ...

    @weights.setter
    def weights(self, arg: MatrixMarketWeights, /) -> None: ...

    @property
    def drop_self_loops(self) -> bool: ...

    @drop_self_loops.setter
    def drop_self_loops(self, arg: bool, /) -> None: ...

    @property
    def sort_and_dedupe(self) -> bool: ...

    @sort_and_dedupe.setter
    def sort_and_dedupe(self, arg: bool, /) -> None: ...

    def set_random(self, num_weights: int, min: int, max: int, seed: int) -> None: ...

def read_edge_list_i32_i32(path: str, options: EdgeListOptions) -> tuple: ...

def write_edge_list_i32_i32(path: str, num_vertices: int, src: Annotated[NDArray[numpy.int32], dict(shape=(None,), order='C', device='cpu', writable=False)], dst: Annotated[NDArray[numpy.int32], dict(shape=(None,), order='C', device='cpu', writable=False)], weights: Annotated[NDArray[numpy.int32], dict(shape=(None,), order='C', device='cpu', writable=False)] | None, num_weights: int) -> None: ...

def read_edge_list_i64_i32(path: str, options: EdgeListOptions) -> tuple: ...

def write_edge_list_i64_i32(path: str, num_vertices: int, src: Annotated[NDArray[numpy.int64], dict(shape=(None,), order='C', device='cpu', writable=False)], dst: Annotated[NDArray[numpy.int64], dict(shape=(None,), order='C', device='cpu', writable=False)], weights: Annotated[NDArray[numpy.int32], dict(shape=(None,), order='C', device='cpu', writable=False)] | None, num_weights: int) -> None: ...

def read_edge_list_i32_u(path: str, options: EdgeListOptions) -> tuple: ...

def write_edge_list_i32_u(path: str, num_vertices: int, src: Annotated[NDArray[numpy.int32], dict(shape=(None,), order='C', device='cpu', writable=False)], dst: Annotated[NDArray[numpy.int32], dict(shape=(None,), order='C', device='cpu', writable=False)], weights: Annotated[NDArray[numpy.int32], dict(shape=(None,), order='C', device='cpu', writable=False)] | None, num_weights: int) -> None: ...

def read_edge_list_i64_u(path: str, options: EdgeListOptions) -> tuple: ...

def write_edge_list_i64_u(path: str, num_vertices: int, src: Annotated[NDArray[numpy.int64], dict(shape=(None,), order='C', device='cpu', writable=False)], dst: Annotated[NDArray[numpy.int64], dict(shape=(None,), order='C', device='cpu', writable=False)], weights: Annotated[NDArray[numpy.int32], dict(shape=(None,), order='C', device='cpu', writable=False)] | None, num_weights: int) -> None: ...

def read_matrix_market_i32_i32(path: str, options: MatrixMarketOptions) -> tuple: ...

def write_matrix_market_i32_i32(path: str, num_vertices: int, src: Annotated[NDArray[numpy.int32], dict(shape=(None,), order='C', device='cpu', writable=False)], dst: Annotated[NDArray[numpy.int32], dict(shape=(None,), order='C', device='cpu', writable=False)], weights: Annotated[NDArray[numpy.int32], dict(shape=(None,), order='C', device='cpu', writable=False)] | None, num_weights: int, weight_column: int) -> None: ...

def read_legacy_batch_i32_i32(insert_path: str, delete_path: str, num_weights: int, num_vertices: int, mosp_lenient: bool) -> tuple: ...

def write_legacy_batch_i32_i32(insert_path: str, delete_path: str, batch: EdgeBatchI32I32) -> None: ...

def read_parents_i32(path: str, num_vertices: int) -> Annotated[NDArray[numpy.int32], dict(shape=(None,))]: ...

@overload
def write_parents(path: str, parents: Annotated[NDArray[numpy.int32], dict(shape=(None,), order='C', device='cpu', writable=False)]) -> None: ...

@overload
def write_parents(path: str, parents: Annotated[NDArray[numpy.int64], dict(shape=(None,), order='C', device='cpu', writable=False)]) -> None: ...

def read_matrix_market_i64_i32(path: str, options: MatrixMarketOptions) -> tuple: ...

def write_matrix_market_i64_i32(path: str, num_vertices: int, src: Annotated[NDArray[numpy.int64], dict(shape=(None,), order='C', device='cpu', writable=False)], dst: Annotated[NDArray[numpy.int64], dict(shape=(None,), order='C', device='cpu', writable=False)], weights: Annotated[NDArray[numpy.int32], dict(shape=(None,), order='C', device='cpu', writable=False)] | None, num_weights: int, weight_column: int) -> None: ...

def read_legacy_batch_i64_i32(insert_path: str, delete_path: str, num_weights: int, num_vertices: int, mosp_lenient: bool) -> tuple: ...

def write_legacy_batch_i64_i32(insert_path: str, delete_path: str, batch: EdgeBatchI64I32) -> None: ...

def read_parents_i64(path: str, num_vertices: int) -> Annotated[NDArray[numpy.int64], dict(shape=(None,))]: ...

def read_csr_triplet_i32_i32_i32(prefix: str, num_weights: int) -> tuple: ...

@overload
def write_csr_triplet(prefix: str, row_ptr: Annotated[NDArray[numpy.int32], dict(shape=(None,), order='C', device='cpu', writable=False)], col_ind: Annotated[NDArray[numpy.int32], dict(shape=(None,), order='C', device='cpu', writable=False)], weights: Annotated[NDArray[numpy.int32], dict(shape=(None,), order='C', device='cpu', writable=False)], num_weights: int) -> None: ...

@overload
def write_csr_triplet(prefix: str, row_ptr: Annotated[NDArray[numpy.int64], dict(shape=(None,), order='C', device='cpu', writable=False)], col_ind: Annotated[NDArray[numpy.int32], dict(shape=(None,), order='C', device='cpu', writable=False)], weights: Annotated[NDArray[numpy.int32], dict(shape=(None,), order='C', device='cpu', writable=False)], num_weights: int) -> None: ...

@overload
def write_csr_triplet(prefix: str, row_ptr: Annotated[NDArray[numpy.int64], dict(shape=(None,), order='C', device='cpu', writable=False)], col_ind: Annotated[NDArray[numpy.int64], dict(shape=(None,), order='C', device='cpu', writable=False)], weights: Annotated[NDArray[numpy.int32], dict(shape=(None,), order='C', device='cpu', writable=False)], num_weights: int) -> None: ...

def read_csr_triplet_i32_i64_i32(prefix: str, num_weights: int) -> tuple: ...

def read_csr_triplet_i64_i64_i32(prefix: str, num_weights: int) -> tuple: ...

def read_distances(path: str, num_vertices: int) -> Annotated[NDArray[numpy.int64], dict(shape=(None,))]: ...

def write_distances(path: str, distances: Annotated[NDArray[numpy.int64], dict(shape=(None,), order='C', device='cpu', writable=False)]) -> None: ...

def histogram_csv(counts: Annotated[NDArray[numpy.uint64], dict(shape=(None,), order='C', device='cpu', writable=False)], include_total: bool) -> str:
    """The cycle histogram as CycleEnumeration-GPU's CSV text."""

class MospChangeMode(enum.Enum):
    """generators::legacy::mosp_change_mode."""

    uniform = 0

    targeted = 1

    reweight = 2

    increase = 3

class MospChangeOptions:
    """generators::legacy::mosp_change_options."""

    def __init__(self) -> None: ...

    @property
    def num_changes(self) -> int: ...

    @num_changes.setter
    def num_changes(self, arg: int, /) -> None: ...

    @property
    def insertion_percentage(self) -> float: ...

    @insertion_percentage.setter
    def insertion_percentage(self, arg: float, /) -> None: ...

    @property
    def mode(self) -> MospChangeMode: ...

    @mode.setter
    def mode(self, arg: MospChangeMode, /) -> None: ...

    @property
    def weight_min(self) -> int: ...

    @weight_min.setter
    def weight_min(self, arg: int, /) -> None: ...

    @property
    def weight_max(self) -> int: ...

    @weight_max.setter
    def weight_max(self, arg: int, /) -> None: ...

    @property
    def seed(self) -> int: ...

    @seed.setter
    def seed(self, arg: int, /) -> None: ...

    @property
    def local_hops(self) -> int: ...

    @local_hops.setter
    def local_hops(self, arg: int, /) -> None: ...

    @property
    def safe_deletions(self) -> bool: ...

    @safe_deletions.setter
    def safe_deletions(self, arg: bool, /) -> None: ...

    @property
    def source(self) -> int: ...

    @source.setter
    def source(self, arg: int, /) -> None: ...

class MospChangeReport:
    """generators::legacy::mosp_change_report."""

    @property
    def inserts(self) -> int: ...

    @property
    def reweights(self) -> int: ...

    @property
    def deletes(self) -> int: ...

    @property
    def requested_deletes(self) -> int: ...

    @property
    def safe_rounds(self) -> int: ...

    @property
    def safe(self) -> bool: ...

    @property
    def centre(self) -> int: ...

    @property
    def local_hops(self) -> int: ...

    @property
    def region(self) -> int: ...

    def summary(self) -> str: ...

class CycleEnumBatchOptions:
    """generators::legacy::cycle_enum_batch_options."""

    def __init__(self) -> None: ...

    @property
    def num_deletions(self) -> int: ...

    @num_deletions.setter
    def num_deletions(self, arg: int, /) -> None: ...

    @property
    def num_insertions(self) -> int: ...

    @num_insertions.setter
    def num_insertions(self, arg: int, /) -> None: ...

    @property
    def seed(self) -> int: ...

    @seed.setter
    def seed(self, arg: int, /) -> None: ...

    @property
    def locality_window(self) -> int: ...

    @locality_window.setter
    def locality_window(self, arg: int, /) -> None: ...

def legacy_mosp_weights(count: int, min: int, max: int, seed: int) -> Annotated[NDArray[numpy.int32], dict(shape=(None,))]:
    """
    MOSP's weight stream: `count` draws in [min, max] from std::mt19937(seed).
    """

@overload
def mosp_changes(graph: GraphI32I32I32, options: MospChangeOptions) -> tuple: ...

@overload
def mosp_changes(graph: GraphI32I64I32, options: MospChangeOptions) -> tuple: ...

@overload
def mosp_changes(graph: GraphI64I64I32, options: MospChangeOptions) -> tuple: ...

@overload
def cycle_enum_batch(graph: GraphI32I32I32, options: CycleEnumBatchOptions) -> tuple: ...

@overload
def cycle_enum_batch(graph: GraphI32I64I32, options: CycleEnumBatchOptions) -> tuple: ...

@overload
def cycle_enum_batch(graph: GraphI64I64I32, options: CycleEnumBatchOptions) -> tuple: ...

@overload
def cycle_enum_batch(graph: GraphI32I32U, options: CycleEnumBatchOptions) -> tuple: ...

@overload
def cycle_enum_batch(graph: GraphI32I64U, options: CycleEnumBatchOptions) -> tuple: ...

def algorithms() -> list:
    """The registry: one dict per built algorithm."""

def citation(what: str) -> str:
    """BibTeX for dynG, an algorithm name or a references.bib key."""

def citation_keys(what: str) -> list[str]:
    """The references.bib keys citation(what) returns."""

class SsspTreeCheck:
    """testing::sssp_tree_check."""

    @property
    def distance_mismatches(self) -> int: ...

    @property
    def inconsistent_parents(self) -> int: ...

    @property
    def non_canonical_parents(self) -> int: ...

    @property
    def parent_mismatches(self) -> int: ...

    @property
    def require_canonical(self) -> bool: ...

    def ok(self) -> bool: ...

    def summary(self) -> str: ...

@overload
def testing_dijkstra(graph: GraphI32I32I32, source: int, objective: int) -> tuple: ...

@overload
def testing_dijkstra(graph: GraphI32I64I32, source: int, objective: int) -> tuple: ...

@overload
def testing_dijkstra(graph: GraphI64I64I32, source: int, objective: int) -> tuple: ...

@overload
def testing_check_sssp_tree(graph: GraphI32I32I32, result: SsspResultI32, require_canonical: bool) -> SsspTreeCheck: ...

@overload
def testing_check_sssp_tree(graph: GraphI32I64I32, result: SsspResultI32, require_canonical: bool) -> SsspTreeCheck: ...

@overload
def testing_check_sssp_tree(graph: GraphI64I64I32, result: SsspResultI64, require_canonical: bool) -> SsspTreeCheck: ...

@overload
def testing_simple_cycles(graph: GraphI32I32I32, max_length: int, brute_force: bool) -> Annotated[NDArray[numpy.uint64], dict(shape=(None,))]: ...

@overload
def testing_simple_cycles(graph: GraphI32I64I32, max_length: int, brute_force: bool) -> Annotated[NDArray[numpy.uint64], dict(shape=(None,))]: ...

@overload
def testing_simple_cycles(graph: GraphI64I64I32, max_length: int, brute_force: bool) -> Annotated[NDArray[numpy.uint64], dict(shape=(None,))]: ...

@overload
def testing_simple_cycles(graph: GraphI32I32U, max_length: int, brute_force: bool) -> Annotated[NDArray[numpy.uint64], dict(shape=(None,))]: ...

@overload
def testing_simple_cycles(graph: GraphI32I64U, max_length: int, brute_force: bool) -> Annotated[NDArray[numpy.uint64], dict(shape=(None,))]: ...
