// SPDX-FileCopyrightText: 2026 The dynG Authors
// SPDX-License-Identifier: Apache-2.0
/**
 * @file algorithm_template.cpp
 * @brief algorithm_template: argument validation, the result, compute() and update() through the
 *        framework's enactors, the hooks of the problem, and the explicit instantiations
 *        (generated by scripts/new_algorithm.py; PLAN Section 4.8, file 4).
 */
#include "algorithms/algorithm_template/problem.hpp"
#include "core/budget_counters.hpp"
#include "framework/composition.hpp"
#include "framework/context.hpp"
#include "framework/enactor.hpp"
#include "framework/views.hpp"
#include "graph/graph_impl.hpp"
#include "graph/instantiate.hpp"

#include <dyng/algorithm_template.hpp>
#include <dyng/core/backend.hpp>
#include <dyng/core/error.hpp>
#include <dyng/core/memory.hpp>
#include <dyng/update.hpp>

#include <algorithm>
#include <cstddef>
#include <cstdint>
#include <memory>
#include <string>
#include <utility>

namespace dyng::detail {

namespace {

/// The backends of the manifest that this algorithm implements.
bool implemented(backend b) {
  return b == backend::sequential
         //@@ openmp
         || b == backend::openmp
      //@@ end
      ;
}

/// Throws not_supported_error unless the backend of `res` is implemented and built.
void expect_backend(const resources& res, const char* function) {
  const backend b = res.get_backend();
  if (!implemented(b) || !backend_available(b)) {
    throw not_supported_error(concat_message("dyng: ", function, ": the ", to_string(b),
                                             " backend is not available for "
                                             "algorithm_template (available: sequential"
                                             //@@ openmp
                                             ,
                                             backend_available(backend::openmp) ? ", openmp" : ""
                                             //@@ end
                                             ,
                                             ")"));
  }
}

/// Throws stale_result_error for a poisoned result.
void expect_not_poisoned(const algorithm_template_state& st, const char* function) {
  if (st.poisoned) {
    throw stale_result_error(concat_message(
        "dyng: ", function, ": a failed update left this result unusable; recompute it"));
  }
}

/// The state of a result, or invalid_argument_error for a moved-from one.
template <typename state_t>
state_t& checked(state_t* st, const char* function) {
  DYNG_EXPECTS(st != nullptr, function, ": the result was moved from");
  expect_not_poisoned(*st, function);
  return *st;
}

}  // namespace

algorithm_template_state& algorithm_template_access::state(algorithm_template::result& r) {
  DYNG_EXPECTS(r.impl_ != nullptr, "algorithm_template: the result was moved from");
  return *r.impl_;
}

const algorithm_template_state& algorithm_template_access::state(
    const algorithm_template::result& r) {
  DYNG_EXPECTS(r.impl_ != nullptr, "algorithm_template: the result was moved from");
  return *r.impl_;
}

algorithm_template::result algorithm_template_access::make(
    std::unique_ptr<algorithm_template_state> st) {
  return algorithm_template::result(std::move(st));
}

void algorithm_template_workspace::reserve(std::size_t n) {
  //@@ fixed_point
  if (queue.capacity() < n || before.capacity() < n) {
    note_reservation();  // invariant I9: a reserving run (core/budget_counters.hpp)
    queue.reserve(n);
    before.reserve(n);
  }
  //@@ end
  //@@ aggregate_delta
  (void)n;
  //@@ end
}

std::size_t algorithm_template_workspace::bytes() const noexcept {
  //@@ fixed_point
  return (queue.capacity() + before.capacity()) * sizeof(std::int64_t);
  //@@ end
  //@@ aggregate_delta
  return unused.capacity() * sizeof(std::int64_t);
  //@@ end
}

// ------------------------------------------------------------------------------------------------
// The problem
// ------------------------------------------------------------------------------------------------

template <typename vertex_t, typename edge_t, typename weight_t>
void algorithm_template_problem<vertex_t, edge_t, weight_t>::begin_update(
    framework::context& ctx, old_graph g, const requested& /*batch*/) {
  expect_backend(ctx.res(), "algorithm_template::update");
  graph_access::expect_placement(ctx.res(), g.get(), "algorithm_template::update");
  expect_not_poisoned(*state_, "algorithm_template::update");
  framework::expect_current_result("algorithm_template::update", state_->version,
                                   state_->graph_state, g.get());
}

template <typename vertex_t, typename edge_t, typename weight_t>
void algorithm_template_problem<vertex_t, edge_t, weight_t>::resume(framework::context& ctx,
                                                                    new_graph g,
                                                                    const applied& /*applied*/) {
  const auto n = static_cast<std::size_t>(g->num_vertices());
  ws_.emplace(ctx.lease_workspace<algorithm_template_workspace>());
  (*ws_)->reserve(n);
  //@@ fixed_point
  if (state_->levels.capacity() < n) {
    note_reservation();  // the result grows with the graph (invariant I9)
  }
  state_->levels.resize(n, -1);  // new vertices start unreached
  (*ws_)->before.assign(state_->levels.begin(), state_->levels.end());
  //@@ end
  //@@ aggregate_delta
  before_ = state_->count;
  //@@ end
}

template <typename vertex_t, typename edge_t, typename weight_t>
void algorithm_template_problem<vertex_t, edge_t, weight_t>::end_update(
    framework::context& /*ctx*/, new_graph g, const stats_type& /*stats*/) {
  framework::stamp_result(state_->version, state_->graph_state, g.get());
  ws_.reset();
}

template <typename vertex_t, typename edge_t, typename weight_t>
void algorithm_template_problem<vertex_t, edge_t, weight_t>::solve(framework::context& ctx,
                                                                   const container_type& g) {
  if (!ws_) {
    ws_.emplace(ctx.lease_workspace<algorithm_template_workspace>());
    (*ws_)->reserve(static_cast<std::size_t>(g.num_vertices()));
  }
  const auto out = graph_access::out_view(g);
  //@@ fixed_point
  //@@ openmp
  if (ctx.res().get_backend() == backend::openmp) {
    algorithm_template_openmp(ctx.res(), out, state_->opt.source, state_->levels, ws_->get());
    return;
  }
  //@@ end
  algorithm_template_sequential(out, state_->opt.source, state_->levels, ws_->get());
  //@@ end
  //@@ aggregate_delta
  //@@ openmp
  if (ctx.res().get_backend() == backend::openmp) {
    state_->count = algorithm_template_openmp(ctx.res(), out);
    return;
  }
  //@@ end
  state_->count = algorithm_template_sequential(out);
  //@@ end
}

//@@ fixed_point
template <typename vertex_t, typename edge_t, typename weight_t>
void algorithm_template_problem<vertex_t, edge_t, weight_t>::loop(framework::context& ctx,
                                                                  new_graph g,
                                                                  frontier_type& /*in*/,
                                                                  frontier_type& /*out*/) {
  // TODO(algorithm_template): propagate from the frontier only (incremental Step 2).
  solve(ctx, g.get());
}

template <typename vertex_t, typename edge_t, typename weight_t>
void algorithm_template_problem<vertex_t, edge_t, weight_t>::seed_static(
    framework::context& /*ctx*/, new_graph /*g*/, frontier_type& /*f*/) {}
//@@ end
//@@ aggregate_delta
template <typename vertex_t, typename edge_t, typename weight_t>
void algorithm_template_problem<vertex_t, edge_t, weight_t>::count(framework::context& /*ctx*/,
                                                                   old_graph /*g*/,
                                                                   frontier_type& /*f*/,
                                                                   framework::sign /*s*/,
                                                                   ownership_type /*rule*/) {
  // TODO(algorithm_template): subtract on G_t what the deleted edges destroy.
}

template <typename vertex_t, typename edge_t, typename weight_t>
void algorithm_template_problem<vertex_t, edge_t, weight_t>::count(framework::context& ctx,
                                                                   new_graph g,
                                                                   frontier_type& /*f*/,
                                                                   framework::sign /*s*/,
                                                                   ownership_type /*rule*/) {
  // TODO(algorithm_template): add on G_{t+1} what the inserted edges create.
  solve(ctx, g.get());
}
//@@ end

template <typename vertex_t, typename edge_t, typename weight_t>
void algorithm_template_problem<vertex_t, edge_t, weight_t>::finalize(framework::context& /*ctx*/,
                                                                      stats_type& stats) {
  if (computing_) {
    return;
  }
  //@@ fixed_point
  const std::vector<std::int64_t>& before = (*ws_)->before;
  std::int64_t changed = 0;
  for (std::size_t v = 0; v < state_->levels.size(); ++v) {
    changed += (v >= before.size() || before[v] != state_->levels[v]) ? 1 : 0;
  }
  stats.affected = changed;
  //@@ end
  //@@ aggregate_delta
  stats.affected = before_ != state_->count ? 1 : 0;
  //@@ end
  stats.fallback_used = true;  // the placeholder recomputed (PLAN Section 4.8, "start green")
}

template <typename vertex_t, typename edge_t, typename weight_t>
void algorithm_template_problem<vertex_t, edge_t, weight_t>::reset(framework::context& /*ctx*/) {
  computing_ = true;
}

}  // namespace dyng::detail

// ------------------------------------------------------------------------------------------------
// The public functions
// ------------------------------------------------------------------------------------------------

namespace dyng::algorithm_template {

result::result(std::unique_ptr<detail::algorithm_template_state> state) noexcept
    : impl_(std::move(state)) {}
result::result(result&& other) noexcept = default;
result& result::operator=(result&& other) noexcept = default;
result::~result() = default;

//@@ fixed_point
array_view<const std::int64_t> result::levels() const {
  const auto& st = detail::checked(impl_.get(), "algorithm_template::result::levels");
  return host_view(st.levels);
}
//@@ end
//@@ aggregate_delta
std::uint64_t result::count() const {
  return detail::checked(impl_.get(), "algorithm_template::result::count").count;
}
//@@ end

const options& result::get_options() const {
  return detail::checked(impl_.get(), "algorithm_template::result::get_options").opt;
}

void result::set_options(const options& opt) {
  auto& st = detail::checked(impl_.get(), "algorithm_template::result::set_options");
  //@@ fixed_point
  DYNG_EXPECTS(opt.source == st.opt.source,
               "algorithm_template::result::set_options: the source is fixed at compute()");
  //@@ end
  st.opt = opt;
}

std::uint64_t result::graph_version() const noexcept {
  return impl_ == nullptr ? 0 : impl_->version;
}

memory_space result::space() const noexcept {
  return memory_space::host;
}

result result::clone(const resources& res) const {
  const auto& st = detail::checked(impl_.get(), "algorithm_template::result::clone");
  detail::expect_backend(res, "algorithm_template::result::clone");
  return result(std::make_unique<detail::algorithm_template_state>(st));
}

}  // namespace dyng::algorithm_template

namespace dyng::detail {

// compute() and update() behind the public wrappers of the header (which static_assert the
// supported graph types).
template <typename vertex_t, typename edge_t, typename weight_t>
algorithm_template::result algorithm_template_compute(const resources& res,
                                                      const graph<vertex_t, edge_t, weight_t>& g,
                                                      const algorithm_template::options& opt) {
  using problem_t = detail::algorithm_template_problem<vertex_t, edge_t, weight_t>;
  detail::expect_backend(res, "algorithm_template::compute");
  detail::graph_access::expect_placement(res, g, "algorithm_template::compute");
  //@@ aggregate_delta
  // The graph requirements (PLAN Section 5.1): the count searches sorted rows of a simple graph.
  DYNG_EXPECTS(g.properties().order == row_order::sorted &&
                   g.properties().parallel_edges == multi_edges::forbid,
               "algorithm_template::compute: the graph needs sorted rows without parallel edges "
               "(graph_properties::order = row_order::sorted, parallel_edges = "
               "multi_edges::forbid)");
  //@@ end
  //@@ fixed_point
  DYNG_EXPECTS(opt.source >= 0 && opt.source < static_cast<std::int64_t>(g.num_vertices()),
               "algorithm_template::compute: the source ", opt.source,
               " is not a vertex of the graph (", g.num_vertices(), " vertices)");
  //@@ end
  const detail::framework::hook_stages& names = detail::framework::stages_of<problem_t>();
  scoped_stage stage(res, names.compute);
  auto st = std::make_unique<detail::algorithm_template_state>();
  st->opt = opt;
  problem_t p(*st);
  detail::framework::context ctx(res, problem_t::name);
  detail::framework::static_enactor<problem_t> enactor(p);
  (void)enactor.run(ctx, detail::framework::new_view<graph<vertex_t, edge_t, weight_t>>(g));
  detail::framework::stamp_result(st->version, st->graph_state, g);
  return detail::algorithm_template_access::make(std::move(st));
}

template <typename vertex_t, typename edge_t, typename weight_t>
algorithm_template::stats algorithm_template_update(
    const resources& res, graph<vertex_t, edge_t, weight_t>& g,
    const edge_batch_view<vertex_t, weight_t>& batch, algorithm_template::result& r) {
  using problem_t = detail::algorithm_template_problem<vertex_t, edge_t, weight_t>;
  return detail::framework::update_one<problem_t>(res, g, batch, r);
}

template <typename vertex_t, typename edge_t, typename weight_t>
std::unique_ptr<update_participant<vertex_t, edge_t, weight_t>> make_algorithm_template_participant(
    algorithm_template::result& r, algorithm_template::stats& out) {
  using problem_t = algorithm_template_problem<vertex_t, edge_t, weight_t>;
  return framework::make_participant<problem_t>(out, r);
}

// Explicit instantiations (PLAN Section 4.4.3).
#define DYNG_INSTANTIATE_ALGORITHM_TEMPLATE(V, E, W)                                \
  template class algorithm_template_problem<V, E, W>;                               \
  template std::unique_ptr<update_participant<V, E, W>>                             \
  make_algorithm_template_participant<V, E, W>(algorithm_template::result&,         \
                                               algorithm_template::stats&);         \
  template algorithm_template::result algorithm_template_compute<V, E, W>(          \
      const resources&, const graph<V, E, W>&, const algorithm_template::options&); \
  template algorithm_template::stats algorithm_template_update<V, E, W>(            \
      const resources&, graph<V, E, W>&, const edge_batch_view<V, W>&,              \
      algorithm_template::result&);
DYNG_FOR_EACH_GRAPH_TYPE(DYNG_INSTANTIATE_ALGORITHM_TEMPLATE)
#undef DYNG_INSTANTIATE_ALGORITHM_TEMPLATE

}  // namespace dyng::detail
