// SPDX-FileCopyrightText: 2026 The dynG Authors
// SPDX-License-Identifier: Apache-2.0
/**
 * @file openmp.cpp
 * @brief algorithm_template: the OpenMP backend (PLAN Section 4.8, file 7; generated by
 *        scripts/new_algorithm.py).
 *
 * TODO(algorithm_template): the placeholder runs the sequential backend, so the conformance kit's
 * cross-backend check (C3) holds from the first build; write the parallel version and keep C3
 * green.
 */
#include "algorithms/algorithm_template/problem.hpp"
#include "graph/instantiate.hpp"

#include <dyng/core/resources.hpp>
#include <dyng/graph/csr.hpp>

#include <cstdint>
#include <vector>

namespace dyng::detail {

//@@ fixed_point
template <typename vertex_t, typename edge_t, typename weight_t>
void algorithm_template_openmp(const resources& /*res*/,
                               const csr_view<vertex_t, edge_t, weight_t>& out, std::int64_t source,
                               std::vector<std::int64_t>& levels,
                               algorithm_template_workspace& ws) {
  algorithm_template_sequential(out, source, levels, ws);
}

#define DYNG_INSTANTIATE(V, E, W)                                                              \
  template void algorithm_template_openmp<V, E, W>(const resources&, const csr_view<V, E, W>&, \
                                                   std::int64_t, std::vector<std::int64_t>&,   \
                                                   algorithm_template_workspace&);
DYNG_FOR_EACH_GRAPH_TYPE(DYNG_INSTANTIATE)
#undef DYNG_INSTANTIATE
//@@ end
//@@ aggregate_delta
template <typename vertex_t, typename edge_t, typename weight_t>
std::uint64_t algorithm_template_openmp(const resources& /*res*/,
                                        const csr_view<vertex_t, edge_t, weight_t>& out) {
  return algorithm_template_sequential(out);
}

#define DYNG_INSTANTIATE(V, E, W)                                             \
  template std::uint64_t algorithm_template_openmp<V, E, W>(const resources&, \
                                                            const csr_view<V, E, W>&);
DYNG_FOR_EACH_GRAPH_TYPE(DYNG_INSTANTIATE)
#undef DYNG_INSTANTIATE
//@@ end

}  // namespace dyng::detail
