// SPDX-FileCopyrightText: 2026 The dynG Authors
// SPDX-License-Identifier: Apache-2.0
/**
 * @file problem.hpp
 * @brief The algorithm_template problem on the framework (cpp/src/framework): its hooks, its
 *        state and its workspace (generated by scripts/new_algorithm.py).
 *
 * Template card (PLAN Section 4.5.2; docs/developer/framework.md):
 *
//@@ fixed_point
 *     normalize -> prepare -> before_apply -> commit ->
 *     identify_affected -> seed -> { loop until is_converged } -> finalize
 *
 * A fixed-point problem. The placeholder ("start green", PLAN Section 4.8) implements only
 * `loop` (on G_{t+1}: the whole static solve, one call with the internal frontier) and
 * `finalize` (the stats, stats::fallback_used = true), so update() recomputes. To make it
 * incremental: in identify_affected, find the elements the batch invalidates (applied.delta lists
 * the changes the batch requested, not its net change: check an edge against G_{t+1}); in seed,
 * put the elements to re-evaluate on the frontier; in loop, propagate from the frontier only; then
 * set fallback_used only when you really recompute.
//@@ end
//@@ aggregate_delta
 *     normalize -> prepare -> count(-) on G_t -> commit ->
 *     identify_affected -> count(+) on G_{t+1} -> finalize
 *
 * An aggregate-delta problem with the exactly-once rule ownership::min_member (invariant I2). The
 * placeholder ("start green", PLAN Section 4.8) leaves count(-) empty and recounts everything in
 * count(+) (finalize sets stats::fallback_used = true), so update() recomputes. To make it
 * incremental: in count(-), count on G_t what the deleted edges destroy; in count(+), count on
 * G_{t+1} what the inserted edges create, each pattern attributed to its smallest changed edge;
 * in finalize, apply the signed delta.
//@@ end
 *
 * compute() is the static enactor with the same hooks (reset first). Lifecycle members without a
 * stage: begin_update (the checks before anything changes), resume (bind G_{t+1}, grow the
 * result, lease the workspace), end_update (record the graph state), poison.
 */
#pragma once

#include "framework/budgets.hpp"
#include "framework/composition.hpp"
#include "framework/context.hpp"
#include "framework/frontier.hpp"
#include "framework/policies.hpp"
#include "framework/problem.hpp"
#include "framework/views.hpp"
#include "framework/workspace.hpp"

#include <dyng/algorithm_template.hpp>
#include <dyng/core/backend.hpp>
#include <dyng/core/resources.hpp>
#include <dyng/graph/csr.hpp>
#include <dyng/graph/graph.hpp>

#include <cstddef>
#include <cstdint>
#include <optional>
#include <string_view>
#include <vector>

namespace dyng::detail {

/// The state behind an algorithm_template::result.
struct algorithm_template_state {
  algorithm_template::options opt;   ///< the options
                                     //@@ fixed_point
  std::vector<std::int64_t> levels;  ///< the hop level of every vertex, -1 if unreachable
                                     //@@ end
                                     //@@ aggregate_delta
  std::uint64_t count = 0;           ///< the aggregate
                                     //@@ end
  std::uint64_t version = 0;         ///< graph version matched
  std::uint64_t graph_state = 0;     ///< graph state matched (ADR 0006, "Graph identity")
  bool poisoned = false;             ///< a failed update left the result unusable
};

/// Access to the state of a result.
struct algorithm_template_access {
  /// The state of `r`.
  static algorithm_template_state& state(algorithm_template::result& r);
  /// The state of `r`.
  static const algorithm_template_state& state(const algorithm_template::result& r);
  /// A result owning `st`.
  static algorithm_template::result make(std::unique_ptr<algorithm_template_state> st);
};

/// Scratch space of the engines, leased from the workspace pool of the resources handle (ADR 0015).
struct algorithm_template_workspace final : pooled_workspace {
  //@@ fixed_point
  std::vector<std::int64_t> queue;   ///< the search queue
  std::vector<std::int64_t> before;  ///< the levels before the update (the stats)
                                     //@@ end
                                     //@@ aggregate_delta
  std::vector<std::int64_t> unused;  ///< TODO(algorithm_template): the scratch of the counts
                                     //@@ end

  /// Size the arrays for `n` vertices (a reservation when they grow, invariant I9).
  void reserve(std::size_t n);

  /// Bytes of the arrays' capacities.
  [[nodiscard]] std::size_t bytes() const noexcept override;
};

//@@ fixed_point
/**
 * @brief The static solve on the sequential backend: hop levels from `source` (breadth-first).
 * @tparam vertex_t Vertex id type.
 * @tparam edge_t   Edge offset type.
 * @tparam weight_t Weight type.
 * @param[in]     out    The out-edges (host).
 * @param[in]     source The source vertex.
 * @param[out]    levels One level per vertex (resized to the vertex count).
 * @param[in,out] ws     The workspace (reserved for the vertex count).
 */
template <typename vertex_t, typename edge_t, typename weight_t>
void algorithm_template_sequential(const csr_view<vertex_t, edge_t, weight_t>& out,
                                   std::int64_t source, std::vector<std::int64_t>& levels,
                                   algorithm_template_workspace& ws);
//@@ openmp

/**
 * @brief The static solve on the OpenMP backend (as algorithm_template_sequential()).
 * @tparam vertex_t Vertex id type.
 * @tparam edge_t   Edge offset type.
 * @tparam weight_t Weight type.
 * @param[in]     res    The resources (their thread count).
 * @param[in]     out    The out-edges (host).
 * @param[in]     source The source vertex.
 * @param[out]    levels One level per vertex.
 * @param[in,out] ws     The workspace.
 */
template <typename vertex_t, typename edge_t, typename weight_t>
void algorithm_template_openmp(const resources& res,
                               const csr_view<vertex_t, edge_t, weight_t>& out, std::int64_t source,
                               std::vector<std::int64_t>& levels, algorithm_template_workspace& ws);
//@@ end
//@@ end
//@@ aggregate_delta
/**
 * @brief The static count on the sequential backend: reciprocal pairs {u -> v, v -> u}.
 * @tparam vertex_t Vertex id type.
 * @tparam edge_t   Edge offset type.
 * @tparam weight_t Weight type.
 * @param[in] out The out-edges (host, sorted rows).
 * @return The count.
 */
template <typename vertex_t, typename edge_t, typename weight_t>
std::uint64_t algorithm_template_sequential(const csr_view<vertex_t, edge_t, weight_t>& out);
//@@ openmp

/**
 * @brief The static count on the OpenMP backend (as algorithm_template_sequential()).
 * @tparam vertex_t Vertex id type.
 * @tparam edge_t   Edge offset type.
 * @tparam weight_t Weight type.
 * @param[in] res The resources (their thread count).
 * @param[in] out The out-edges (host, sorted rows).
 * @return The count.
 */
template <typename vertex_t, typename edge_t, typename weight_t>
std::uint64_t algorithm_template_openmp(const resources& res,
                                        const csr_view<vertex_t, edge_t, weight_t>& out);
//@@ end
//@@ end

/// The update family of algorithm_template.
//@@ fixed_point
inline constexpr framework::family algorithm_template_family = framework::family::fixed_point;
//@@ end
//@@ aggregate_delta
inline constexpr framework::family algorithm_template_family = framework::family::aggregate_delta;
//@@ end

/**
 * @brief The algorithm_template problem (see the file comment).
 * @tparam vertex_t Vertex id type.
 * @tparam edge_t   Edge offset type.
 * @tparam weight_t Weight type.
 */
template <typename vertex_t, typename edge_t, typename weight_t>
class algorithm_template_problem final
    : public framework::problem_base<algorithm_template_problem<vertex_t, edge_t, weight_t>,
                                     algorithm_template_family> {
 public:
  static constexpr std::string_view name = "algorithm_template";     ///< stages "<name>.<hook>"
  using container_type = graph<vertex_t, edge_t, weight_t>;          ///< the container
  using stats_type = algorithm_template::stats;                      ///< the stats of update()
  using frontier_type = framework::internal_frontier;                ///< frontiers are internal
                                                                     //@@ aggregate_delta
  using ownership_type = framework::ownership::min_member;           ///< the counting rule (I2)
                                                                     //@@ end
  using old_graph = framework::old_view<container_type>;             ///< G_t
  using new_graph = framework::new_view<container_type>;             ///< G_{t+1}
  using requested = framework::requested_batch<vertex_t, weight_t>;  ///< the batch before commit
  using applied = framework::applied_batch<vertex_t>;                ///< what the commit did

  /// The problem of one update of `r`.
  explicit algorithm_template_problem(algorithm_template::result& r)
      : state_(&algorithm_template_access::state(r)), target_(&r) {}
  /// The problem of one compute() filling `st`.
  explicit algorithm_template_problem(algorithm_template_state& st) : state_(&st) {}

  // ---- lifecycle (no stage) ----

  /// The result this problem updates (nullptr for compute()).
  [[nodiscard]] const void* target() const noexcept {
    return target_;
  }
  /// The checks before anything changes: backend, poisoned and stale result.
  void begin_update(framework::context& ctx, old_graph g, const requested& batch);
  /// Bind G_{t+1}: grow the result for new vertices, lease the workspace.
  void resume(framework::context& ctx, new_graph g, const applied& applied);
  /// Record the graph state the result matches; return the workspace.
  void end_update(framework::context& ctx, new_graph g, const stats_type& stats);
  /// Mark the result unusable (a failed algorithm phase).
  void poison() noexcept {
    state_->poisoned = true;
  }
  /// The engines read the out-edges only (the commit need not build the in-edges).
  [[nodiscard]] bool reads_prepared_graph() const noexcept {
    return false;
  }
  /// The budget of the algorithm phase (invariant I9, conformance check C8): nothing allocated
  /// once reserved, no host synchronization.
  [[nodiscard]] framework::budget algorithm_budget(framework::context& /*ctx*/) const noexcept {
    return framework::budget::steady_state(0);
  }

  //@@ fixed_point
  // ---- Step 2 ----

  /// algorithm_template.loop: the placeholder solves G_{t+1} from scratch (one call).
  void loop(framework::context& ctx, new_graph g, frontier_type& in, frontier_type& out);
  //@@ end
  //@@ aggregate_delta
  // ---- the signed recount ----

  /// algorithm_template.count_minus on G_t: the placeholder counts nothing (count(+) recounts).
  void count(framework::context& ctx, old_graph g, frontier_type& f, framework::sign s,
             ownership_type rule);
  /// algorithm_template.count_plus on G_{t+1} (and algorithm_template.count in compute()): the
  /// placeholder recounts everything.
  void count(framework::context& ctx, new_graph g, frontier_type& f, framework::sign s,
             ownership_type rule);
  //@@ end
  /// algorithm_template.finalize: the stats (the placeholder sets fallback_used in update()).
  void finalize(framework::context& ctx, stats_type& stats);

  // ---- compute() ----

  /// algorithm_template.reset: start the static solve.
  void reset(framework::context& ctx);
  //@@ fixed_point
  /// algorithm_template.seed (static): nothing to seed, the loop solves from the source.
  void seed_static(framework::context& ctx, new_graph g, frontier_type& f);
  //@@ end
 private:
  /// The static solve of `g` into the state.
  void solve(framework::context& ctx, const container_type& g);

  algorithm_template_state* state_ = nullptr;
  const algorithm_template::result* target_ = nullptr;
  bool computing_ = false;
  std::optional<workspace_pool::lease<algorithm_template_workspace>> ws_;
  //@@ aggregate_delta
  std::uint64_t before_ = 0;
  //@@ end
};

}  // namespace dyng::detail
