// SPDX-FileCopyrightText: 2026 The dynG Authors
// SPDX-License-Identifier: Apache-2.0
/**
 * @file sequential.cpp
 * @brief algorithm_template: the sequential reference backend, the oracle of the other backends
 *        and of update() (PLAN Section 4.8, file 6; generated by scripts/new_algorithm.py).
 */
#include "algorithms/algorithm_template/problem.hpp"
#include "graph/instantiate.hpp"

#include <dyng/graph/csr.hpp>

#include <algorithm>
#include <cstddef>
#include <cstdint>
#include <vector>

namespace dyng::detail {

//@@ fixed_point
template <typename vertex_t, typename edge_t, typename weight_t>
void algorithm_template_sequential(const csr_view<vertex_t, edge_t, weight_t>& out,
                                   std::int64_t source, std::vector<std::int64_t>& levels,
                                   algorithm_template_workspace& ws) {
  // TODO(algorithm_template): the static solve. The placeholder: breadth-first hop levels.
  const auto n = static_cast<std::size_t>(out.num_vertices());
  levels.assign(n, -1);
  if (source < 0 || static_cast<std::size_t>(source) >= n) {
    return;
  }
  std::vector<std::int64_t>& queue = ws.queue;
  queue.clear();
  levels[static_cast<std::size_t>(source)] = 0;
  queue.push_back(source);
  for (std::size_t head = 0; head < queue.size(); ++head) {
    const auto u = static_cast<std::size_t>(queue[head]);
    for (auto e = out.row_ptr[u]; e < out.row_ptr[u + 1]; ++e) {
      const auto v = static_cast<std::size_t>(out.col_ind[static_cast<std::size_t>(e)]);
      if (levels[v] < 0) {
        levels[v] = levels[u] + 1;
        queue.push_back(static_cast<std::int64_t>(v));
      }
    }
  }
}

#define DYNG_INSTANTIATE(V, E, W)                                                              \
  template void algorithm_template_sequential<V, E, W>(const csr_view<V, E, W>&, std::int64_t, \
                                                       std::vector<std::int64_t>&,             \
                                                       algorithm_template_workspace&);
DYNG_FOR_EACH_GRAPH_TYPE(DYNG_INSTANTIATE)
#undef DYNG_INSTANTIATE
//@@ end
//@@ aggregate_delta
template <typename vertex_t, typename edge_t, typename weight_t>
std::uint64_t algorithm_template_sequential(const csr_view<vertex_t, edge_t, weight_t>& out) {
  // TODO(algorithm_template): the static count. The placeholder: reciprocal pairs u < v.
  const auto n = static_cast<std::size_t>(out.num_vertices());
  std::uint64_t pairs = 0;
  for (std::size_t u = 0; u < n; ++u) {
    for (auto e = out.row_ptr[u]; e < out.row_ptr[u + 1]; ++e) {
      const auto v = static_cast<std::size_t>(out.col_ind[static_cast<std::size_t>(e)]);
      if (u < v) {
        const vertex_t* first = out.col_ind.data() + out.row_ptr[v];
        const vertex_t* last = out.col_ind.data() + out.row_ptr[v + 1];
        pairs += std::binary_search(first, last, static_cast<vertex_t>(u)) ? 1 : 0;
      }
    }
  }
  return pairs;
}

#define DYNG_INSTANTIATE(V, E, W) \
  template std::uint64_t algorithm_template_sequential<V, E, W>(const csr_view<V, E, W>&);
DYNG_FOR_EACH_GRAPH_TYPE(DYNG_INSTANTIATE)
#undef DYNG_INSTANTIATE
//@@ end

}  // namespace dyng::detail
