// SPDX-FileCopyrightText: 2026 The dynG Authors
// SPDX-License-Identifier: Apache-2.0
/**
 * @file dynamic_bfs.hpp
 * @brief dynamic_bfs: compute() and update() (generated by scripts/new_algorithm.py).
 * @ingroup dynamic_bfs
 */
#pragma once

#include <dyng/core/array_view.hpp>
#include <dyng/core/memory.hpp>
#include <dyng/core/resources.hpp>
#include <dyng/core/stats.hpp>
#include <dyng/core/types.hpp>
#include <dyng/graph/apply_summary.hpp>
#include <dyng/graph/edge_batch.hpp>
#include <dyng/graph/graph.hpp>
#include <dyng/update.hpp>

#include <cstdint>
#include <memory>
#include <type_traits>

/**
 * @defgroup dynamic_bfs dynamic_bfs
 * @brief Dynamic breadth-first search levels (tutorial).
 *
 * TEACHING MATERIAL (maturity `tutorial`): a small, complete fixed-point algorithm on the
 * framework, the subject of the tutorial "Your first dynamic algorithm"
 * (docs/tutorials/your_first_dynamic_algorithm.md). It is not a research algorithm and not tuned
 * for speed; use it to learn how a dynG algorithm is built.
 *
 * compute() gives the BFS level (hop distance) of every vertex from options::source in a
 * directed graph, -1 for the vertices the source does not reach (weights are ignored). update()
 * applies a batch of edge insertions and deletions and repairs the levels: the subtrees below
 * the deleted BFS-tree edges are invalidated and re-seeded from their valid in-neighbours, the
 * inserted edges offer shorter levels, and a frontier propagates the improvements until nothing
 * changes. Afterwards the levels equal compute() on the new graph exactly
 * (docs/algorithms/dynamic_bfs.md).
 */

namespace dyng::dynamic_bfs {

/**
 * @brief Options of compute() and update() (an aggregate; fields are only ever appended).
 * @ingroup dynamic_bfs
 */
struct options {
  /// The source vertex. Fixed at compute().
  std::int64_t source = 0;
};

/**
 * @brief Counters of one update() (fields are only ever appended).
 * @ingroup dynamic_bfs
 */
struct stats : update_stats {
  /// Deterministic: what applying the batch did to the graph.
  apply_summary batch;
  /// Deterministic: vertices invalidated (the subtrees below the deleted tree edges).
  std::int64_t invalidated = 0;
  /// Deterministic: passes of the invalidation (the roots, then one per tree level below them;
  /// 0 without deletions).
  std::int64_t invalidation_rounds = 0;
};

}  // namespace dyng::dynamic_bfs

namespace dyng::detail {
struct dynamic_bfs_state;
struct dynamic_bfs_access;
}  // namespace dyng::detail

namespace dyng::dynamic_bfs {

/**
 * @brief The result kept up to date by update() (opaque, move-only).
 *
 * The result owns its levels and its BFS tree (host memory for the sequential and OpenMP
 * backends, device memory for cuda), its options and the graph version it matches.
 * @ingroup dynamic_bfs
 */
class result {
 public:
  /**
   * @brief Move constructor.
   * @param[in,out] other The result to move from; it may only be assigned to or destroyed after.
   */
  result(result&& other) noexcept;

  /**
   * @brief Move assignment.
   * @param[in,out] other The result to move from; it may only be assigned to or destroyed after.
   * @return *this.
   */
  result& operator=(result&& other) noexcept;

  result(const result&) = delete;             ///< not copyable: use clone()
  result& operator=(const result&) = delete;  ///< not copyable: use clone()
  ~result();                                  ///< releases the values

  /**
   * @brief The hop levels.
   * @return One level per vertex (in the memory space(): device memory for a result of the
   *         cuda backend), -1 for the vertices the source does not reach. Valid until the next
   *         update() of this result.
   * @throws invalid_argument_error for a moved-from result.
   * @throws stale_result_error     if a failed update left the result unusable (poisoned).
   */
  [[nodiscard]] array_view<const std::int64_t> levels() const;

  /**
   * @brief The options.
   * @return The options given at compute(), as changed by set_options().
   * @throws invalid_argument_error for a moved-from result.
   * @throws stale_result_error     if a failed update left the result unusable (poisoned).
   */
  [[nodiscard]] const options& get_options() const;

  /**
   * @brief Change the tunables.
   * @param[in] opt The new options; the ones fixed at compute() must stay the same.
   * @throws invalid_argument_error if a fixed option differs, or for a moved-from result.
   * @throws stale_result_error     if a failed update left the result unusable (poisoned).
   */
  void set_options(const options& opt);

  /**
   * @brief The graph version this result matches.
   * @return The version of the graph after the last compute() / update() of this result.
   */
  [[nodiscard]] std::uint64_t graph_version() const noexcept;

  /**
   * @brief The memory space of the levels.
   * @return memory_space::host for the sequential and OpenMP backends, memory_space::device for
   *         cuda.
   */
  [[nodiscard]] memory_space space() const noexcept;

  /**
   * @brief A deep copy for the resources `res`.
   * @param[in] res Execution resources of the copy.
   * @return The copy.
   * @throws invalid_argument_error for a moved-from result.
   * @throws stale_result_error     if a failed update left the result unusable (poisoned).
   * @throws not_supported_error    if the backend of `res` is not available for
   *         dynamic_bfs.
   * @throws out_of_memory_error    if the copy cannot be allocated.
   * @sync
   */
  [[nodiscard]] result clone(const resources& res) const;

 private:
  friend struct detail::dynamic_bfs_access;
  explicit result(std::unique_ptr<detail::dynamic_bfs_state> state) noexcept;

  std::unique_ptr<detail::dynamic_bfs_state> impl_;
};

}  // namespace dyng::dynamic_bfs

namespace dyng::detail {

/**
 * @brief Whether dynamic_bfs is instantiated for graph<vertex_t, edge_t, weight_t> (the
 *        explicit instantiations of dynamic_bfs.cpp: int32_t weights with int32_t ids and
 *        int32_t or int64_t offsets, or int64_t ids and offsets; and unweighted graphs with
 *        int32_t ids and int32_t or int64_t offsets).
 * @tparam vertex_t Vertex id type.
 * @tparam edge_t   Edge offset type.
 * @tparam weight_t Weight type.
 */
template <typename vertex_t, typename edge_t, typename weight_t>
inline constexpr bool dynamic_bfs_supported_v =
    (std::is_same_v<weight_t, std::int32_t> &&
     ((std::is_same_v<vertex_t, std::int32_t> &&
       (std::is_same_v<edge_t, std::int32_t> || std::is_same_v<edge_t, std::int64_t>)) ||
      (std::is_same_v<vertex_t, std::int64_t> && std::is_same_v<edge_t, std::int64_t>))) ||
    (is_unweighted_v<weight_t> && std::is_same_v<vertex_t, std::int32_t> &&
     (std::is_same_v<edge_t, std::int32_t> || std::is_same_v<edge_t, std::int64_t>));

/**
 * @brief The message of dynamic_bfs's static_assert for an unsupported graph type.
 * @ingroup dynamic_bfs
 */
#define DYNG_DYNAMIC_BFS_TYPES_MESSAGE                                                        \
  "dyng::dynamic_bfs supports graph<int32_t, int32_t or int64_t, int32_t or unweighted> and " \
  "graph<int64_t, int64_t, int32_t> only; see docs/algorithms/dynamic_bfs.md"

/**
 * @brief dynamic_bfs::compute() for a supported graph type (instantiated in the library).
 * @tparam vertex_t Vertex id type.
 * @tparam edge_t   Edge offset type.
 * @tparam weight_t Weight type.
 * @param[in] res Execution resources.
 * @param[in] g   The graph.
 * @param[in] opt Options.
 * @return The result.
 */
template <typename vertex_t, typename edge_t, typename weight_t>
[[nodiscard]] dynamic_bfs::result dynamic_bfs_compute(const resources& res,
                                                      const graph<vertex_t, edge_t, weight_t>& g,
                                                      const dynamic_bfs::options& opt);

/**
 * @brief dynamic_bfs::update() for a supported graph type (instantiated in the library).
 * @tparam vertex_t Vertex id type.
 * @tparam edge_t   Edge offset type.
 * @tparam weight_t Weight type.
 * @param[in]     res   Execution resources.
 * @param[in,out] g     The graph.
 * @param[in]     batch The batch.
 * @param[in,out] r     The result.
 * @return The update's counters.
 */
template <typename vertex_t, typename edge_t, typename weight_t>
dynamic_bfs::stats dynamic_bfs_update(const resources& res, graph<vertex_t, edge_t, weight_t>& g,
                                      const edge_batch_view<vertex_t, weight_t>& batch,
                                      dynamic_bfs::result& r);

}  // namespace dyng::detail

namespace dyng::dynamic_bfs {

/**
 * @brief Compute the result of `g` (the static solve, the oracle of update()).
 * @tparam vertex_t Vertex id type.
 * @tparam edge_t   Edge offset type.
 * @tparam weight_t Weight type (ignored).
 * @param[in] res Execution resources (sequential, openmp, cuda).
 * @param[in] g   The graph, with its in-edges stored (graph_properties::store_transposed, the
 *                default); placed as `res` (host storage for the host backends, a graph built
 *                with CUDA resources for cuda); it is not modified.
 * @param[in] opt Options.
 * @return The result, matching `g.version()`.
 * @throws invalid_argument_error if the source is not a vertex of `g`, `g` does not store its
 *         in-edges, or the placement of `g` does not match `res`.
 * @throws not_supported_error    if the backend of `res` is not available for
 *         dynamic_bfs.
 * @throws out_of_memory_error    if memory cannot be allocated.
 * @sync
 * @backends sequential, openmp, cuda
 * @determinism Exact: identical levels on every backend and run.
 * @paper None: teaching material (the tutorial "Your first dynamic algorithm").
 * @guarantee Strong: `g` is not modified, and nothing is kept if the call throws.
 * @ingroup dynamic_bfs
 */
template <typename vertex_t, typename edge_t, typename weight_t>
[[nodiscard]] result compute(const resources& res, const graph<vertex_t, edge_t, weight_t>& g,
                             const options& opt = {}) {
  static_assert(detail::dynamic_bfs_supported_v<vertex_t, edge_t, weight_t>,
                DYNG_DYNAMIC_BFS_TYPES_MESSAGE);
  return detail::dynamic_bfs_compute(res, g, opt);
}

/**
 * @brief Apply a batch of edge changes to `g` and update `r`.
 *
 * Postcondition: `r` equals compute(res, g, r.get_options()) exactly.
 * @tparam vertex_t Vertex id type.
 * @tparam edge_t   Edge offset type.
 * @tparam weight_t Weight type (ignored).
 * @param[in]     res   Execution resources (sequential, openmp, cuda).
 * @param[in,out] g     The graph; the batch is applied to it and its version increases by one.
 * @param[in]     batch Insertions and deletions (weights are ignored).
 * @param[in,out] r     Result of compute() or of a previous update() on `g`.
 * @return Counters of this update.
 * @throws stale_result_error     if r.graph_version() != g.version() or `r` belongs to another
 *         graph.
 * @throws invalid_argument_error if a batch id or weight is invalid (nothing is changed).
 * @throws not_supported_error    if the backend of `res` is not available for
 *         dynamic_bfs.
 * @throws out_of_memory_error    if memory cannot be allocated.
 * @sync
 * @backends sequential, openmp, cuda
 * @determinism Exact: identical levels and deterministic counters on every backend and run.
 * @paper None: teaching material (the tutorial "Your first dynamic algorithm").
 * @guarantee Strong for every error found before the batch is applied (`g` and `r` unchanged);
 *            basic after the commit (`g` updated, `r` poisoned until it is recomputed).
 * @ingroup dynamic_bfs
 */
template <typename vertex_t, typename edge_t, typename weight_t>
stats update(const resources& res, graph<vertex_t, edge_t, weight_t>& g,
             const edge_batch_view<vertex_t, weight_t>& batch, result& r) {
  static_assert(detail::dynamic_bfs_supported_v<vertex_t, edge_t, weight_t>,
                DYNG_DYNAMIC_BFS_TYPES_MESSAGE);
  return detail::dynamic_bfs_update(res, g, batch, r);
}

}  // namespace dyng::dynamic_bfs

namespace dyng::detail {

/**
 * @brief The update participant of dynamic_bfs::result (used by dyng::update()).
 * @tparam vertex_t Vertex id type.
 * @tparam edge_t   Edge offset type.
 * @tparam weight_t Weight type.
 * @param[in,out] r   The result.
 * @param[out]    out Receives the stats of the update.
 * @return The participant.
 */
template <typename vertex_t, typename edge_t, typename weight_t>
std::unique_ptr<update_participant<vertex_t, edge_t, weight_t>> make_dynamic_bfs_participant(
    dynamic_bfs::result& r, dynamic_bfs::stats& out);

/**
 * @brief update_traits of dynamic_bfs::result (dyng::update() support).
 */
template <>
struct update_traits<dynamic_bfs::result> {
  using stats_type = dynamic_bfs::stats;  ///< the stats type

  /**
   * @brief Create the participant.
   * @tparam container_t The container type.
   * @param[in,out] r   The result.
   * @param[out]    out Receives the stats.
   * @return The participant.
   */
  template <typename container_t>
  static std::unique_ptr<typename participant_of<container_t>::type> make_participant(
      dynamic_bfs::result& r, dynamic_bfs::stats& out) {
    static_assert(
        dynamic_bfs_supported_v<typename container_t::vertex_type, typename container_t::edge_type,
                                typename container_t::weight_type>,
        DYNG_DYNAMIC_BFS_TYPES_MESSAGE);
    return make_dynamic_bfs_participant<typename container_t::vertex_type,
                                        typename container_t::edge_type,
                                        typename container_t::weight_type>(r, out);
  }
};

}  // namespace dyng::detail
