// SPDX-FileCopyrightText: 2026 The dynG Authors
// SPDX-License-Identifier: Apache-2.0
/**
 * @file triangle_delta.hpp
 * @brief triangle_delta: compute() and update() (generated by scripts/new_algorithm.py).
 * @ingroup triangle_delta
 */
#pragma once

#include <dyng/core/array_view.hpp>
#include <dyng/core/memory.hpp>
#include <dyng/core/resources.hpp>
#include <dyng/core/stats.hpp>
#include <dyng/core/types.hpp>
#include <dyng/graph/apply_summary.hpp>
#include <dyng/graph/edge_batch.hpp>
#include <dyng/graph/graph.hpp>
#include <dyng/update.hpp>

#include <cstdint>
#include <memory>
#include <type_traits>

/**
 * @defgroup triangle_delta triangle_delta
 * @brief Dynamic triangle count (tutorial).
 *
 * TODO(triangle_delta): the problem, the update model and the template mapping (the page
 * docs/algorithms/triangle_delta.md has the required sections).
 *
 * Placeholder written by scripts/new_algorithm.py: the number of reciprocal pairs
 * {u -> v, v -> u} of the graph, an aggregate-delta problem. update() applies the batch and
 * recounts from scratch (stats::fallback_used is true); make it incremental in problem.hpp.
 */

namespace dyng::triangle_delta {

/**
 * @brief Options of compute() and update() (an aggregate; fields are only ever appended).
 * @ingroup triangle_delta
 */
struct options {
  /// Reserved for the algorithm's options (options are only ever appended).
  bool validate_inputs = true;
};

/**
 * @brief Counters of one update() (fields are only ever appended).
 * @ingroup triangle_delta
 */
struct stats : update_stats {
  /// Deterministic: what applying the batch did to the graph.
  apply_summary batch;
};

}  // namespace dyng::triangle_delta

namespace dyng::detail {
struct triangle_delta_state;
struct triangle_delta_access;
}  // namespace dyng::detail

namespace dyng::triangle_delta {

/**
 * @brief The result kept up to date by update() (opaque, move-only).
 *
 * The result owns its values (host memory), its options and the graph version it matches.
 * @ingroup triangle_delta
 */
class result {
 public:
  /**
   * @brief Move constructor.
   * @param[in,out] other The result to move from; it may only be assigned to or destroyed after.
   */
  result(result&& other) noexcept;

  /**
   * @brief Move assignment.
   * @param[in,out] other The result to move from; it may only be assigned to or destroyed after.
   * @return *this.
   */
  result& operator=(result&& other) noexcept;

  result(const result&) = delete;             ///< not copyable: use clone()
  result& operator=(const result&) = delete;  ///< not copyable: use clone()
  ~result();                                  ///< releases the values

  /**
   * @brief The aggregate.
   * @return The number of reciprocal pairs.
   * @throws invalid_argument_error for a moved-from result.
   * @throws stale_result_error     if a failed update left the result unusable (poisoned).
   */
  [[nodiscard]] std::uint64_t count() const;

  /**
   * @brief The options.
   * @return The options given at compute(), as changed by set_options().
   * @throws invalid_argument_error for a moved-from result.
   * @throws stale_result_error     if a failed update left the result unusable (poisoned).
   */
  [[nodiscard]] const options& get_options() const;

  /**
   * @brief Change the tunables.
   * @param[in] opt The new options; the ones fixed at compute() must stay the same.
   * @throws invalid_argument_error if a fixed option differs, or for a moved-from result.
   * @throws stale_result_error     if a failed update left the result unusable (poisoned).
   */
  void set_options(const options& opt);

  /**
   * @brief The graph version this result matches.
   * @return The version of the graph after the last compute() / update() of this result.
   */
  [[nodiscard]] std::uint64_t graph_version() const noexcept;

  /**
   * @brief The memory space of the values.
   * @return memory_space::host.
   */
  [[nodiscard]] memory_space space() const noexcept;

  /**
   * @brief A deep copy for the resources `res`.
   * @param[in] res Execution resources of the copy.
   * @return The copy.
   * @throws invalid_argument_error for a moved-from result.
   * @throws stale_result_error     if a failed update left the result unusable (poisoned).
   * @throws not_supported_error    if the backend of `res` is not available for
   *         triangle_delta.
   * @throws out_of_memory_error    if the copy cannot be allocated.
   * @sync
   */
  [[nodiscard]] result clone(const resources& res) const;

 private:
  friend struct detail::triangle_delta_access;
  explicit result(std::unique_ptr<detail::triangle_delta_state> state) noexcept;

  std::unique_ptr<detail::triangle_delta_state> impl_;
};

}  // namespace dyng::triangle_delta

namespace dyng::detail {

/**
 * @brief Whether triangle_delta is instantiated for graph<vertex_t, edge_t, weight_t> (the
 *        explicit instantiations of triangle_delta.cpp: int32_t weights with int32_t ids and
 *        int32_t or int64_t offsets, or int64_t ids and offsets).
 * @tparam vertex_t Vertex id type.
 * @tparam edge_t   Edge offset type.
 * @tparam weight_t Weight type.
 */
template <typename vertex_t, typename edge_t, typename weight_t>
inline constexpr bool triangle_delta_supported_v =
    std::is_same_v<weight_t, std::int32_t> &&
    ((std::is_same_v<vertex_t, std::int32_t> &&
      (std::is_same_v<edge_t, std::int32_t> || std::is_same_v<edge_t, std::int64_t>)) ||
     (std::is_same_v<vertex_t, std::int64_t> && std::is_same_v<edge_t, std::int64_t>));

/**
 * @brief The message of triangle_delta's static_assert for an unsupported graph type.
 * @ingroup triangle_delta
 */
#define DYNG_TRIANGLE_DELTA_TYPES_MESSAGE                                          \
  "dyng::triangle_delta supports graph<int32_t, int32_t or int64_t, int32_t> and " \
  "graph<int64_t, int64_t, int32_t> only; see docs/algorithms/triangle_delta.md"

/**
 * @brief triangle_delta::compute() for a supported graph type (instantiated in the library).
 * @tparam vertex_t Vertex id type.
 * @tparam edge_t   Edge offset type.
 * @tparam weight_t Weight type.
 * @param[in] res Execution resources.
 * @param[in] g   The graph.
 * @param[in] opt Options.
 * @return The result.
 */
template <typename vertex_t, typename edge_t, typename weight_t>
[[nodiscard]] triangle_delta::result triangle_delta_compute(
    const resources& res, const graph<vertex_t, edge_t, weight_t>& g,
    const triangle_delta::options& opt);

/**
 * @brief triangle_delta::update() for a supported graph type (instantiated in the library).
 * @tparam vertex_t Vertex id type.
 * @tparam edge_t   Edge offset type.
 * @tparam weight_t Weight type.
 * @param[in]     res   Execution resources.
 * @param[in,out] g     The graph.
 * @param[in]     batch The batch.
 * @param[in,out] r     The result.
 * @return The update's counters.
 */
template <typename vertex_t, typename edge_t, typename weight_t>
triangle_delta::stats triangle_delta_update(const resources& res,
                                            graph<vertex_t, edge_t, weight_t>& g,
                                            const edge_batch_view<vertex_t, weight_t>& batch,
                                            triangle_delta::result& r);

}  // namespace dyng::detail

namespace dyng::triangle_delta {

/**
 * @brief Compute the result of `g` (the static solve, the oracle of update()).
 * @tparam vertex_t Vertex id type.
 * @tparam edge_t   Edge offset type.
 * @tparam weight_t Weight type (ignored).
 * @param[in] res Execution resources (sequential, openmp).
 * @param[in] g   The graph (host storage); it is not modified.
 * @param[in] opt Options.
 * @return The result, matching `g.version()`.
 * @throws invalid_argument_error if an option is out of range or `g` is not host storage.
 * @throws not_supported_error    if the backend of `res` is not available for
 *         triangle_delta.
 * @throws out_of_memory_error    if host memory cannot be allocated.
 * @sync
 * @backends sequential, openmp
 * @determinism Exact: identical results on every backend and run.
 * @paper None yet (TODO(triangle_delta): the paper, and its key in docs/references.bib).
 * @guarantee Strong: `g` is not modified, and nothing is kept if the call throws.
 * @ingroup triangle_delta
 */
template <typename vertex_t, typename edge_t, typename weight_t>
[[nodiscard]] result compute(const resources& res, const graph<vertex_t, edge_t, weight_t>& g,
                             const options& opt = {}) {
  static_assert(detail::triangle_delta_supported_v<vertex_t, edge_t, weight_t>,
                DYNG_TRIANGLE_DELTA_TYPES_MESSAGE);
  return detail::triangle_delta_compute(res, g, opt);
}

/**
 * @brief Apply a batch of edge changes to `g` and update `r`.
 *
 * Postcondition: `r` equals compute(res, g, r.get_options()) exactly.
 * @tparam vertex_t Vertex id type.
 * @tparam edge_t   Edge offset type.
 * @tparam weight_t Weight type (ignored).
 * @param[in]     res   Execution resources (sequential, openmp).
 * @param[in,out] g     The graph; the batch is applied to it and its version increases by one.
 * @param[in]     batch Insertions, deletions and weight changes.
 * @param[in,out] r     Result of compute() or of a previous update() on `g`.
 * @return Counters of this update.
 * @throws stale_result_error     if r.graph_version() != g.version() or `r` belongs to another
 *         graph.
 * @throws invalid_argument_error if a batch id or weight is invalid (nothing is changed).
 * @throws not_supported_error    if the backend of `res` is not available for
 *         triangle_delta.
 * @throws out_of_memory_error    if host memory cannot be allocated.
 * @sync
 * @backends sequential, openmp
 * @determinism Exact: identical results on every backend and run.
 * @paper None yet (TODO(triangle_delta)).
 * @guarantee Strong for every error found before the batch is applied (`g` and `r` unchanged);
 *            basic after the commit (`g` updated, `r` poisoned until it is recomputed).
 * @ingroup triangle_delta
 */
template <typename vertex_t, typename edge_t, typename weight_t>
stats update(const resources& res, graph<vertex_t, edge_t, weight_t>& g,
             const edge_batch_view<vertex_t, weight_t>& batch, result& r) {
  static_assert(detail::triangle_delta_supported_v<vertex_t, edge_t, weight_t>,
                DYNG_TRIANGLE_DELTA_TYPES_MESSAGE);
  return detail::triangle_delta_update(res, g, batch, r);
}

}  // namespace dyng::triangle_delta

namespace dyng::detail {

/**
 * @brief The update participant of an triangle_delta result (used by dyng::update()).
 * @tparam vertex_t Vertex id type.
 * @tparam edge_t   Edge offset type.
 * @tparam weight_t Weight type.
 * @param[in,out] r   The result.
 * @param[out]    out Receives the stats of the update.
 * @return The participant.
 */
template <typename vertex_t, typename edge_t, typename weight_t>
std::unique_ptr<update_participant<vertex_t, edge_t, weight_t>> make_triangle_delta_participant(
    triangle_delta::result& r, triangle_delta::stats& out);

/**
 * @brief update_traits of triangle_delta::result (dyng::update() support).
 */
template <>
struct update_traits<triangle_delta::result> {
  using stats_type = triangle_delta::stats;  ///< the stats type

  /**
   * @brief Create the participant.
   * @tparam container_t The container type.
   * @param[in,out] r   The result.
   * @param[out]    out Receives the stats.
   * @return The participant.
   */
  template <typename container_t>
  static std::unique_ptr<typename participant_of<container_t>::type> make_participant(
      triangle_delta::result& r, triangle_delta::stats& out) {
    static_assert(triangle_delta_supported_v<typename container_t::vertex_type,
                                             typename container_t::edge_type,
                                             typename container_t::weight_type>,
                  DYNG_TRIANGLE_DELTA_TYPES_MESSAGE);
    return make_triangle_delta_participant<typename container_t::vertex_type,
                                           typename container_t::edge_type,
                                           typename container_t::weight_type>(r, out);
  }
};

}  // namespace dyng::detail
