// SPDX-FileCopyrightText: 2026 The dynG Authors
// SPDX-License-Identifier: Apache-2.0
/**
 * @file algorithm_template_test.cpp
 * @brief Hand cases of algorithm_template: paper examples, regression seeds, edge cases (PLAN
 *        Section 4.8, file 12; generated by scripts/new_algorithm.py).
 */
#include <dyng/algorithm_template.hpp>
#include <dyng/core/copy.hpp>
#include <dyng/core/resources.hpp>
#include <dyng/graph/edge_batch.hpp>
#include <dyng/graph/edge_list.hpp>
#include <dyng/graph/graph.hpp>

#include <gtest/gtest.h>

#include <cstdint>
#include <utility>
#include <vector>

namespace {

using graph_t = dyng::graph<std::int32_t, std::int32_t, std::int32_t>;

graph_t make_graph(const dyng::resources& res, std::int32_t n,
                   const std::vector<std::pair<std::int32_t, std::int32_t>>& edges) {
  dyng::edge_list<std::int32_t, std::int32_t> list;
  list.num_vertices = n;
  list.num_weights = 1;
  for (const auto& [u, v] : edges) {
    list.add_edge(u, v, {1});
  }
  return graph_t::from_edges(res, list.view());
}

// TODO(algorithm_template): the paper's example and the edge cases of the algorithm.
TEST(AlgorithmTemplate, AnUpdateEqualsCompute) {
  const dyng::resources res = dyng::resources::sequential();
  graph_t g = make_graph(res, 4, {{0, 1}, {1, 0}, {1, 2}, {2, 3}});
  auto r = dyng::algorithm_template::compute(res, g);
  dyng::edge_batch<std::int32_t, std::int32_t> batch;
  batch.delete_edge(1, 2);
  batch.insert_edge(3, 2, {1});
  const auto s = dyng::algorithm_template::update(res, g, batch.view(), r);
  EXPECT_TRUE(s.fallback_used);  // the placeholder recomputes ("start green")
  const auto fresh = dyng::algorithm_template::compute(res, g);
  //@@ fixed_point
  EXPECT_EQ(dyng::to_vector(res, r.levels()), dyng::to_vector(res, fresh.levels()));
  EXPECT_EQ(dyng::to_vector(res, r.levels()), (std::vector<std::int64_t>{0, 1, -1, -1}));
  //@@ end
  //@@ aggregate_delta
  EXPECT_EQ(r.count(), fresh.count());
  EXPECT_EQ(r.count(), 2U);  // {0, 1} and {2, 3}
                             //@@ end
  EXPECT_EQ(r.graph_version(), g.version());
}

}  // namespace
