// SPDX-FileCopyrightText: 2026 The dynG Authors
// SPDX-License-Identifier: Apache-2.0
/**
 * @file triangle_delta_traits.hpp
 * @brief The conformance-kit traits of triangle_delta (PLAN Section 8.2; cpp/tests/conformance;
 *        generated by scripts/new_algorithm.py).
 */
#pragma once

#include "conformance/test_traits.hpp"
#include "conformance/type_list.hpp"

#include <dyng/core/backend.hpp>
#include <dyng/core/copy.hpp>
#include <dyng/core/resources.hpp>
#include <dyng/core/types.hpp>
#include <dyng/graph/edge_batch.hpp>
#include <dyng/graph/edge_list.hpp>
#include <dyng/graph/graph.hpp>
#include <dyng/graph/graph_properties.hpp>
#include <dyng/triangle_delta.hpp>

#include <cstdint>
#include <functional>
#include <string_view>
#include <vector>

namespace dyng::conformance {

/// triangle_delta (TODO(triangle_delta): what the kit compares).
template <>
struct test_traits<tags::triangle_delta> {
  static constexpr std::string_view name = "triangle_delta";      ///< as in the manifest
  static constexpr oracle_kind oracle = oracle_kind::compute;     ///< update chain == compute
  static constexpr determinism level = determinism::exact_value;  ///< identical values
  static constexpr bool history_independent = true;               ///< the result of a graph
  /// The instantiated graph types (DYNG_FOR_EACH_GRAPH_TYPE).
  using graph_types = type_list<graph<std::int32_t, std::int32_t, std::int32_t>,
                                graph<std::int32_t, std::int64_t, std::int32_t>,
                                graph<std::int64_t, std::int64_t, std::int32_t>>;
  template <typename graph_t>
  using result = triangle_delta::result;  ///< the result
  using stats = triangle_delta::stats;    ///< update()'s stats
  using snapshot = std::uint64_t;         ///< the count

  /// The graph requirements.
  static void require(graph_properties& props) {
    props.order = row_order::sorted;
    props.parallel_edges = multi_edges::forbid;
  }
  /// The generated graphs.
  static graph_shape shape(size_class size) {
    switch (size) {
      case size_class::tiny:
        return {6, 10, 5};
      case size_class::small:
        return {30, 100, 9};
      case size_class::medium:
        return {120, 500, 9};
    }
    return {};
  }
  /// compute() (one engine).
  template <typename graph_t>
  static result<graph_t> compute(const resources& res, const graph_t& g, engine /*e*/) {
    return triangle_delta::compute(res, g);
  }
  /// update().
  template <typename graph_t>
  static stats update(
      const resources& res, graph_t& g,
      const edge_batch_view<typename graph_t::vertex_type, typename graph_t::weight_type>& batch,
      result<graph_t>& r) {
    return triangle_delta::update(res, g, batch, r);
  }
  /// The result on the host.
  template <typename graph_t>
  static snapshot take(const resources& res, const result<graph_t>& r) {
    (void)res;
    return r.count();
  }
  /// The counters that are equal across runs and backends (besides the common ones).
  static std::vector<std::int64_t> deterministic(const stats& /*s*/) {
    return {};
  }
  /// Options and graphs compute() and set_options() reject.
  template <typename graph_t>
  static std::vector<std::function<void()>> invalid_options(const resources& res,
                                                            const graph_t& g) {
    return {
        [&] {
          edge_list<typename graph_t::vertex_type, typename graph_t::weight_type> list;
          list.num_vertices = 2;
          graph_properties props = g.properties();
          props.order = row_order::append;
          props.parallel_edges = multi_edges::allow;
          props.semantics = batch_semantics::upsert_last_wins();
          const graph_t append = graph_t::from_edges(res, list.view(), props);
          (void)triangle_delta::compute(res, append);
        },
    };
  }
  /// C8: host synchronizations of the algorithm phase (none: host backends only).
  static std::int64_t host_sync_budget(backend /*b*/) {
    return 0;
  }
};

}  // namespace dyng::conformance
