// SPDX-FileCopyrightText: 2026 The dynG Authors
// SPDX-License-Identifier: Apache-2.0
/**
 * @file triangle_delta_test.cpp
 * @brief Hand cases of triangle_delta: the worked example of its page and the edge cases (PLAN
 *        Section 4.8, file 12; first generated by scripts/new_algorithm.py).
 */
#include <dyng/core/backend.hpp>
#include <dyng/core/error.hpp>
#include <dyng/core/resources.hpp>
#include <dyng/graph/edge_batch.hpp>
#include <dyng/graph/edge_list.hpp>
#include <dyng/graph/graph.hpp>
#include <dyng/graph/graph_properties.hpp>
#include <dyng/triangle_delta.hpp>

#include <gtest/gtest.h>

#include <cstdint>
#include <string>
#include <utility>
#include <vector>

namespace {

using graph_t = dyng::graph<std::int32_t, std::int32_t, std::int32_t>;
using batch_t = dyng::edge_batch<std::int32_t, std::int32_t>;

/// An undirected graph (each edge given once, stored in both directions).
graph_t make_graph(const dyng::resources& res, std::int32_t n,
                   const std::vector<std::pair<std::int32_t, std::int32_t>>& edges,
                   dyng::batch_semantics semantics = dyng::batch_semantics::upsert_last_wins()) {
  dyng::edge_list<std::int32_t, std::int32_t> list;
  list.num_vertices = n;
  list.num_weights = 1;
  for (const auto& [u, v] : edges) {
    list.add_edge(u, v, {1});
  }
  dyng::graph_properties props;
  props.directed = false;
  props.semantics = semantics;
  return graph_t::from_edges(res, list.view(), props);
}

/// The host backends of this build.
std::vector<dyng::resources> host_backends() {
  std::vector<dyng::resources> out{dyng::resources::sequential()};
  if (dyng::backend_available(dyng::backend::openmp)) {
    out.push_back(dyng::resources::openmp(4));
  }
  return out;
}

// The worked example of docs/algorithms/triangle_delta.md: K4 without the edge {2, 3}.
TEST(TriangleDelta, ThePageExample) {
  for (const dyng::batch_semantics semantics :
       {dyng::batch_semantics::upsert_last_wins(), dyng::batch_semantics::set()}) {
    for (const dyng::resources& res : host_backends()) {
      SCOPED_TRACE(std::string(dyng::to_string(res.get_backend())));
      graph_t g = make_graph(res, 4, {{0, 1}, {0, 2}, {0, 3}, {1, 2}, {1, 3}}, semantics);
      auto r = dyng::triangle_delta::compute(res, g);
      EXPECT_EQ(r.count(), 2U);  // {0, 1, 2} and {0, 1, 3}

      // Inserting {2, 3} closes two triangles (the common neighbours 0 and 1): K4 has four.
      batch_t close;
      close.insert_edge(3, 2, {1});  // either direction names the undirected edge
      const auto s = dyng::triangle_delta::update(res, g, close.view(), r);
      EXPECT_FALSE(s.fallback_used);
      EXPECT_EQ(s.insertions, 1);
      EXPECT_EQ(s.triangles_added, 2U);
      EXPECT_EQ(r.count(), 4U);

      // Deleting {0, 1} and {0, 2} destroys three triangles; {0, 1, 2} goes through both and is
      // counted once, by the smaller edge {0, 1} (ownership::min_member).
      batch_t cut;
      cut.delete_edge(0, 1);
      cut.delete_edge(2, 0);
      const auto t = dyng::triangle_delta::update(res, g, cut.view(), r);
      EXPECT_EQ(t.deletions, 2);
      EXPECT_EQ(t.triangles_removed, 3U);
      EXPECT_EQ(t.triangles_added, 0U);
      EXPECT_EQ(t.affected, 1);
      EXPECT_EQ(r.count(), 1U);  // {1, 2, 3}
      EXPECT_EQ(r.count(), dyng::triangle_delta::compute(res, g).count());
    }
  }
}

TEST(TriangleDelta, ADeletedAndReinsertedEdgeChangesNothing) {
  for (const dyng::resources& res : host_backends()) {
    graph_t g = make_graph(res, 3, {{0, 1}, {1, 2}, {0, 2}});
    auto r = dyng::triangle_delta::compute(res, g);
    batch_t again;
    again.delete_edge(0, 1);
    again.insert_edge(0, 1, {1});  // deletions first: removed, then added back
    const auto s = dyng::triangle_delta::update(res, g, again.view(), r);
    EXPECT_EQ(s.triangles_removed, 1U);
    EXPECT_EQ(s.triangles_added, 1U);
    EXPECT_EQ(s.affected, 0);
    EXPECT_EQ(r.count(), 1U);
  }
}

TEST(TriangleDelta, SelfLoopsAndNewVerticesCloseNoTriangle) {
  for (const dyng::resources& res : host_backends()) {
    graph_t g = make_graph(res, 3, {{0, 1}, {1, 2}, {0, 2}});
    auto r = dyng::triangle_delta::compute(res, g);
    batch_t grow;
    grow.insert_edge(1, 1, {1});  // a self-loop (kept by upsert semantics)
    grow.insert_edge(2, 4, {1});  // vertices 3 and 4 appear
    grow.insert_edge(1, 4, {1});  // {1, 2, 4} is a triangle
    (void)dyng::triangle_delta::update(res, g, grow.view(), r);
    EXPECT_EQ(r.count(), 2U);
    EXPECT_EQ(r.count(), dyng::triangle_delta::compute(res, g).count());
  }
}

TEST(TriangleDelta, RejectsGraphsItCannotCount) {
  const dyng::resources res = dyng::resources::sequential();
  dyng::edge_list<std::int32_t, std::int32_t> list;
  list.num_vertices = 3;
  list.num_weights = 1;
  list.add_edge(0, 1, {1});
  const graph_t directed = graph_t::from_edges(res, list.view());
  EXPECT_THROW((void)dyng::triangle_delta::compute(res, directed), dyng::invalid_argument_error);
}

}  // namespace
