// SPDX-FileCopyrightText: 2026 The dynG Authors
// SPDX-License-Identifier: Apache-2.0
/**
 * @file openmp.cpp
 * @brief triangle_delta: the OpenMP backend (PLAN Section 4.8, file 7; generated by
 *        scripts/new_algorithm.py).
 *
 * TODO(triangle_delta): the placeholder runs the sequential backend, so the conformance kit's
 * cross-backend check (C3) holds from the first build; write the parallel version and keep C3
 * green.
 */
#include "algorithms/triangle_delta/problem.hpp"
#include "graph/instantiate.hpp"

#include <dyng/core/resources.hpp>
#include <dyng/graph/csr.hpp>

#include <cstdint>
#include <vector>

namespace dyng::detail {

template <typename vertex_t, typename edge_t, typename weight_t>
std::uint64_t triangle_delta_openmp(const resources& /*res*/,
                                    const csr_view<vertex_t, edge_t, weight_t>& out) {
  return triangle_delta_sequential(out);
}

#define DYNG_INSTANTIATE(V, E, W) \
  template std::uint64_t triangle_delta_openmp<V, E, W>(const resources&, const csr_view<V, E, W>&);
DYNG_FOR_EACH_GRAPH_TYPE(DYNG_INSTANTIATE)
#undef DYNG_INSTANTIATE

}  // namespace dyng::detail
