// SPDX-FileCopyrightText: 2026 The dynG Authors
// SPDX-License-Identifier: Apache-2.0
/**
 * @file problem.hpp
 * @brief The triangle_delta problem on the framework (cpp/src/framework): its hooks, its
 *        state and its workspace (generated by scripts/new_algorithm.py).
 *
 * Template card (PLAN Section 4.5.2; docs/developer/framework.md):
 *
 *     normalize -> prepare -> count(-) on G_t -> commit ->
 *     identify_affected -> count(+) on G_{t+1} -> finalize
 *
 * An aggregate-delta problem with the exactly-once rule ownership::min_member (invariant I2). The
 * placeholder ("start green", PLAN Section 4.8) leaves count(-) empty and recounts everything in
 * count(+) (finalize sets stats::fallback_used = true), so update() recomputes. To make it
 * incremental: in count(-), count on G_t what the deleted edges destroy; in count(+), count on
 * G_{t+1} what the inserted edges create, each pattern attributed to its smallest changed edge;
 * in finalize, apply the signed delta.
 *
 * compute() is the static enactor with the same hooks (reset first). Lifecycle members without a
 * stage: begin_update (the checks before anything changes), resume (bind G_{t+1}, grow the
 * result, lease the workspace), end_update (record the graph state), poison.
 */
#pragma once

#include "framework/budgets.hpp"
#include "framework/composition.hpp"
#include "framework/context.hpp"
#include "framework/frontier.hpp"
#include "framework/policies.hpp"
#include "framework/problem.hpp"
#include "framework/views.hpp"
#include "framework/workspace.hpp"

#include <dyng/core/backend.hpp>
#include <dyng/core/resources.hpp>
#include <dyng/graph/csr.hpp>
#include <dyng/graph/graph.hpp>
#include <dyng/triangle_delta.hpp>

#include <cstddef>
#include <cstdint>
#include <optional>
#include <string_view>
#include <vector>

namespace dyng::detail {

/// The state behind an triangle_delta::result.
struct triangle_delta_state {
  triangle_delta::options opt;    ///< the options
  std::uint64_t count = 0;        ///< the aggregate
  std::uint64_t version = 0;      ///< graph version matched
  std::uint64_t graph_state = 0;  ///< graph state matched (ADR 0006, "Graph identity")
  bool poisoned = false;          ///< a failed update left the result unusable
};

/// Access to the state of a result.
struct triangle_delta_access {
  /// The state of `r`.
  static triangle_delta_state& state(triangle_delta::result& r);
  /// The state of `r`.
  static const triangle_delta_state& state(const triangle_delta::result& r);
  /// A result owning `st`.
  static triangle_delta::result make(std::unique_ptr<triangle_delta_state> st);
};

/// Scratch space of the engines, leased from the workspace pool of the resources handle (ADR 0015).
struct triangle_delta_workspace final : pooled_workspace {
  std::vector<std::int64_t> unused;  ///< TODO(triangle_delta): the scratch of the counts

  /// Size the arrays for `n` vertices (a reservation when they grow, invariant I9).
  void reserve(std::size_t n);

  /// Bytes of the arrays' capacities.
  [[nodiscard]] std::size_t bytes() const noexcept override;
};

/**
 * @brief The static count on the sequential backend: reciprocal pairs {u -> v, v -> u}.
 * @tparam vertex_t Vertex id type.
 * @tparam edge_t   Edge offset type.
 * @tparam weight_t Weight type.
 * @param[in] out The out-edges (host, sorted rows).
 * @return The count.
 */
template <typename vertex_t, typename edge_t, typename weight_t>
std::uint64_t triangle_delta_sequential(const csr_view<vertex_t, edge_t, weight_t>& out);

/**
 * @brief The static count on the OpenMP backend (as triangle_delta_sequential()).
 * @tparam vertex_t Vertex id type.
 * @tparam edge_t   Edge offset type.
 * @tparam weight_t Weight type.
 * @param[in] res The resources (their thread count).
 * @param[in] out The out-edges (host, sorted rows).
 * @return The count.
 */
template <typename vertex_t, typename edge_t, typename weight_t>
std::uint64_t triangle_delta_openmp(const resources& res,
                                    const csr_view<vertex_t, edge_t, weight_t>& out);

/// The update family of triangle_delta.
inline constexpr framework::family triangle_delta_family = framework::family::aggregate_delta;

/**
 * @brief The triangle_delta problem (see the file comment).
 * @tparam vertex_t Vertex id type.
 * @tparam edge_t   Edge offset type.
 * @tparam weight_t Weight type.
 */
template <typename vertex_t, typename edge_t, typename weight_t>
class triangle_delta_problem final
    : public framework::problem_base<triangle_delta_problem<vertex_t, edge_t, weight_t>,
                                     triangle_delta_family> {
 public:
  static constexpr std::string_view name = "triangle_delta";         ///< stages "<name>.<hook>"
  using container_type = graph<vertex_t, edge_t, weight_t>;          ///< the container
  using stats_type = triangle_delta::stats;                          ///< the stats of update()
  using frontier_type = framework::internal_frontier;                ///< frontiers are internal
  using ownership_type = framework::ownership::min_member;           ///< the counting rule (I2)
  using old_graph = framework::old_view<container_type>;             ///< G_t
  using new_graph = framework::new_view<container_type>;             ///< G_{t+1}
  using requested = framework::requested_batch<vertex_t, weight_t>;  ///< the batch before commit
  using applied = framework::applied_batch<vertex_t>;                ///< what the commit did

  /// The problem of one update of `r`.
  explicit triangle_delta_problem(triangle_delta::result& r)
      : state_(&triangle_delta_access::state(r)), target_(&r) {}
  /// The problem of one compute() filling `st`.
  explicit triangle_delta_problem(triangle_delta_state& st) : state_(&st) {}

  // ---- lifecycle (no stage) ----

  /// The result this problem updates (nullptr for compute()).
  [[nodiscard]] const void* target() const noexcept {
    return target_;
  }
  /// The checks before anything changes: backend, poisoned and stale result.
  void begin_update(framework::context& ctx, old_graph g, const requested& batch);
  /// Bind G_{t+1}: grow the result for new vertices, lease the workspace.
  void resume(framework::context& ctx, new_graph g, const applied& applied);
  /// Record the graph state the result matches; return the workspace.
  void end_update(framework::context& ctx, new_graph g, const stats_type& stats);
  /// Mark the result unusable (a failed algorithm phase).
  void poison() noexcept {
    state_->poisoned = true;
  }
  /// The engines read the out-edges only (the commit need not build the in-edges).
  [[nodiscard]] bool reads_prepared_graph() const noexcept {
    return false;
  }
  /// The budget of the algorithm phase (invariant I9, conformance check C8): nothing allocated
  /// once reserved, no host synchronization.
  [[nodiscard]] framework::budget algorithm_budget(framework::context& /*ctx*/) const noexcept {
    return framework::budget::steady_state(0);
  }

  // ---- the signed recount ----

  /// triangle_delta.count_minus on G_t: the placeholder counts nothing (count(+) recounts).
  void count(framework::context& ctx, old_graph g, frontier_type& f, framework::sign s,
             ownership_type rule);
  /// triangle_delta.count_plus on G_{t+1} (and triangle_delta.count in compute()): the
  /// placeholder recounts everything.
  void count(framework::context& ctx, new_graph g, frontier_type& f, framework::sign s,
             ownership_type rule);
  /// triangle_delta.finalize: the stats (the placeholder sets fallback_used in update()).
  void finalize(framework::context& ctx, stats_type& stats);

  // ---- compute() ----

  /// triangle_delta.reset: start the static solve.
  void reset(framework::context& ctx);

 private:
  /// The static solve of `g` into the state.
  void solve(framework::context& ctx, const container_type& g);

  triangle_delta_state* state_ = nullptr;
  const triangle_delta::result* target_ = nullptr;
  bool computing_ = false;
  std::optional<workspace_pool::lease<triangle_delta_workspace>> ws_;
  std::uint64_t before_ = 0;
};

}  // namespace dyng::detail
