// SPDX-FileCopyrightText: 2026 The dynG Authors
// SPDX-License-Identifier: Apache-2.0
/**
 * @file sequential.cpp
 * @brief triangle_delta: the sequential reference backend, the oracle of the other backends
 *        and of update() (PLAN Section 4.8, file 6; generated by scripts/new_algorithm.py).
 */
#include "algorithms/triangle_delta/problem.hpp"
#include "graph/instantiate.hpp"

#include <dyng/graph/csr.hpp>

#include <algorithm>
#include <cstddef>
#include <cstdint>
#include <vector>

namespace dyng::detail {

template <typename vertex_t, typename edge_t, typename weight_t>
std::uint64_t triangle_delta_sequential(const csr_view<vertex_t, edge_t, weight_t>& out) {
  // TODO(triangle_delta): the static count. The placeholder: reciprocal pairs u < v.
  const auto n = static_cast<std::size_t>(out.num_vertices());
  std::uint64_t pairs = 0;
  for (std::size_t u = 0; u < n; ++u) {
    for (auto e = out.row_ptr[u]; e < out.row_ptr[u + 1]; ++e) {
      const auto v = static_cast<std::size_t>(out.col_ind[static_cast<std::size_t>(e)]);
      if (u < v) {
        const vertex_t* first = out.col_ind.data() + out.row_ptr[v];
        const vertex_t* last = out.col_ind.data() + out.row_ptr[v + 1];
        pairs += std::binary_search(first, last, static_cast<vertex_t>(u)) ? 1 : 0;
      }
    }
  }
  return pairs;
}

#define DYNG_INSTANTIATE(V, E, W) \
  template std::uint64_t triangle_delta_sequential<V, E, W>(const csr_view<V, E, W>&);
DYNG_FOR_EACH_GRAPH_TYPE(DYNG_INSTANTIATE)
#undef DYNG_INSTANTIATE

}  // namespace dyng::detail
