// SPDX-FileCopyrightText: 2026 The dynG Authors
// SPDX-License-Identifier: Apache-2.0
/**
 * @file triangle_delta.cpp
 * @brief triangle_delta: argument validation, the result, compute() and update() through the
 *        framework's enactors, the hooks of the problem, and the explicit instantiations
 *        (generated by scripts/new_algorithm.py; PLAN Section 4.8, file 4).
 */
#include "algorithms/triangle_delta/problem.hpp"
#include "core/budget_counters.hpp"
#include "framework/composition.hpp"
#include "framework/context.hpp"
#include "framework/enactor.hpp"
#include "framework/views.hpp"
#include "graph/graph_impl.hpp"
#include "graph/instantiate.hpp"

#include <dyng/core/backend.hpp>
#include <dyng/core/error.hpp>
#include <dyng/core/memory.hpp>
#include <dyng/triangle_delta.hpp>
#include <dyng/update.hpp>

#include <algorithm>
#include <cstddef>
#include <cstdint>
#include <memory>
#include <string>
#include <utility>

namespace dyng::detail {

namespace {

/// The backends of the manifest that this algorithm implements.
bool implemented(backend b) {
  return b == backend::sequential || b == backend::openmp;
}

/// Throws not_supported_error unless the backend of `res` is implemented and built.
void expect_backend(const resources& res, const char* function) {
  const backend b = res.get_backend();
  if (!implemented(b) || !backend_available(b)) {
    throw not_supported_error(concat_message("dyng: ", function, ": the ", to_string(b),
                                             " backend is not available for "
                                             "triangle_delta (available: sequential",
                                             backend_available(backend::openmp) ? ", openmp" : "",
                                             ")"));
  }
}

/// Throws stale_result_error for a poisoned result.
void expect_not_poisoned(const triangle_delta_state& st, const char* function) {
  if (st.poisoned) {
    throw stale_result_error(concat_message(
        "dyng: ", function, ": a failed update left this result unusable; recompute it"));
  }
}

/// The state of a result, or invalid_argument_error for a moved-from one.
template <typename state_t>
state_t& checked(state_t* st, const char* function) {
  DYNG_EXPECTS(st != nullptr, function, ": the result was moved from");
  expect_not_poisoned(*st, function);
  return *st;
}

}  // namespace

triangle_delta_state& triangle_delta_access::state(triangle_delta::result& r) {
  DYNG_EXPECTS(r.impl_ != nullptr, "triangle_delta: the result was moved from");
  return *r.impl_;
}

const triangle_delta_state& triangle_delta_access::state(const triangle_delta::result& r) {
  DYNG_EXPECTS(r.impl_ != nullptr, "triangle_delta: the result was moved from");
  return *r.impl_;
}

triangle_delta::result triangle_delta_access::make(std::unique_ptr<triangle_delta_state> st) {
  return triangle_delta::result(std::move(st));
}

void triangle_delta_workspace::reserve(std::size_t n) {
  (void)n;
}

std::size_t triangle_delta_workspace::bytes() const noexcept {
  return unused.capacity() * sizeof(std::int64_t);
}

// ------------------------------------------------------------------------------------------------
// The problem
// ------------------------------------------------------------------------------------------------

template <typename vertex_t, typename edge_t, typename weight_t>
void triangle_delta_problem<vertex_t, edge_t, weight_t>::begin_update(framework::context& ctx,
                                                                      old_graph g,
                                                                      const requested& /*batch*/) {
  expect_backend(ctx.res(), "triangle_delta::update");
  graph_access::expect_placement(ctx.res(), g.get(), "triangle_delta::update");
  expect_not_poisoned(*state_, "triangle_delta::update");
  framework::expect_current_result("triangle_delta::update", state_->version, state_->graph_state,
                                   g.get());
}

template <typename vertex_t, typename edge_t, typename weight_t>
void triangle_delta_problem<vertex_t, edge_t, weight_t>::resume(framework::context& ctx,
                                                                new_graph g,
                                                                const applied& /*applied*/) {
  const auto n = static_cast<std::size_t>(g->num_vertices());
  ws_.emplace(ctx.lease_workspace<triangle_delta_workspace>());
  (*ws_)->reserve(n);
  before_ = state_->count;
}

template <typename vertex_t, typename edge_t, typename weight_t>
void triangle_delta_problem<vertex_t, edge_t, weight_t>::end_update(framework::context& /*ctx*/,
                                                                    new_graph g,
                                                                    const stats_type& /*stats*/) {
  framework::stamp_result(state_->version, state_->graph_state, g.get());
  ws_.reset();
}

template <typename vertex_t, typename edge_t, typename weight_t>
void triangle_delta_problem<vertex_t, edge_t, weight_t>::solve(framework::context& ctx,
                                                               const container_type& g) {
  if (!ws_) {
    ws_.emplace(ctx.lease_workspace<triangle_delta_workspace>());
    (*ws_)->reserve(static_cast<std::size_t>(g.num_vertices()));
  }
  const auto out = graph_access::out_view(g);
  if (ctx.res().get_backend() == backend::openmp) {
    state_->count = triangle_delta_openmp(ctx.res(), out);
    return;
  }
  state_->count = triangle_delta_sequential(out);
}

template <typename vertex_t, typename edge_t, typename weight_t>
void triangle_delta_problem<vertex_t, edge_t, weight_t>::count(framework::context& /*ctx*/,
                                                               old_graph /*g*/,
                                                               frontier_type& /*f*/,
                                                               framework::sign /*s*/,
                                                               ownership_type /*rule*/) {
  // TODO(triangle_delta): subtract on G_t what the deleted edges destroy.
}

template <typename vertex_t, typename edge_t, typename weight_t>
void triangle_delta_problem<vertex_t, edge_t, weight_t>::count(framework::context& ctx, new_graph g,
                                                               frontier_type& /*f*/,
                                                               framework::sign /*s*/,
                                                               ownership_type /*rule*/) {
  // TODO(triangle_delta): add on G_{t+1} what the inserted edges create.
  solve(ctx, g.get());
}

template <typename vertex_t, typename edge_t, typename weight_t>
void triangle_delta_problem<vertex_t, edge_t, weight_t>::finalize(framework::context& /*ctx*/,
                                                                  stats_type& stats) {
  if (computing_) {
    return;
  }
  stats.affected = before_ != state_->count ? 1 : 0;
  stats.fallback_used = true;  // the placeholder recomputed (PLAN Section 4.8, "start green")
}

template <typename vertex_t, typename edge_t, typename weight_t>
void triangle_delta_problem<vertex_t, edge_t, weight_t>::reset(framework::context& /*ctx*/) {
  computing_ = true;
}

}  // namespace dyng::detail

// ------------------------------------------------------------------------------------------------
// The public functions
// ------------------------------------------------------------------------------------------------

namespace dyng::triangle_delta {

result::result(std::unique_ptr<detail::triangle_delta_state> state) noexcept
    : impl_(std::move(state)) {}
result::result(result&& other) noexcept = default;
result& result::operator=(result&& other) noexcept = default;
result::~result() = default;

std::uint64_t result::count() const {
  return detail::checked(impl_.get(), "triangle_delta::result::count").count;
}

const options& result::get_options() const {
  return detail::checked(impl_.get(), "triangle_delta::result::get_options").opt;
}

void result::set_options(const options& opt) {
  auto& st = detail::checked(impl_.get(), "triangle_delta::result::set_options");
  st.opt = opt;
}

std::uint64_t result::graph_version() const noexcept {
  return impl_ == nullptr ? 0 : impl_->version;
}

memory_space result::space() const noexcept {
  return memory_space::host;
}

result result::clone(const resources& res) const {
  const auto& st = detail::checked(impl_.get(), "triangle_delta::result::clone");
  detail::expect_backend(res, "triangle_delta::result::clone");
  return result(std::make_unique<detail::triangle_delta_state>(st));
}

}  // namespace dyng::triangle_delta

namespace dyng::detail {

// compute() and update() behind the public wrappers of the header (which static_assert the
// supported graph types).
template <typename vertex_t, typename edge_t, typename weight_t>
triangle_delta::result triangle_delta_compute(const resources& res,
                                              const graph<vertex_t, edge_t, weight_t>& g,
                                              const triangle_delta::options& opt) {
  using problem_t = detail::triangle_delta_problem<vertex_t, edge_t, weight_t>;
  detail::expect_backend(res, "triangle_delta::compute");
  detail::graph_access::expect_placement(res, g, "triangle_delta::compute");
  // The graph requirements (PLAN Section 5.1): the count searches sorted rows of a simple graph.
  DYNG_EXPECTS(g.properties().order == row_order::sorted &&
                   g.properties().parallel_edges == multi_edges::forbid,
               "triangle_delta::compute: the graph needs sorted rows without parallel edges "
               "(graph_properties::order = row_order::sorted, parallel_edges = "
               "multi_edges::forbid)");
  const detail::framework::hook_stages& names = detail::framework::stages_of<problem_t>();
  scoped_stage stage(res, names.compute);
  auto st = std::make_unique<detail::triangle_delta_state>();
  st->opt = opt;
  problem_t p(*st);
  detail::framework::context ctx(res, problem_t::name);
  detail::framework::static_enactor<problem_t> enactor(p);
  (void)enactor.run(ctx, detail::framework::new_view<graph<vertex_t, edge_t, weight_t>>(g));
  detail::framework::stamp_result(st->version, st->graph_state, g);
  return detail::triangle_delta_access::make(std::move(st));
}

template <typename vertex_t, typename edge_t, typename weight_t>
triangle_delta::stats triangle_delta_update(const resources& res,
                                            graph<vertex_t, edge_t, weight_t>& g,
                                            const edge_batch_view<vertex_t, weight_t>& batch,
                                            triangle_delta::result& r) {
  using problem_t = detail::triangle_delta_problem<vertex_t, edge_t, weight_t>;
  return detail::framework::update_one<problem_t>(res, g, batch, r);
}

template <typename vertex_t, typename edge_t, typename weight_t>
std::unique_ptr<update_participant<vertex_t, edge_t, weight_t>> make_triangle_delta_participant(
    triangle_delta::result& r, triangle_delta::stats& out) {
  using problem_t = triangle_delta_problem<vertex_t, edge_t, weight_t>;
  return framework::make_participant<problem_t>(out, r);
}

// Explicit instantiations (PLAN Section 4.4.3).
#define DYNG_INSTANTIATE_TRIANGLE_DELTA(V, E, W)                                                  \
  template class triangle_delta_problem<V, E, W>;                                                 \
  template std::unique_ptr<update_participant<V, E, W>> make_triangle_delta_participant<V, E, W>( \
      triangle_delta::result&, triangle_delta::stats&);                                           \
  template triangle_delta::result triangle_delta_compute<V, E, W>(                                \
      const resources&, const graph<V, E, W>&, const triangle_delta::options&);                   \
  template triangle_delta::stats triangle_delta_update<V, E, W>(                                  \
      const resources&, graph<V, E, W>&, const edge_batch_view<V, W>&, triangle_delta::result&);
DYNG_FOR_EACH_GRAPH_TYPE(DYNG_INSTANTIATE_TRIANGLE_DELTA)
#undef DYNG_INSTANTIATE_TRIANGLE_DELTA

}  // namespace dyng::detail
