// SPDX-FileCopyrightText: 2026 The dynG Authors
// SPDX-License-Identifier: Apache-2.0
/**
 * @file triangle_delta.cpp
 * @brief triangle_delta: argument validation, the result, compute() and update() through the
 *        framework's enactors, the hooks of the problem, and the explicit instantiations (PLAN
 *        Section 4.8, file 4; first generated by scripts/new_algorithm.py). TEACHING MATERIAL.
 */
#include "algorithms/triangle_delta/problem.hpp"
#include "framework/composition.hpp"
#include "framework/context.hpp"
#include "framework/enactor.hpp"
#include "framework/views.hpp"
#include "graph/device_graph.hpp"
#include "graph/graph_impl.hpp"
#include "graph/instantiate.hpp"
#include "graph/normalized_batch.hpp"
#include "graph/structural_change.hpp"

#include <dyng/config.hpp>
#include <dyng/core/backend.hpp>
#include <dyng/core/error.hpp>
#include <dyng/core/memory.hpp>
#include <dyng/triangle_delta.hpp>
#include <dyng/update.hpp>

#include <algorithm>
#include <cstddef>
#include <cstdint>
#include <memory>
#include <string>
#include <utility>
#include <vector>

namespace dyng::detail {

namespace {

/// Throws not_supported_error unless the backend of `res` is built (triangle_delta implements
/// all three).
void expect_backend(const resources& res, const char* function) {
  const backend b = res.get_backend();
  if (!backend_available(b)) {
    throw not_supported_error(concat_message("dyng: ", function, ": the ", to_string(b),
                                             " backend is not available in this build"));
  }
}

/// Throws stale_result_error for a poisoned result.
void expect_not_poisoned(const triangle_delta_state& st, const char* function) {
  if (st.poisoned) {
    throw stale_result_error(concat_message(
        "dyng: ", function, ": a failed update left this result unusable; recompute it"));
  }
}

/// The state of a result, or invalid_argument_error for a moved-from one.
template <typename state_t>
state_t& checked(state_t* st, const char* function) {
  DYNG_EXPECTS(st != nullptr, function, ": the result was moved from");
  expect_not_poisoned(*st, function);
  return *st;
}

/// The graph requirements (PLAN Section 5.1): an undirected simple graph with sorted rows (the
/// counts intersect sorted rows).
template <typename graph_t>
void expect_requirements(const graph_t& g, const char* function) {
  const graph_properties& p = g.properties();
  DYNG_EXPECTS(!p.directed && p.order == row_order::sorted &&
                   p.parallel_edges == multi_edges::forbid,
               function,
               ": the graph must be undirected with sorted rows and without parallel edges "
               "(graph_properties::directed = false, order = row_order::sorted, parallel_edges = "
               "multi_edges::forbid)");
}

/// One change list: the undirected edges (u, v), u < v, of `changes`, sorted, without repeats
/// (an undirected graph lists both directions of every edge; self-loops close no triangle).
template <typename vertex_t, typename change_t>
void undirected_list(const std::vector<change_t>& changes,
                     std::vector<std::pair<vertex_t, vertex_t>>& out) {
  out.clear();
  for (const change_t& c : changes) {
    if (c.source != c.target) {
      out.emplace_back(std::min(c.source, c.target), std::max(c.source, c.target));
    }
  }
  std::sort(out.begin(), out.end());
  out.erase(std::unique(out.begin(), out.end()), out.end());
}

}  // namespace

triangle_delta_state& triangle_delta_access::state(triangle_delta::result& r) {
  DYNG_EXPECTS(r.impl_ != nullptr, "triangle_delta: the result was moved from");
  return *r.impl_;
}

const triangle_delta_state& triangle_delta_access::state(const triangle_delta::result& r) {
  DYNG_EXPECTS(r.impl_ != nullptr, "triangle_delta: the result was moved from");
  return *r.impl_;
}

triangle_delta::result triangle_delta_access::make(std::unique_ptr<triangle_delta_state> st) {
  return triangle_delta::result(std::move(st));
}

// ------------------------------------------------------------------------------------------------
// The problem
// ------------------------------------------------------------------------------------------------

template <typename vertex_t, typename edge_t, typename weight_t>
std::pair<const triangle_delta_engine<vertex_t, edge_t>*, triangle_delta_graph<vertex_t, edge_t>>
triangle_delta_problem<vertex_t, edge_t, weight_t>::bind(framework::context& ctx,
                                                         const container_type& g) const {
  triangle_delta_graph<vertex_t, edge_t> view;
  view.num_vertices = static_cast<std::int64_t>(g.num_vertices());
  if (ctx.on_cuda()) {
#if DYNG_HAS_CUDA
    // The resident device copy (uploaded on first use per graph state); out-edges only.
    const device_graph<vertex_t, edge_t, weight_t>& d = graph_access::device_out(ctx.res(), g);
    view.offsets = d.out_row_ptr.data();
    view.neighbors = d.out_col_ind.data();
    return {&triangle_delta_cuda_engine<vertex_t, edge_t>(), view};
#else
    throw not_supported_error("dyng: triangle_delta: the cuda backend is not built");
#endif
  }
  const csr_view<vertex_t, edge_t, weight_t> out = graph_access::out_view(g);
  view.offsets = out.row_ptr.data();
  view.neighbors = out.col_ind.data();
  const engine_type* engine = ctx.get_backend() == backend::openmp
                                  ? &triangle_delta_openmp_engine<vertex_t, edge_t>()
                                  : &triangle_delta_sequential_engine<vertex_t, edge_t>();
  return {engine, view};
}

template <typename vertex_t, typename edge_t, typename weight_t>
void triangle_delta_problem<vertex_t, edge_t, weight_t>::begin_update(framework::context& ctx,
                                                                      old_graph g,
                                                                      const requested& /*batch*/) {
  expect_backend(ctx.res(), "triangle_delta::update");
  graph_access::expect_placement(ctx.res(), g.get(), "triangle_delta::update");
  expect_not_poisoned(*state_, "triangle_delta::update");
  expect_requirements(g.get(), "triangle_delta::update");
  framework::expect_current_result("triangle_delta::update", state_->version, state_->graph_state,
                                   g.get());
  ws_.emplace(ctx.lease_workspace<workspace_type>());
}

template <typename vertex_t, typename edge_t, typename weight_t>
void triangle_delta_problem<vertex_t, edge_t, weight_t>::normalize(framework::context& /*ctx*/,
                                                                   old_graph g,
                                                                   const requested& batch) {
  workspace_type& ws = ws_->get();
  if (batch.normalized != nullptr) {
    // Set semantics: the framework normalized the batch once for everybody (ADR 0020).
    undirected_list(batch.normalized->deletions, ws.deletions);
    undirected_list(batch.normalized->insertions, ws.insertions);
    return;
  }
  // Other semantics: the net change of the edge set, computed on G_t without applying the batch.
  const container_type& graph = g.get();
  compute_structural_change(graph_access::out_view(graph), batch.edges, graph.properties(),
                            ws.change);
  undirected_list(ws.change.deletions, ws.deletions);
  undirected_list(ws.change.insertions, ws.insertions);
}

template <typename vertex_t, typename edge_t, typename weight_t>
void triangle_delta_problem<vertex_t, edge_t, weight_t>::count(framework::context& ctx,
                                                               old_graph g, frontier_type& /*f*/,
                                                               framework::sign /*s*/,
                                                               ownership_type /*rule*/) {
  // count(-) on G_t: the triangles the deleted edges destroy (before the commit, invariant I1).
  const auto [engine, view] = bind(ctx, g.get());
  removed_ = engine->count_owned(ctx.res(), view, ws_->get().deletions, ws_->get());
}

template <typename vertex_t, typename edge_t, typename weight_t>
void triangle_delta_problem<vertex_t, edge_t, weight_t>::count(framework::context& ctx,
                                                               new_graph g, frontier_type& /*f*/,
                                                               framework::sign /*s*/,
                                                               ownership_type /*rule*/) {
  const auto [engine, view] = bind(ctx, g.get());
  if (computing_) {
    added_ = engine->count_all(ctx.res(), view, ws_->get());  // compute(): every triangle
    return;
  }
  // count(+) on G_{t+1}: the triangles the inserted edges create.
  added_ = engine->count_owned(ctx.res(), view, ws_->get().insertions, ws_->get());
}

template <typename vertex_t, typename edge_t, typename weight_t>
void triangle_delta_problem<vertex_t, edge_t, weight_t>::finalize(framework::context& /*ctx*/,
                                                                  stats_type& stats) {
  if (computing_) {
    state_->count = added_;
    return;
  }
  // Every destroyed triangle was counted in the old count (invariant I7: never wrap around).
  if (removed_ > state_->count) {
    DYNG_FAIL("triangle_delta::update: ", removed_, " triangles removed from a count of ",
              state_->count);
  }
  const std::uint64_t before = state_->count;
  state_->count = before - removed_ + added_;
  const workspace_type& ws = ws_->get();
  stats.affected = state_->count != before ? 1 : 0;
  stats.deletions = static_cast<std::int64_t>(ws.deletions.size());
  stats.insertions = static_cast<std::int64_t>(ws.insertions.size());
  stats.frontier_visits = stats.deletions + stats.insertions;
  stats.triangles_removed = removed_;
  stats.triangles_added = added_;
}

template <typename vertex_t, typename edge_t, typename weight_t>
void triangle_delta_problem<vertex_t, edge_t, weight_t>::end_update(framework::context& /*ctx*/,
                                                                    new_graph g,
                                                                    const stats_type& /*stats*/) {
  framework::stamp_result(state_->version, state_->graph_state, g.get());
  ws_.reset();
}

template <typename vertex_t, typename edge_t, typename weight_t>
void triangle_delta_problem<vertex_t, edge_t, weight_t>::reset(framework::context& ctx) {
  computing_ = true;
  ws_.emplace(ctx.lease_workspace<workspace_type>());
}

}  // namespace dyng::detail

// ------------------------------------------------------------------------------------------------
// The public functions
// ------------------------------------------------------------------------------------------------

namespace dyng::triangle_delta {

result::result(std::unique_ptr<detail::triangle_delta_state> state) noexcept
    : impl_(std::move(state)) {}
result::result(result&& other) noexcept = default;
result& result::operator=(result&& other) noexcept = default;
result::~result() = default;

std::uint64_t result::count() const {
  return detail::checked(impl_.get(), "triangle_delta::result::count").count;
}

const options& result::get_options() const {
  return detail::checked(impl_.get(), "triangle_delta::result::get_options").opt;
}

void result::set_options(const options& opt) {
  auto& st = detail::checked(impl_.get(), "triangle_delta::result::set_options");
  st.opt = opt;
}

std::uint64_t result::graph_version() const noexcept {
  return impl_ == nullptr ? 0 : impl_->version;
}

memory_space result::space() const noexcept {
  return memory_space::host;
}

result result::clone(const resources& res) const {
  const auto& st = detail::checked(impl_.get(), "triangle_delta::result::clone");
  detail::expect_backend(res, "triangle_delta::result::clone");
  return result(std::make_unique<detail::triangle_delta_state>(st));
}

}  // namespace dyng::triangle_delta

namespace dyng::detail {

// compute() and update() behind the public wrappers of the header (which static_assert the
// supported graph types).
template <typename vertex_t, typename edge_t, typename weight_t>
triangle_delta::result triangle_delta_compute(const resources& res,
                                              const graph<vertex_t, edge_t, weight_t>& g,
                                              const triangle_delta::options& opt) {
  using problem_t = detail::triangle_delta_problem<vertex_t, edge_t, weight_t>;
  detail::expect_backend(res, "triangle_delta::compute");
  detail::graph_access::expect_placement(res, g, "triangle_delta::compute");
  expect_requirements(g, "triangle_delta::compute");
  const detail::framework::hook_stages& names = detail::framework::stages_of<problem_t>();
  scoped_stage stage(res, names.compute);
  auto st = std::make_unique<detail::triangle_delta_state>();
  st->opt = opt;
  {
    problem_t p(*st);
    detail::framework::context ctx(res, problem_t::name);
    detail::framework::static_enactor<problem_t> enactor(p);
    (void)enactor.run(ctx, detail::framework::new_view<graph<vertex_t, edge_t, weight_t>>(g));
  }
  detail::framework::stamp_result(st->version, st->graph_state, g);
  return detail::triangle_delta_access::make(std::move(st));
}

template <typename vertex_t, typename edge_t, typename weight_t>
triangle_delta::stats triangle_delta_update(const resources& res,
                                            graph<vertex_t, edge_t, weight_t>& g,
                                            const edge_batch_view<vertex_t, weight_t>& batch,
                                            triangle_delta::result& r) {
  using problem_t = detail::triangle_delta_problem<vertex_t, edge_t, weight_t>;
  return detail::framework::update_one<problem_t>(res, g, batch, r);
}

template <typename vertex_t, typename edge_t, typename weight_t>
std::unique_ptr<update_participant<vertex_t, edge_t, weight_t>> make_triangle_delta_participant(
    triangle_delta::result& r, triangle_delta::stats& out) {
  using problem_t = triangle_delta_problem<vertex_t, edge_t, weight_t>;
  return framework::make_participant<problem_t>(out, r);
}

// Explicit instantiations (PLAN Section 4.4.3).
#define DYNG_INSTANTIATE_TRIANGLE_DELTA(V, E, W)                                    \
  template class triangle_delta_problem<V, E, W>;                                   \
  template std::unique_ptr<update_participant<V, E, W>>                             \
  make_triangle_delta_participant<V, E, W>(triangle_delta::result&,                 \
                                           triangle_delta::stats&);                 \
  template triangle_delta::result triangle_delta_compute<V, E, W>(                  \
      const resources&, const graph<V, E, W>&, const triangle_delta::options&);     \
  template triangle_delta::stats triangle_delta_update<V, E, W>(                    \
      const resources&, graph<V, E, W>&, const edge_batch_view<V, W>&,              \
      triangle_delta::result&);
DYNG_FOR_EACH_GRAPH_TYPE(DYNG_INSTANTIATE_TRIANGLE_DELTA)
#undef DYNG_INSTANTIATE_TRIANGLE_DELTA

}  // namespace dyng::detail
