// SPDX-FileCopyrightText: 2026 The dynG Authors
// SPDX-License-Identifier: Apache-2.0
/**
 * @file dynamic_bfs.cpp
 * @brief dynamic_bfs: argument validation, the result, compute() and update() through the
 *        framework's enactors, the hooks of the problem, and the explicit instantiations
 *        (generated by scripts/new_algorithm.py; PLAN Section 4.8, file 4).
 */
#include "algorithms/dynamic_bfs/problem.hpp"
#include "core/budget_counters.hpp"
#include "framework/composition.hpp"
#include "framework/context.hpp"
#include "framework/enactor.hpp"
#include "framework/views.hpp"
#include "graph/graph_impl.hpp"
#include "graph/instantiate.hpp"

#include <dyng/core/backend.hpp>
#include <dyng/core/error.hpp>
#include <dyng/core/memory.hpp>
#include <dyng/dynamic_bfs.hpp>
#include <dyng/update.hpp>

#include <algorithm>
#include <cstddef>
#include <cstdint>
#include <memory>
#include <string>
#include <utility>

namespace dyng::detail {

namespace {

/// The backends of the manifest that this algorithm implements.
bool implemented(backend b) {
  return b == backend::sequential || b == backend::openmp;
}

/// Throws not_supported_error unless the backend of `res` is implemented and built.
void expect_backend(const resources& res, const char* function) {
  const backend b = res.get_backend();
  if (!implemented(b) || !backend_available(b)) {
    throw not_supported_error(concat_message("dyng: ", function, ": the ", to_string(b),
                                             " backend is not available for "
                                             "dynamic_bfs (available: sequential",
                                             backend_available(backend::openmp) ? ", openmp" : "",
                                             ")"));
  }
}

/// Throws stale_result_error for a poisoned result.
void expect_not_poisoned(const dynamic_bfs_state& st, const char* function) {
  if (st.poisoned) {
    throw stale_result_error(concat_message(
        "dyng: ", function, ": a failed update left this result unusable; recompute it"));
  }
}

/// The state of a result, or invalid_argument_error for a moved-from one.
template <typename state_t>
state_t& checked(state_t* st, const char* function) {
  DYNG_EXPECTS(st != nullptr, function, ": the result was moved from");
  expect_not_poisoned(*st, function);
  return *st;
}

}  // namespace

dynamic_bfs_state& dynamic_bfs_access::state(dynamic_bfs::result& r) {
  DYNG_EXPECTS(r.impl_ != nullptr, "dynamic_bfs: the result was moved from");
  return *r.impl_;
}

const dynamic_bfs_state& dynamic_bfs_access::state(const dynamic_bfs::result& r) {
  DYNG_EXPECTS(r.impl_ != nullptr, "dynamic_bfs: the result was moved from");
  return *r.impl_;
}

dynamic_bfs::result dynamic_bfs_access::make(std::unique_ptr<dynamic_bfs_state> st) {
  return dynamic_bfs::result(std::move(st));
}

void dynamic_bfs_workspace::reserve(std::size_t n) {
  if (queue.capacity() < n || before.capacity() < n) {
    note_reservation();  // invariant I9: a reserving run (core/budget_counters.hpp)
    queue.reserve(n);
    before.reserve(n);
  }
}

std::size_t dynamic_bfs_workspace::bytes() const noexcept {
  return (queue.capacity() + before.capacity()) * sizeof(std::int64_t);
}

// ------------------------------------------------------------------------------------------------
// The problem
// ------------------------------------------------------------------------------------------------

template <typename vertex_t, typename edge_t, typename weight_t>
void dynamic_bfs_problem<vertex_t, edge_t, weight_t>::begin_update(framework::context& ctx,
                                                                   old_graph g,
                                                                   const requested& /*batch*/) {
  expect_backend(ctx.res(), "dynamic_bfs::update");
  graph_access::expect_placement(ctx.res(), g.get(), "dynamic_bfs::update");
  expect_not_poisoned(*state_, "dynamic_bfs::update");
  framework::expect_current_result("dynamic_bfs::update", state_->version, state_->graph_state,
                                   g.get());
}

template <typename vertex_t, typename edge_t, typename weight_t>
void dynamic_bfs_problem<vertex_t, edge_t, weight_t>::resume(framework::context& ctx, new_graph g,
                                                             const applied& /*applied*/) {
  const auto n = static_cast<std::size_t>(g->num_vertices());
  ws_.emplace(ctx.lease_workspace<dynamic_bfs_workspace>());
  (*ws_)->reserve(n);
  if (state_->levels.capacity() < n) {
    note_reservation();  // the result grows with the graph (invariant I9)
  }
  state_->levels.resize(n, -1);  // new vertices start unreached
  (*ws_)->before.assign(state_->levels.begin(), state_->levels.end());
}

template <typename vertex_t, typename edge_t, typename weight_t>
void dynamic_bfs_problem<vertex_t, edge_t, weight_t>::end_update(framework::context& /*ctx*/,
                                                                 new_graph g,
                                                                 const stats_type& /*stats*/) {
  framework::stamp_result(state_->version, state_->graph_state, g.get());
  ws_.reset();
}

template <typename vertex_t, typename edge_t, typename weight_t>
void dynamic_bfs_problem<vertex_t, edge_t, weight_t>::solve(framework::context& ctx,
                                                            const container_type& g) {
  if (!ws_) {
    ws_.emplace(ctx.lease_workspace<dynamic_bfs_workspace>());
    (*ws_)->reserve(static_cast<std::size_t>(g.num_vertices()));
  }
  const auto out = graph_access::out_view(g);
  if (ctx.res().get_backend() == backend::openmp) {
    dynamic_bfs_openmp(ctx.res(), out, state_->opt.source, state_->levels, ws_->get());
    return;
  }
  dynamic_bfs_sequential(out, state_->opt.source, state_->levels, ws_->get());
}

template <typename vertex_t, typename edge_t, typename weight_t>
void dynamic_bfs_problem<vertex_t, edge_t, weight_t>::loop(framework::context& ctx, new_graph g,
                                                           frontier_type& /*in*/,
                                                           frontier_type& /*out*/) {
  // TODO(dynamic_bfs): propagate from the frontier only (incremental Step 2).
  solve(ctx, g.get());
}

template <typename vertex_t, typename edge_t, typename weight_t>
void dynamic_bfs_problem<vertex_t, edge_t, weight_t>::seed_static(framework::context& /*ctx*/,
                                                                  new_graph /*g*/,
                                                                  frontier_type& /*f*/) {}

template <typename vertex_t, typename edge_t, typename weight_t>
void dynamic_bfs_problem<vertex_t, edge_t, weight_t>::finalize(framework::context& /*ctx*/,
                                                               stats_type& stats) {
  if (computing_) {
    return;
  }
  const std::vector<std::int64_t>& before = (*ws_)->before;
  std::int64_t changed = 0;
  for (std::size_t v = 0; v < state_->levels.size(); ++v) {
    changed += (v >= before.size() || before[v] != state_->levels[v]) ? 1 : 0;
  }
  stats.affected = changed;
  stats.fallback_used = true;  // the placeholder recomputed (PLAN Section 4.8, "start green")
}

template <typename vertex_t, typename edge_t, typename weight_t>
void dynamic_bfs_problem<vertex_t, edge_t, weight_t>::reset(framework::context& /*ctx*/) {
  computing_ = true;
}

}  // namespace dyng::detail

// ------------------------------------------------------------------------------------------------
// The public functions
// ------------------------------------------------------------------------------------------------

namespace dyng::dynamic_bfs {

result::result(std::unique_ptr<detail::dynamic_bfs_state> state) noexcept
    : impl_(std::move(state)) {}
result::result(result&& other) noexcept = default;
result& result::operator=(result&& other) noexcept = default;
result::~result() = default;

array_view<const std::int64_t> result::levels() const {
  const auto& st = detail::checked(impl_.get(), "dynamic_bfs::result::levels");
  return host_view(st.levels);
}

const options& result::get_options() const {
  return detail::checked(impl_.get(), "dynamic_bfs::result::get_options").opt;
}

void result::set_options(const options& opt) {
  auto& st = detail::checked(impl_.get(), "dynamic_bfs::result::set_options");
  DYNG_EXPECTS(opt.source == st.opt.source,
               "dynamic_bfs::result::set_options: the source is fixed at compute()");
  st.opt = opt;
}

std::uint64_t result::graph_version() const noexcept {
  return impl_ == nullptr ? 0 : impl_->version;
}

memory_space result::space() const noexcept {
  return memory_space::host;
}

result result::clone(const resources& res) const {
  const auto& st = detail::checked(impl_.get(), "dynamic_bfs::result::clone");
  detail::expect_backend(res, "dynamic_bfs::result::clone");
  return result(std::make_unique<detail::dynamic_bfs_state>(st));
}

}  // namespace dyng::dynamic_bfs

namespace dyng::detail {

// compute() and update() behind the public wrappers of the header (which static_assert the
// supported graph types).
template <typename vertex_t, typename edge_t, typename weight_t>
dynamic_bfs::result dynamic_bfs_compute(const resources& res,
                                        const graph<vertex_t, edge_t, weight_t>& g,
                                        const dynamic_bfs::options& opt) {
  using problem_t = detail::dynamic_bfs_problem<vertex_t, edge_t, weight_t>;
  detail::expect_backend(res, "dynamic_bfs::compute");
  detail::graph_access::expect_placement(res, g, "dynamic_bfs::compute");
  DYNG_EXPECTS(opt.source >= 0 && opt.source < static_cast<std::int64_t>(g.num_vertices()),
               "dynamic_bfs::compute: the source ", opt.source, " is not a vertex of the graph (",
               g.num_vertices(), " vertices)");
  const detail::framework::hook_stages& names = detail::framework::stages_of<problem_t>();
  scoped_stage stage(res, names.compute);
  auto st = std::make_unique<detail::dynamic_bfs_state>();
  st->opt = opt;
  problem_t p(*st);
  detail::framework::context ctx(res, problem_t::name);
  detail::framework::static_enactor<problem_t> enactor(p);
  (void)enactor.run(ctx, detail::framework::new_view<graph<vertex_t, edge_t, weight_t>>(g));
  detail::framework::stamp_result(st->version, st->graph_state, g);
  return detail::dynamic_bfs_access::make(std::move(st));
}

template <typename vertex_t, typename edge_t, typename weight_t>
dynamic_bfs::stats dynamic_bfs_update(const resources& res, graph<vertex_t, edge_t, weight_t>& g,
                                      const edge_batch_view<vertex_t, weight_t>& batch,
                                      dynamic_bfs::result& r) {
  using problem_t = detail::dynamic_bfs_problem<vertex_t, edge_t, weight_t>;
  return detail::framework::update_one<problem_t>(res, g, batch, r);
}

template <typename vertex_t, typename edge_t, typename weight_t>
std::unique_ptr<update_participant<vertex_t, edge_t, weight_t>> make_dynamic_bfs_participant(
    dynamic_bfs::result& r, dynamic_bfs::stats& out) {
  using problem_t = dynamic_bfs_problem<vertex_t, edge_t, weight_t>;
  return framework::make_participant<problem_t>(out, r);
}

// Explicit instantiations (PLAN Section 4.4.3).
#define DYNG_INSTANTIATE_DYNAMIC_BFS(V, E, W)                                                  \
  template class dynamic_bfs_problem<V, E, W>;                                                 \
  template std::unique_ptr<update_participant<V, E, W>> make_dynamic_bfs_participant<V, E, W>( \
      dynamic_bfs::result&, dynamic_bfs::stats&);                                              \
  template dynamic_bfs::result dynamic_bfs_compute<V, E, W>(                                   \
      const resources&, const graph<V, E, W>&, const dynamic_bfs::options&);                   \
  template dynamic_bfs::stats dynamic_bfs_update<V, E, W>(                                     \
      const resources&, graph<V, E, W>&, const edge_batch_view<V, W>&, dynamic_bfs::result&);
DYNG_FOR_EACH_GRAPH_TYPE(DYNG_INSTANTIATE_DYNAMIC_BFS)
#undef DYNG_INSTANTIATE_DYNAMIC_BFS

}  // namespace dyng::detail
