// SPDX-FileCopyrightText: 2026 The dynG Authors
// SPDX-License-Identifier: Apache-2.0
/**
 * @file dynamic_bfs.cpp
 * @brief dynamic_bfs: argument validation, the result, compute() and update() through the
 *        framework's enactors, the hooks of the problem, and the explicit instantiations (PLAN
 *        Section 4.8, file 4; first generated by scripts/new_algorithm.py). TEACHING MATERIAL.
 *
 * The hooks below only decide WHAT happens WHEN and bind the arrays; every pass is the engine's
 * (engine.hpp), so this file is the same for the three backends.
 */
#include "algorithms/dynamic_bfs/problem.hpp"
#include "core/budget_counters.hpp"
#include "core/cuda_runtime.hpp"
#include "framework/composition.hpp"
#include "framework/context.hpp"
#include "framework/enactor.hpp"
#include "framework/views.hpp"
#include "graph/device_graph.hpp"
#include "graph/graph_impl.hpp"
#include "graph/instantiate.hpp"

#include <dyng/config.hpp>
#include <dyng/core/backend.hpp>
#include <dyng/core/buffer.hpp>
#include <dyng/core/error.hpp>
#include <dyng/core/memory.hpp>
#include <dyng/dynamic_bfs.hpp>
#include <dyng/update.hpp>

#if DYNG_HAS_CUDA
#include "util/device_fill.hpp"
#endif

#include <algorithm>
#include <cstddef>
#include <cstdint>
#include <memory>
#include <string>
#include <utility>

namespace dyng::detail {

namespace {

/// Throws not_supported_error unless the backend of `res` is built (dynamic_bfs implements all
/// three).
void expect_backend(const resources& res, const char* function) {
  const backend b = res.get_backend();
  if (!backend_available(b)) {
    throw not_supported_error(concat_message("dyng: ", function, ": the ", to_string(b),
                                             " backend is not available in this build"));
  }
}

/// Throws stale_result_error for a poisoned result.
void expect_not_poisoned(const dynamic_bfs_state& st, const char* function) {
  if (st.poisoned) {
    throw stale_result_error(concat_message(
        "dyng: ", function, ": a failed update left this result unusable; recompute it"));
  }
}

/// The state of a result, or invalid_argument_error for a moved-from one.
template <typename state_t>
state_t& checked(state_t* st, const char* function) {
  DYNG_EXPECTS(st != nullptr, function, ": the result was moved from");
  expect_not_poisoned(*st, function);
  return *st;
}

/// A result lives in the memory of the backend that computed it: host memory for sequential and
/// openmp, device memory of one device for cuda (clone() moves it).
void expect_result_placement(const resources& res, const dynamic_bfs_state& st,
                             const char* function) {
  const bool on_cuda = res.get_backend() == backend::cuda;
  DYNG_EXPECTS(on_cuda ? (st.space == memory_space::device && st.device == res.device())
                       : st.space == memory_space::host,
               function, ": the result is in ",
               st.space == memory_space::host ? std::string("host memory")
                                              : concat_message("CUDA device ", st.device),
               " but the resources are ", to_string(res.get_backend()),
               "; copy it with r.clone(res)");
}

/// The graph requirement: the seed pulls levels along the in-edges.
template <typename graph_t>
void expect_in_edges(const graph_t& g, const char* function) {
  DYNG_EXPECTS(g.properties().store_transposed || !g.properties().directed, function,
               ": the graph must store its in-edges (graph_properties::store_transposed = true, "
               "the default)");
}

/// Set `count` levels or parents from `first` on to -1 (the memory of `res`).
void fill_unreached(const resources& res, buffer<std::int64_t>& b, std::size_t first,
                    std::size_t count) {
  if (count == 0) {
    return;
  }
  if (b.space() != memory_space::device) {
    std::fill(b.data() + first, b.data() + first + count, std::int64_t{-1});
    return;
  }
#if DYNG_HAS_CUDA
  const scoped_device guard(res.device());
  fill_async(res.stream(), b.data() + first, count, std::int64_t{-1});
#else
  (void)res;
  DYNG_FAIL("dynamic_bfs: device memory in a build without CUDA");
#endif
}

}  // namespace

dynamic_bfs_state& dynamic_bfs_access::state(dynamic_bfs::result& r) {
  DYNG_EXPECTS(r.impl_ != nullptr, "dynamic_bfs: the result was moved from");
  return *r.impl_;
}

const dynamic_bfs_state& dynamic_bfs_access::state(const dynamic_bfs::result& r) {
  DYNG_EXPECTS(r.impl_ != nullptr, "dynamic_bfs: the result was moved from");
  return *r.impl_;
}

dynamic_bfs::result dynamic_bfs_access::make(std::unique_ptr<dynamic_bfs_state> st) {
  return dynamic_bfs::result(std::move(st));
}

// ------------------------------------------------------------------------------------------------
// The problem
// ------------------------------------------------------------------------------------------------

template <typename vertex_t, typename edge_t, typename weight_t>
void dynamic_bfs_problem<vertex_t, edge_t, weight_t>::bind(framework::context& ctx,
                                                           const container_type& g) {
  const resources& res = ctx.res();
  view_ = {};
  view_.num_vertices = static_cast<std::int64_t>(g.num_vertices());
  if (ctx.on_cuda()) {
#if DYNG_HAS_CUDA
    // The resident device copy with its in-edges (built by the commit's prepare step in an
    // update, here on first use in compute()).
    const device_graph<vertex_t, edge_t, weight_t>& d = graph_access::device(res, g);
    view_.out_offsets = d.out_row_ptr.data();
    view_.out_targets = d.out_col_ind.data();
    view_.in_offsets = d.in_row_ptr.data();
    view_.in_sources = d.in_col_ind.data();
    engine_ = &dynamic_bfs_cuda_engine<vertex_t, edge_t>();
#else
    throw not_supported_error("dyng: dynamic_bfs: the cuda backend is not built");
#endif
    return;
  }
  // The host CSR; an undirected graph is stored symmetric, so its out-edges are its in-edges.
  const graph_view<vertex_t, edge_t, weight_t> v = graph_access::view(res, g);
  const csr_view<vertex_t, edge_t, weight_t>& in = v.has_transposed ? v.in : v.out;
  view_.out_offsets = v.out.row_ptr.data();
  view_.out_targets = v.out.col_ind.data();
  view_.in_offsets = in.row_ptr.data();
  view_.in_sources = in.col_ind.data();
  engine_ = res.get_backend() == backend::openmp
                ? &dynamic_bfs_openmp_engine<vertex_t, edge_t>()
                : &dynamic_bfs_sequential_engine<vertex_t, edge_t>();
}

template <typename vertex_t, typename edge_t, typename weight_t>
void dynamic_bfs_problem<vertex_t, edge_t, weight_t>::bind_run() {
  run_ = {};
  run_.levels = state_->levels.data();
  run_.parents = state_->parents.data();
  run_.ws = &ws_->get();
}

template <typename vertex_t, typename edge_t, typename weight_t>
void dynamic_bfs_problem<vertex_t, edge_t, weight_t>::begin_update(framework::context& ctx,
                                                                   old_graph g,
                                                                   const requested& /*batch*/) {
  expect_backend(ctx.res(), "dynamic_bfs::update");
  graph_access::expect_placement(ctx.res(), g.get(), "dynamic_bfs::update");
  expect_not_poisoned(*state_, "dynamic_bfs::update");
  expect_result_placement(ctx.res(), *state_, "dynamic_bfs::update");
  expect_in_edges(g.get(), "dynamic_bfs::update");
  framework::expect_current_result("dynamic_bfs::update", state_->version, state_->graph_state,
                                   g.get());
}

template <typename vertex_t, typename edge_t, typename weight_t>
void dynamic_bfs_problem<vertex_t, edge_t, weight_t>::resume(framework::context& ctx, new_graph g,
                                                             const applied& applied) {
  const resources& res = ctx.res();
  const auto n = static_cast<std::size_t>(g->num_vertices());
  const std::size_t old_n = state_->levels.size();
  if (old_n < n) {
    // Vertex growth: the new vertices are unreached (a reserving run, invariant I9).
    note_reservation();
    for (buffer<std::int64_t>* b : {&state_->levels, &state_->parents}) {
      b->set_stream(res.stream());
      b->resize(n);
      fill_unreached(res, *b, old_n, n - old_n);
    }
  }
  applied_ = &applied;
  ws_.emplace(ctx.lease_workspace<dynamic_bfs_workspace<vertex_t>>());
  bind(ctx, g.get());
  bind_run();
  engine_->begin(res, view_, run_, /*snapshot=*/true);
}

template <typename vertex_t, typename edge_t, typename weight_t>
void dynamic_bfs_problem<vertex_t, edge_t, weight_t>::end_update(framework::context& /*ctx*/,
                                                                 new_graph g,
                                                                 const stats_type& /*stats*/) {
  framework::stamp_result(state_->version, state_->graph_state, g.get());
  ws_.reset();
}

template <typename vertex_t, typename edge_t, typename weight_t>
framework::budget dynamic_bfs_problem<vertex_t, edge_t, weight_t>::algorithm_budget(
    framework::context& ctx) const noexcept {
  // On cuda each count the host reads is a synchronization: one per invalidation pass, one for
  // the seed, one per loop round and two in finalize.
  return framework::budget::steady_state(
      ctx.on_cuda() ? run_.invalidation_rounds + run_.iterations + 3 : 0);
}

template <typename vertex_t, typename edge_t, typename weight_t>
void dynamic_bfs_problem<vertex_t, edge_t, weight_t>::identify_affected(framework::context& ctx,
                                                                        new_graph /*g*/,
                                                                        const applied& applied,
                                                                        frontier_type& /*f*/) {
  // applied.delta lists every deletion the batch requested (an absent edge is harmless: its head
  // is not a root unless the edge was its tree edge).
  const apply_delta<vertex_t>& delta = applied.delta;
  engine_->invalidate(ctx.res(), view_, run_, delta.delete_src.data(), delta.delete_dst.data(),
                      static_cast<std::int64_t>(delta.delete_src.size()));
}

template <typename vertex_t, typename edge_t, typename weight_t>
void dynamic_bfs_problem<vertex_t, edge_t, weight_t>::seed(framework::context& ctx, new_graph /*g*/,
                                                           frontier_type& f) {
  const apply_delta<vertex_t>& delta = applied_->delta;
  engine_->seed(ctx.res(), view_, run_, delta.insert_src.data(), delta.insert_dst.data(),
                static_cast<std::int64_t>(delta.insert_src.size()), f);
}

template <typename vertex_t, typename edge_t, typename weight_t>
void dynamic_bfs_problem<vertex_t, edge_t, weight_t>::loop(framework::context& ctx, new_graph /*g*/,
                                                           frontier_type& in, frontier_type& out) {
  engine_->advance(ctx.res(), view_, run_, in, out);
}

template <typename vertex_t, typename edge_t, typename weight_t>
void dynamic_bfs_problem<vertex_t, edge_t, weight_t>::finalize(framework::context& ctx,
                                                               stats_type& stats) {
  const std::int64_t affected = engine_->finish(ctx.res(), view_, run_, !computing_);
  stats.affected = affected;
  stats.iterations = run_.iterations;
  stats.frontier_visits = run_.frontier_visits;
  stats.invalidated = run_.invalidated;
  stats.invalidation_rounds = run_.invalidation_rounds;
}

template <typename vertex_t, typename edge_t, typename weight_t>
void dynamic_bfs_problem<vertex_t, edge_t, weight_t>::reset(framework::context& ctx) {
  const resources& res = ctx.res();
  computing_ = true;
  const auto n = static_cast<std::size_t>(graph_->num_vertices());
  state_->levels = buffer<std::int64_t>(res, n);
  state_->parents = buffer<std::int64_t>(res, n);
  state_->space = state_->levels.space();
  state_->device = ctx.on_cuda() ? res.device() : -1;
  ws_.emplace(ctx.lease_workspace<dynamic_bfs_workspace<vertex_t>>());
  bind(ctx, *graph_);
  bind_run();
  engine_->begin(res, view_, run_, /*snapshot=*/false);
}

template <typename vertex_t, typename edge_t, typename weight_t>
void dynamic_bfs_problem<vertex_t, edge_t, weight_t>::seed_static(framework::context& ctx,
                                                                  new_graph /*g*/,
                                                                  frontier_type& f) {
  engine_->seed_source(ctx.res(), view_, run_, state_->opt.source, f);
}

}  // namespace dyng::detail

// ------------------------------------------------------------------------------------------------
// The public functions
// ------------------------------------------------------------------------------------------------

namespace dyng::dynamic_bfs {

result::result(std::unique_ptr<detail::dynamic_bfs_state> state) noexcept
    : impl_(std::move(state)) {}
result::result(result&& other) noexcept = default;
result& result::operator=(result&& other) noexcept = default;
result::~result() = default;

array_view<const std::int64_t> result::levels() const {
  const auto& st = detail::checked(impl_.get(), "dynamic_bfs::result::levels");
  return st.levels.view();
}

const options& result::get_options() const {
  return detail::checked(impl_.get(), "dynamic_bfs::result::get_options").opt;
}

void result::set_options(const options& opt) {
  auto& st = detail::checked(impl_.get(), "dynamic_bfs::result::set_options");
  DYNG_EXPECTS(opt.source == st.opt.source,
               "dynamic_bfs::result::set_options: the source is fixed at compute()");
  st.opt = opt;
}

std::uint64_t result::graph_version() const noexcept {
  return impl_ == nullptr ? 0 : impl_->version;
}

memory_space result::space() const noexcept {
  return impl_ == nullptr ? memory_space::host : impl_->space;
}

result result::clone(const resources& res) const {
  const auto& st = detail::checked(impl_.get(), "dynamic_bfs::result::clone");
  detail::expect_backend(res, "dynamic_bfs::result::clone");
  auto copy = std::make_unique<detail::dynamic_bfs_state>();
  copy->opt = st.opt;
  copy->version = st.version;
  copy->graph_state = st.graph_state;
  const bool to_cuda = res.get_backend() == backend::cuda;
  const std::size_t n = st.levels.size();
  copy->levels = buffer<std::int64_t>(res, n);
  copy->parents = buffer<std::int64_t>(res, n);
  copy->space = copy->levels.space();
  copy->device = to_cuda ? res.device() : -1;
  // A result is complete when the call that produced it returns, so its arrays can be read on
  // any stream; the copy is ordered on the stream of `res` (or of the source's device).
  const stream_ref stream = to_cuda ? res.stream() : stream_ref{};
  const int device = to_cuda ? res.device() : st.device;
  const std::size_t bytes = n * sizeof(std::int64_t);
  if (n > 0) {
    detail::copy_bytes(copy->levels.data(), copy->levels.space(), st.levels.data(),
                       st.levels.space(), bytes, stream, device);
    detail::copy_bytes(copy->parents.data(), copy->parents.space(), st.parents.data(),
                       st.parents.space(), bytes, stream, device);
    if (device >= 0) {
      detail::cuda_synchronize(device, stream);
    }
  }
  return result(std::move(copy));
}

}  // namespace dyng::dynamic_bfs

namespace dyng::detail {

// compute() and update() behind the public wrappers of the header (which static_assert the
// supported graph types).
template <typename vertex_t, typename edge_t, typename weight_t>
dynamic_bfs::result dynamic_bfs_compute(const resources& res,
                                        const graph<vertex_t, edge_t, weight_t>& g,
                                        const dynamic_bfs::options& opt) {
  using problem_t = detail::dynamic_bfs_problem<vertex_t, edge_t, weight_t>;
  detail::expect_backend(res, "dynamic_bfs::compute");
  detail::graph_access::expect_placement(res, g, "dynamic_bfs::compute");
  DYNG_EXPECTS(opt.source >= 0 && opt.source < static_cast<std::int64_t>(g.num_vertices()),
               "dynamic_bfs::compute: the source ", opt.source, " is not a vertex of the graph (",
               g.num_vertices(), " vertices)");
  expect_in_edges(g, "dynamic_bfs::compute");
  const detail::framework::hook_stages& names = detail::framework::stages_of<problem_t>();
  scoped_stage stage(res, names.compute);
  auto st = std::make_unique<detail::dynamic_bfs_state>();
  st->opt = opt;
  {
    problem_t p(*st, g);
    detail::framework::context ctx(res, problem_t::name);
    detail::framework::static_enactor<problem_t> enactor(p);
    (void)enactor.run(ctx, detail::framework::new_view<graph<vertex_t, edge_t, weight_t>>(g));
  }
  if (res.get_backend() == backend::cuda) {
    res.synchronize();  // compute() is synchronous: the last passes wrote the parents
  }
  detail::framework::stamp_result(st->version, st->graph_state, g);
  return detail::dynamic_bfs_access::make(std::move(st));
}

template <typename vertex_t, typename edge_t, typename weight_t>
dynamic_bfs::stats dynamic_bfs_update(const resources& res, graph<vertex_t, edge_t, weight_t>& g,
                                      const edge_batch_view<vertex_t, weight_t>& batch,
                                      dynamic_bfs::result& r) {
  using problem_t = detail::dynamic_bfs_problem<vertex_t, edge_t, weight_t>;
  return detail::framework::update_one<problem_t>(res, g, batch, r);
}

template <typename vertex_t, typename edge_t, typename weight_t>
std::unique_ptr<update_participant<vertex_t, edge_t, weight_t>> make_dynamic_bfs_participant(
    dynamic_bfs::result& r, dynamic_bfs::stats& out) {
  using problem_t = dynamic_bfs_problem<vertex_t, edge_t, weight_t>;
  return framework::make_participant<problem_t>(out, r);
}

// Explicit instantiations (PLAN Section 4.4.3).
#define DYNG_INSTANTIATE_DYNAMIC_BFS(V, E, W)                                                  \
  template class dynamic_bfs_problem<V, E, W>;                                                 \
  template std::unique_ptr<update_participant<V, E, W>> make_dynamic_bfs_participant<V, E, W>( \
      dynamic_bfs::result&, dynamic_bfs::stats&);                                              \
  template dynamic_bfs::result dynamic_bfs_compute<V, E, W>(                                   \
      const resources&, const graph<V, E, W>&, const dynamic_bfs::options&);                   \
  template dynamic_bfs::stats dynamic_bfs_update<V, E, W>(                                     \
      const resources&, graph<V, E, W>&, const edge_batch_view<V, W>&, dynamic_bfs::result&);
DYNG_FOR_EACH_GRAPH_TYPE(DYNG_INSTANTIATE_DYNAMIC_BFS)
DYNG_FOR_EACH_UNWEIGHTED_GRAPH_TYPE(DYNG_INSTANTIATE_DYNAMIC_BFS)
#undef DYNG_INSTANTIATE_DYNAMIC_BFS

}  // namespace dyng::detail
