// SPDX-FileCopyrightText: 2026 The dynG Authors
// SPDX-License-Identifier: Apache-2.0
/**
 * @file openmp.cpp
 * @brief dynamic_bfs: the OpenMP backend (PLAN Section 4.8, file 7; generated by
 *        scripts/new_algorithm.py).
 *
 * TODO(dynamic_bfs): the placeholder runs the sequential backend, so the conformance kit's
 * cross-backend check (C3) holds from the first build; write the parallel version and keep C3
 * green.
 */
#include "algorithms/dynamic_bfs/problem.hpp"
#include "graph/instantiate.hpp"

#include <dyng/core/resources.hpp>
#include <dyng/graph/csr.hpp>

#include <cstdint>
#include <vector>

namespace dyng::detail {

template <typename vertex_t, typename edge_t, typename weight_t>
void dynamic_bfs_openmp(const resources& /*res*/, const csr_view<vertex_t, edge_t, weight_t>& out,
                        std::int64_t source, std::vector<std::int64_t>& levels,
                        dynamic_bfs_workspace& ws) {
  dynamic_bfs_sequential(out, source, levels, ws);
}

#define DYNG_INSTANTIATE(V, E, W)                                                       \
  template void dynamic_bfs_openmp<V, E, W>(const resources&, const csr_view<V, E, W>&, \
                                            std::int64_t, std::vector<std::int64_t>&,   \
                                            dynamic_bfs_workspace&);
DYNG_FOR_EACH_GRAPH_TYPE(DYNG_INSTANTIATE)
#undef DYNG_INSTANTIATE

}  // namespace dyng::detail
