// SPDX-FileCopyrightText: 2026 The dynG Authors
// SPDX-License-Identifier: Apache-2.0
/**
 * @file problem.hpp
 * @brief The dynamic_bfs problem on the framework (cpp/src/framework): its hooks, its
 *        state and its workspace (generated by scripts/new_algorithm.py).
 *
 * Template card (PLAN Section 4.5.2; docs/developer/framework.md):
 *
 *     normalize -> prepare -> before_apply -> commit ->
 *     identify_affected -> seed -> { loop until is_converged } -> finalize
 *
 * A fixed-point problem. The placeholder ("start green", PLAN Section 4.8) implements only
 * `loop` (on G_{t+1}: the whole static solve, one call with the internal frontier) and
 * `finalize` (the stats, stats::fallback_used = true), so update() recomputes. To make it
 * incremental: in identify_affected, find the elements the batch invalidates (applied.delta has
 * the effective changes); in seed, put the elements to re-evaluate on the frontier; in loop,
 * propagate from the frontier only; then set fallback_used only when you really recompute.
 *
 * compute() is the static enactor with the same hooks (reset first). Lifecycle members without a
 * stage: begin_update (the checks before anything changes), resume (bind G_{t+1}, grow the
 * result, lease the workspace), end_update (record the graph state), poison.
 */
#pragma once

#include "framework/budgets.hpp"
#include "framework/composition.hpp"
#include "framework/context.hpp"
#include "framework/frontier.hpp"
#include "framework/policies.hpp"
#include "framework/problem.hpp"
#include "framework/views.hpp"
#include "framework/workspace.hpp"

#include <dyng/core/backend.hpp>
#include <dyng/core/resources.hpp>
#include <dyng/dynamic_bfs.hpp>
#include <dyng/graph/csr.hpp>
#include <dyng/graph/graph.hpp>

#include <cstddef>
#include <cstdint>
#include <optional>
#include <string_view>
#include <vector>

namespace dyng::detail {

/// The state behind an dynamic_bfs::result.
struct dynamic_bfs_state {
  dynamic_bfs::options opt;          ///< the options
  std::vector<std::int64_t> levels;  ///< the hop level of every vertex, -1 if unreachable
  std::uint64_t version = 0;         ///< graph version matched
  std::uint64_t graph_state = 0;     ///< graph state matched (ADR 0006, "Graph identity")
  bool poisoned = false;             ///< a failed update left the result unusable
};

/// Access to the state of a result.
struct dynamic_bfs_access {
  /// The state of `r`.
  static dynamic_bfs_state& state(dynamic_bfs::result& r);
  /// The state of `r`.
  static const dynamic_bfs_state& state(const dynamic_bfs::result& r);
  /// A result owning `st`.
  static dynamic_bfs::result make(std::unique_ptr<dynamic_bfs_state> st);
};

/// Scratch space of the engines, leased from the workspace pool of the resources handle (ADR 0015).
struct dynamic_bfs_workspace final : pooled_workspace {
  std::vector<std::int64_t> queue;   ///< the search queue
  std::vector<std::int64_t> before;  ///< the levels before the update (the stats)

  /// Size the arrays for `n` vertices (a reservation when they grow, invariant I9).
  void reserve(std::size_t n);

  /// Bytes of the arrays' capacities.
  [[nodiscard]] std::size_t bytes() const noexcept override;
};

/**
 * @brief The static solve on the sequential backend: hop levels from `source` (breadth-first).
 * @tparam vertex_t Vertex id type.
 * @tparam edge_t   Edge offset type.
 * @tparam weight_t Weight type.
 * @param[in]     out    The out-edges (host).
 * @param[in]     source The source vertex.
 * @param[out]    levels One level per vertex (resized to the vertex count).
 * @param[in,out] ws     The workspace (reserved for the vertex count).
 */
template <typename vertex_t, typename edge_t, typename weight_t>
void dynamic_bfs_sequential(const csr_view<vertex_t, edge_t, weight_t>& out, std::int64_t source,
                            std::vector<std::int64_t>& levels, dynamic_bfs_workspace& ws);

/**
 * @brief The static solve on the OpenMP backend (as dynamic_bfs_sequential()).
 * @tparam vertex_t Vertex id type.
 * @tparam edge_t   Edge offset type.
 * @tparam weight_t Weight type.
 * @param[in]     res    The resources (their thread count).
 * @param[in]     out    The out-edges (host).
 * @param[in]     source The source vertex.
 * @param[out]    levels One level per vertex.
 * @param[in,out] ws     The workspace.
 */
template <typename vertex_t, typename edge_t, typename weight_t>
void dynamic_bfs_openmp(const resources& res, const csr_view<vertex_t, edge_t, weight_t>& out,
                        std::int64_t source, std::vector<std::int64_t>& levels,
                        dynamic_bfs_workspace& ws);

/// The update family of dynamic_bfs.
inline constexpr framework::family dynamic_bfs_family = framework::family::fixed_point;

/**
 * @brief The dynamic_bfs problem (see the file comment).
 * @tparam vertex_t Vertex id type.
 * @tparam edge_t   Edge offset type.
 * @tparam weight_t Weight type.
 */
template <typename vertex_t, typename edge_t, typename weight_t>
class dynamic_bfs_problem final
    : public framework::problem_base<dynamic_bfs_problem<vertex_t, edge_t, weight_t>,
                                     dynamic_bfs_family> {
 public:
  static constexpr std::string_view name = "dynamic_bfs";            ///< stages "<name>.<hook>"
  using container_type = graph<vertex_t, edge_t, weight_t>;          ///< the container
  using stats_type = dynamic_bfs::stats;                             ///< the stats of update()
  using frontier_type = framework::internal_frontier;                ///< frontiers are internal
  using old_graph = framework::old_view<container_type>;             ///< G_t
  using new_graph = framework::new_view<container_type>;             ///< G_{t+1}
  using requested = framework::requested_batch<vertex_t, weight_t>;  ///< the batch before commit
  using applied = framework::applied_batch<vertex_t>;                ///< what the commit did

  /// The problem of one update of `r`.
  explicit dynamic_bfs_problem(dynamic_bfs::result& r)
      : state_(&dynamic_bfs_access::state(r)), target_(&r) {}
  /// The problem of one compute() filling `st`.
  explicit dynamic_bfs_problem(dynamic_bfs_state& st) : state_(&st) {}

  // ---- lifecycle (no stage) ----

  /// The result this problem updates (nullptr for compute()).
  [[nodiscard]] const void* target() const noexcept {
    return target_;
  }
  /// The checks before anything changes: backend, poisoned and stale result.
  void begin_update(framework::context& ctx, old_graph g, const requested& batch);
  /// Bind G_{t+1}: grow the result for new vertices, lease the workspace.
  void resume(framework::context& ctx, new_graph g, const applied& applied);
  /// Record the graph state the result matches; return the workspace.
  void end_update(framework::context& ctx, new_graph g, const stats_type& stats);
  /// Mark the result unusable (a failed algorithm phase).
  void poison() noexcept {
    state_->poisoned = true;
  }
  /// The engines read the out-edges only (the commit need not build the in-edges).
  [[nodiscard]] bool reads_prepared_graph() const noexcept {
    return false;
  }
  /// The budget of the algorithm phase (invariant I9, conformance check C8): nothing allocated
  /// once reserved, no host synchronization.
  [[nodiscard]] framework::budget algorithm_budget(framework::context& /*ctx*/) const noexcept {
    return framework::budget::steady_state(0);
  }

  // ---- Step 2 ----

  /// dynamic_bfs.loop: the placeholder solves G_{t+1} from scratch (one call).
  void loop(framework::context& ctx, new_graph g, frontier_type& in, frontier_type& out);
  /// dynamic_bfs.finalize: the stats (the placeholder sets fallback_used in update()).
  void finalize(framework::context& ctx, stats_type& stats);

  // ---- compute() ----

  /// dynamic_bfs.reset: start the static solve.
  void reset(framework::context& ctx);
  /// dynamic_bfs.seed (static): nothing to seed, the loop solves from the source.
  void seed_static(framework::context& ctx, new_graph g, frontier_type& f);

 private:
  /// The static solve of `g` into the state.
  void solve(framework::context& ctx, const container_type& g);

  dynamic_bfs_state* state_ = nullptr;
  const dynamic_bfs::result* target_ = nullptr;
  bool computing_ = false;
  std::optional<workspace_pool::lease<dynamic_bfs_workspace>> ws_;
};

}  // namespace dyng::detail
