#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 The dynG Authors
# SPDX-License-Identifier: Apache-2.0
"""Regenerate the files that are derived from the algorithm manifests (PLAN Sections 4.2 and 4.8).

The manifests cpp/src/algorithms/<name>/manifest.toml (plus cpp/src/algorithms/planned.toml for the
algorithms whose port has not started) are the one place an algorithm is registered. This script
writes, and with --check verifies, everything derived from them:

  - the algorithm tables of README.md, docs/index.md (the landing page) and
    docs/algorithms/index.md, between the markers <!-- regen:algorithms begin ... --> and
    <!-- regen:algorithms end -->;
  - the per-algorithm block of .github/CODEOWNERS (between "# regen:algorithms begin" and
    "# regen:algorithms end"), from each manifest's `maintainers`;
  - the library's registry table cpp/src/core/registry_table.inc (dyng::algorithms());
  - the conformance kit's registry cpp/tests/conformance/registry.hpp (the tags of every
    algorithm and the includes of their test_traits).

It also checks the registration rules (invariant I8, PLAN Section 4.5.5): every manifest names a
sequential backend first and an oracle kind, its cite keys exist in docs/references.bib, the files
every algorithm has (PLAN Section 4.8) exist, and cpp/src/algorithms/CMakeLists.txt adds exactly
the algorithms that have a manifest.

    python3 scripts/regen.py            # rewrite the generated files
    python3 scripts/regen.py --check    # exit 1 if a generated file is out of date (CI)

Exit status: 0 up to date (or rewritten), 1 out of date (--check), 2 invalid manifests.
"""

from __future__ import annotations

import argparse
import re
import sys
import tomllib
from dataclasses import dataclass, field
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent

FAMILIES = {"fixed_point": "fixed point", "aggregate_delta": "aggregate delta"}
CONTAINERS = ("graph", "hypergraph")
TIERS = ("framework", "custom_engine")
MATURITY = ("experimental", "stable", "deprecated")
DETERMINISM = ("bitwise", "exact_value", "tolerance")
ORACLES = ("compute", "reference")
BACKENDS = {"sequential": "sequential", "openmp": "OpenMP", "cuda": "CUDA"}
REQUIRED = (
    "name",
    "title",
    "computes",
    "paper",
    "since",
    "family",
    "container",
    "tier",
    "maturity",
    "backends",
    "determinism",
    "oracle",
    "graph_requirements",
    "cite",
    "maintainers",
)
NAME = re.compile(r"^[a-z][a-z0-9_]*$")
HANDLE = re.compile(r"^[A-Za-z0-9](?:[A-Za-z0-9-]{0,38})$")
GENERATED = "generated by scripts/regen.py from the manifests; do not edit"
MD_BEGIN = f"<!-- regen:algorithms begin ({GENERATED}) -->"
MD_END = "<!-- regen:algorithms end -->"
CO_BEGIN = f"# regen:algorithms begin ({GENERATED})"
CO_END = "# regen:algorithms end"


class ManifestError(Exception):
    """A manifest breaks a registration rule."""


@dataclass
class Algorithm:
    """One algorithm with a manifest."""

    name: str
    data: dict
    path: Path

    def __getitem__(self, key: str):
        return self.data[key]


@dataclass
class Planned:
    """One algorithm whose port has not started (cpp/src/algorithms/planned.toml)."""

    name: str
    computes: str
    container: str
    family: str
    backends: str
    paper: str
    since: str


@dataclass
class Registry:
    """Every manifest (in add_subdirectory order) and every planned algorithm."""

    algorithms: list[Algorithm] = field(default_factory=list)
    planned: list[Planned] = field(default_factory=list)


def _subdirectories(root: Path) -> list[str]:
    text = (root / "cpp/src/algorithms/CMakeLists.txt").read_text(encoding="utf-8")
    return re.findall(r"^\s*add_subdirectory\(\s*([A-Za-z0-9_]+)\s*\)", text, re.MULTILINE)


def _cite_keys(root: Path) -> set[str]:
    text = (root / "docs/references.bib").read_text(encoding="utf-8")
    return set(re.findall(r"^@\w+\{([^,\s]+),", text, re.MULTILINE))


def _check_manifest(root: Path, algo: Algorithm, keys: set[str]) -> list[str]:
    """The registration rules of one manifest (an empty list when it is valid)."""
    d = algo.data
    problems = [f"missing key `{k}`" for k in REQUIRED if k not in d]
    if problems:
        return problems
    folder = algo.path.parent.name
    if d["name"] != folder or not NAME.match(d["name"]):
        problems.append(f"name `{d['name']}` must be the folder name `{folder}` (snake_case)")
    for key, allowed in (
        ("family", tuple(FAMILIES)),
        ("container", CONTAINERS),
        ("tier", TIERS),
        ("maturity", MATURITY),
        ("determinism", DETERMINISM),
        ("oracle", ORACLES),
    ):
        if d[key] not in allowed:
            problems.append(f"`{key}` is `{d[key]}`; expected one of {', '.join(allowed)}")
    backends = d["backends"]
    if not isinstance(backends, list) or not backends:
        problems.append("`backends` must be a non-empty list")
    else:
        unknown = [b for b in backends if b not in BACKENDS]
        if unknown:
            problems.append(f"unknown backends {unknown}; expected {', '.join(BACKENDS)}")
        if backends[0] != "sequential":
            problems.append(
                "`backends` must start with `sequential`: every algorithm has the sequential "
                "reference backend, its oracle (invariant I8)"
            )
        if len(set(backends)) != len(backends):
            problems.append("`backends` lists a backend twice")
    if d["maturity"] == "stable" and "cuda" not in backends and "no_cuda_reason" not in d:
        problems.append(
            "a `stable` algorithm has a CUDA backend or an accepted written reason "
            "(`no_cuda_reason`)"
        )
    missing = [k for k in d["cite"] if k not in keys]
    if missing:
        problems.append(f"cite keys {missing} are not in docs/references.bib")
    if not d["maintainers"] or any(not HANDLE.match(m) for m in d["maintainers"]):
        problems.append("`maintainers` must list GitHub handles")
    name = d["name"]
    files = [
        f"cpp/include/dyng/{name}.hpp",
        f"cpp/src/algorithms/{name}/CMakeLists.txt",
        f"cpp/src/algorithms/{name}/{name}.cpp",
        f"cpp/src/algorithms/{name}/problem.hpp",
        f"cpp/src/algorithms/{name}/sequential.cpp",
        f"cpp/tests/algorithms/{name}/{name}_traits.hpp",
        f"cpp/tests/algorithms/{name}/{name}_conformance_test.cpp",
        f"docs/algorithms/{name}.md",
    ]
    if "openmp" in backends:
        files.append(f"cpp/src/algorithms/{name}/openmp.cpp")
    if "cuda" in backends:
        files.append(f"cpp/src/algorithms/{name}/cuda.cu")
    problems += [f"missing file {f} (PLAN Section 4.8)" for f in files if not (root / f).is_file()]
    # The manifest must list every backend the folder implements: the registry, the algorithm
    # tables and the conformance kit (which runs the listed backends only) read `backends`.
    for backend, source in (("openmp", "openmp.cpp"), ("cuda", "cuda.cu")):
        if backend not in backends and (root / f"cpp/src/algorithms/{name}/{source}").is_file():
            problems.append(
                f"cpp/src/algorithms/{name}/{source} exists but `backends` does not list "
                f"`{backend}` (the kit would not test it and the registry would misreport it)"
            )
    return problems


def load(root: Path) -> Registry:
    """Read and check every manifest; raise ManifestError listing every problem."""
    keys = _cite_keys(root)
    order = _subdirectories(root)
    found = {
        p.parent.name: p
        for p in sorted((root / "cpp/src/algorithms").glob("*/manifest.toml"))
        if not p.parent.name.startswith("_")
    }
    problems: list[str] = []
    for name in order:
        if name not in found:
            problems.append(
                f"cpp/src/algorithms/CMakeLists.txt adds `{name}`, which has no manifest"
            )
    for name in found:
        if name not in order:
            problems.append(
                f"cpp/src/algorithms/{name}/manifest.toml exists but cpp/src/algorithms/"
                f"CMakeLists.txt has no add_subdirectory({name})"
            )
    reg = Registry()
    for name in [n for n in order if n in found]:
        path = found[name]
        try:
            data = tomllib.loads(path.read_text(encoding="utf-8"))
        except tomllib.TOMLDecodeError as e:
            problems.append(f"{path.relative_to(root)}: {e}")
            continue
        algo = Algorithm(name=name, data=data, path=path)
        problems += [f"{path.relative_to(root)}: {p}" for p in _check_manifest(root, algo, keys)]
        reg.algorithms.append(algo)
    planned_path = root / "cpp/src/algorithms/planned.toml"
    if planned_path.is_file():
        for entry in tomllib.loads(planned_path.read_text(encoding="utf-8")).get("planned", []):
            try:
                reg.planned.append(Planned(**entry))
            except TypeError as e:
                problems.append(f"cpp/src/algorithms/planned.toml: {e}")
                continue
            if entry["name"] in found:
                problems.append(
                    f"cpp/src/algorithms/planned.toml lists `{entry['name']}`, which has a "
                    "manifest: remove the planned entry"
                )
    if problems:
        raise ManifestError("\n".join(problems))
    return reg


# ------------------------------------------------------------------------------------------------
# Rendering
# ------------------------------------------------------------------------------------------------


def _backends(algo: Algorithm) -> str:
    return ", ".join(BACKENDS[b] for b in algo["backends"])


def _table(rows: list[list[str]], header: list[str]) -> str:
    lines = ["| " + " | ".join(header) + " |", "|" + "---|" * len(header)]
    lines += ["| " + " | ".join(r) + " |" for r in rows]
    return "\n".join(lines)


def readme_table(reg: Registry) -> str:
    """The table of README.md (links into docs/)."""
    rows = [
        [
            f"[`{a.name}`](docs/algorithms/{a.name}.md)",
            a["computes"],
            a["container"],
            FAMILIES[a["family"]],
            _backends(a),
            a["maturity"],
            a["paper"],
        ]
        for a in reg.algorithms
    ]
    rows += [
        [
            f"`{p.name}`",
            p.computes,
            p.container,
            p.family,
            p.backends,
            f"planned ({p.since})",
            p.paper,
        ]
        for p in reg.planned
    ]
    header = ["Algorithm", "Computes", "Container", "Family", "Backends", "Status", "Paper"]
    return _table(rows, header)


def landing_table(reg: Registry) -> str:
    """The table of docs/index.md (the landing page)."""
    rows = [
        [
            f"{{doc}}`{a.name} <algorithms/{a.name}>`",
            a["computes"],
            a["container"],
            FAMILIES[a["family"]],
            _backends(a),
            a["maturity"],
            a["paper"],
        ]
        for a in reg.algorithms
    ]
    rows += [
        [
            f"`{p.name}`",
            p.computes,
            p.container,
            p.family,
            p.backends,
            f"planned ({p.since})",
            p.paper,
        ]
        for p in reg.planned
    ]
    header = ["Algorithm", "Computes", "Container", "Family", "Backends", "Status", "Paper"]
    return _table(rows, header)


def index_table(reg: Registry) -> str:
    """The table of docs/algorithms/index.md."""
    rows = [
        [
            f"{{doc}}`{a.name}`",
            a["computes"],
            a["container"],
            FAMILIES[a["family"]],
            _backends(a),
            a["maturity"],
            a["since"],
        ]
        for a in reg.algorithms
    ]
    rows += [
        [f"`{p.name}`", p.computes, p.container, p.family, p.backends, "planned", p.since]
        for p in reg.planned
    ]
    header = ["Algorithm", "Computes", "Container", "Family", "Backends", "Maturity", "Release"]
    return _table(rows, header)


def codeowners_block(reg: Registry) -> str:
    """The per-algorithm block of .github/CODEOWNERS."""
    lines = []
    for a in reg.algorithms:
        owners = " ".join(f"@{m}" for m in a["maintainers"])
        for path in (
            f"/cpp/src/algorithms/{a.name}/",
            f"/cpp/include/dyng/{a.name}.hpp",
            f"/cpp/tests/algorithms/{a.name}/",
            f"/docs/algorithms/{a.name}.md",
        ):
            # At least one space between the path and the owners, however long the path.
            lines.append(f"{path:<35} {owners}")
    return "\n".join(lines)


# The SPDX header of the generated C++ files (split so that `reuse lint` does not read this script's
# string as a header of its own).
HEADER_CPP = (
    "// SPDX-FileCopyrightText: 2026 The dynG Authors\n// SPDX-License-Identifier: Apache-2.0\n"
)


def registry_table(reg: Registry) -> str:
    """cpp/src/core/registry_table.inc: the body of dyng::algorithms() (core/registry.cpp)."""
    out = [
        HEADER_CPP.rstrip("\n"),
        f"// The algorithm registry table ({GENERATED}).",
        "// Included by core/registry.cpp inside make_table(); DYNG_ALGORITHM_<NAME> is defined",
        "// for every algorithm CMake builds (cpp/CMakeLists.txt).",
    ]
    for a in reg.algorithms:
        backends = ", ".join(f"backend::{b}" for b in a["backends"])
        cites = ", ".join(f'"{c}"' for c in a["cite"])
        out += [
            f"#if defined(DYNG_ALGORITHM_{a.name.upper()})",
            "table.push_back(algorithm_info{",
            f'    "{a.name}",',
            f'    "{a["title"]}",',
            f"    algorithm_family::{a['family']},",
            f"    container_kind::{a['container']},",
            f"    maturity_level::{a['maturity']},",
            f"    determinism::{a['determinism']},",
            f"    oracle_kind::{a['oracle']},",
            f"    {{{backends}}},",
            f"    {{{cites}}},",
            "});",
            "#endif",
        ]
    return "\n".join(out) + "\n"


def kit_registry(reg: Registry) -> str:
    """cpp/tests/conformance/registry.hpp: the conformance kit's list of algorithms."""
    tags = "\n".join(f"/// The tag of {a.name}.\nstruct {a.name};" for a in reg.algorithms)
    includes = "\n".join(
        f"#if defined(DYNG_ALGORITHM_{a.name.upper()})\n"
        f'#include "algorithms/{a.name}/{a.name}_traits.hpp"\n'
        "#endif"
        for a in reg.algorithms
    )
    # One short line per algorithm (clang-format keeps them as they are).
    steps = ["using list_0 = type_list<>;"] + [
        f"using list_{i + 1} = append_t<list_{i}, tags::{a.name}>;"
        for i, a in enumerate(reg.algorithms)
    ]
    chain = "\n".join(steps)
    last = f"registry_detail::list_{len(reg.algorithms)}"
    return f"""{HEADER_CPP}// {GENERATED[0].upper() + GENERATED[1:]}.
/**
 * @file registry.hpp
 * @brief The algorithms the conformance kit knows (PLAN Section 8.2): one tag per manifest, and
 *        the test_traits of every algorithm this build contains (DYNG_ALGORITHM_<NAME>, defined by
 *        cpp/tests/CMakeLists.txt for the algorithms CMake builds).
 */
#pragma once

#include "conformance/type_list.hpp"

/// The tags of the algorithms: test_traits<tags::<name>> is an algorithm's traits.
namespace dyng::conformance::tags {{
{tags}
}}  // namespace dyng::conformance::tags

{includes}

namespace dyng::conformance {{

/// The list of the manifests, built one algorithm at a time.
namespace registry_detail {{
{chain}
}}  // namespace registry_detail

/// Every algorithm with a manifest, in the order of cpp/src/algorithms/CMakeLists.txt; the kit
/// keeps those whose test_traits this build defines (registered_algorithms, conformance.hpp).
using manifest_algorithms = {last};

}}  // namespace dyng::conformance
"""


# ------------------------------------------------------------------------------------------------
# Writing and checking
# ------------------------------------------------------------------------------------------------


def _replace_block(text: str, begin: str, end: str, body: str, where: str) -> str:
    start = text.find(begin)
    stop = text.find(end)
    if start < 0 or stop < start:
        raise ManifestError(f"{where}: the markers `{begin}` ... `{end}` are missing")
    return text[: start + len(begin)] + "\n" + body + "\n" + text[stop:]


def outputs(root: Path, reg: Registry) -> dict[Path, str]:
    """Every generated file and its expected content."""
    out: dict[Path, str] = {}
    for rel, body in (
        ("README.md", readme_table(reg)),
        ("docs/index.md", landing_table(reg)),
        ("docs/algorithms/index.md", index_table(reg)),
    ):
        path = root / rel
        out[path] = _replace_block(path.read_text(encoding="utf-8"), MD_BEGIN, MD_END, body, rel)
    path = root / ".github/CODEOWNERS"
    out[path] = _replace_block(
        path.read_text(encoding="utf-8"),
        CO_BEGIN,
        CO_END,
        codeowners_block(reg),
        ".github/CODEOWNERS",
    )
    out[root / "cpp/src/core/registry_table.inc"] = registry_table(reg)
    out[root / "cpp/tests/conformance/registry.hpp"] = kit_registry(reg)
    return out


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("--check", action="store_true", help="fail if a file is out of date")
    parser.add_argument("--root", type=Path, default=REPO, help="repository root (tests)")
    args = parser.parse_args(argv)
    root = args.root.resolve()
    try:
        reg = load(root)
        expected = outputs(root, reg)
    except ManifestError as e:
        print(f"regen.py: invalid manifests:\n{e}", file=sys.stderr)
        return 2
    stale = []
    for path, content in expected.items():
        current = path.read_text(encoding="utf-8") if path.is_file() else None
        if current != content:
            stale.append(path)
            if not args.check:
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_text(content, encoding="utf-8")
    rel = [str(p.relative_to(root)) for p in stale]
    if args.check:
        if stale:
            print(
                "regen.py --check: out of date (run `python3 scripts/regen.py`): " + ", ".join(rel),
                file=sys.stderr,
            )
            return 1
        print(
            f"regen.py: {len(expected)} generated files up to date "
            f"({len(reg.algorithms)} algorithms)"
        )
        return 0
    print("regen.py: " + ("rewrote " + ", ".join(rel) if rel else "everything up to date"))
    return 0


if __name__ == "__main__":
    sys.exit(main())
