#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 The dynG Authors
# SPDX-License-Identifier: Apache-2.0
"""The public C++ API snapshot: a listing of every public declaration, and its check (the 0.1 API
freeze, PLAN Sections 5.9 and 11.2 M3; ADR 0023).

    ci/api_snapshot.py [--xml build/doxygen/xml]            # check against the baseline
    ci/api_snapshot.py --update [--xml build/doxygen/xml]   # rewrite the baseline
    ci/api_snapshot.py --print  [--xml build/doxygen/xml]   # print the listing

The listing is generated from the Doxygen XML of the public headers (ci/docs.sh writes it; the
Doxyfile excludes dyng::detail), so it contains what a user can name: for every header, its
classes and structs (template parameters, bases, public members with their types, default
arguments and member initializers), its enumerations with their values, its functions,
variables, type aliases and macros, in declaration order. Documentation text, line numbers and
function bodies are not part of it, so a comment edit never changes the listing; a changed
signature, default value, enumerator, field or a new or removed entity does.

The baseline is cpp/tests/api/api_snapshot/public_api.txt (committed). ci/docs.sh runs the check
after Doxygen, so the docs job of CI and the local gate (ci/check.sh, step docs) fail when the
public API differs from the baseline. A deliberate change is reviewed and recorded, then the
baseline is updated (docs/developer/api_review_checklist.md, "Updating the API baseline"):

  1. go through the API review checklist for the change;
  2. add the CHANGELOG entry (Added / Changed / Deprecated / Removed; a migration note for a
     break) and give the pull request the `api-change` label;
  3. run `ci/docs.sh --doxygen-only && ci/api_snapshot.py --update` and commit the new baseline
     in the same pull request, so the reviewers see the API diff next to the code.

Headers are marked `frozen` (the 0.1 API: core/*, graph/*, update.hpp, sssp.hpp, cycle_count.hpp
and the top-level library headers) or `tracked` (io/*, generators/*, testing/*: listed and
checked the same way, but reviewed and frozen with the CLI and the Python layer in M5).
"""

from __future__ import annotations

import argparse
import difflib
import fnmatch
import re
import sys
import xml.etree.ElementTree as ET
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
BASELINE = REPO / "cpp" / "tests" / "api" / "api_snapshot" / "public_api.txt"
DEFAULT_XML = REPO / "build" / "doxygen" / "xml"

# The 0.1 freeze (PLAN Section 5, M3): these headers are the frozen 0.1 API.
FROZEN = [
    "dyng/core/*",
    "dyng/graph/*",
    "dyng/update.hpp",
    "dyng/sssp.hpp",
    "dyng/cycle_count.hpp",
    "dyng/citation.hpp",
    "dyng/config.hpp",
    "dyng/dyng.hpp",
    "dyng/version.hpp",
]

HEADER = """\
# SPDX-FileCopyrightText: 2026 The dynG Authors
# SPDX-License-Identifier: Apache-2.0
#
# The public C++ API of dynG: every declaration of cpp/include/dyng outside dyng::detail.
# Generated by ci/api_snapshot.py from the Doxygen XML; do not edit by hand. The check in
# ci/docs.sh fails when the headers no longer match this file; to change the API, follow
# "Updating the API baseline" in docs/developer/api_review_checklist.md (ADR 0023).
# `frozen`: the 0.1 API (reviewed in ADR 0023). `tracked`: checked the same way, frozen in M5.
"""


def text_of(node: ET.Element | None) -> str:
    return "" if node is None else "".join(node.itertext())


def squash(text: str) -> str:
    """One line, single spaces (Doxygen breaks long types and initializers over lines)."""
    return re.sub(r"\s+", " ", text).strip()


def status(header: str) -> str:
    return "frozen" if any(fnmatch.fnmatch(header, p) for p in FROZEN) else "tracked"


def template_prefix(node: ET.Element) -> str:
    params = node.find("templateparamlist")
    if params is None:
        return ""
    parts = []
    for param in params.findall("param"):
        item = squash(text_of(param.find("type")))
        declname = squash(text_of(param.find("declname")))
        if declname and not item.endswith(declname):
            item += " " + declname
        default = squash(text_of(param.find("defval")))
        if default:
            item += " = " + default
        parts.append(item)
    return "template <" + ", ".join(parts) + "> "


def location(node: ET.Element) -> tuple[str, int, int]:
    loc = node.find("location")
    if loc is None:
        return ("", 0, 0)
    return (
        loc.get("file", ""),
        int(loc.get("line", "0") or 0),
        int(loc.get("column", "0") or 0),
    )


def render_member(member: ET.Element, in_class: bool) -> str:
    kind = member.get("kind")
    name = squash(text_of(member.find("name")))
    qualified = squash(text_of(member.find("qualifiedname"))) or name
    shown = name if in_class else qualified
    if kind == "define":
        params = [squash(text_of(p.find("defname"))) for p in member.findall("param")]
        has_params = member.find("param") is not None
        return f"#define {name}" + (f"({', '.join(params)})" if has_params else "")
    if kind == "enum":
        head = "enum class" if member.get("strong") == "yes" else "enum"
        underlying = squash(text_of(member.find("type")))
        values = []
        for value in member.findall("enumvalue"):
            item = squash(text_of(value.find("name")))
            init = squash(text_of(value.find("initializer")))
            values.append(f"{item} {init}".strip())
        base = f" : {underlying}" if underlying else ""
        return f"{head} {shown}{base} {{ {', '.join(values)} }}"
    if kind == "typedef":
        definition = squash(text_of(member.find("definition")))
        aliased = squash(text_of(member.find("type")))
        if definition.startswith("using "):
            return template_prefix(member) + f"using {shown} = {aliased}"
        return template_prefix(member) + (f"typedef {aliased} {shown}" if in_class else definition)
    type_ = squash(text_of(member.find("type")))
    args = squash(text_of(member.find("argsstring")))
    if kind == "variable":
        init = squash(text_of(member.find("initializer")))
        attrs = []
        if member.get("static") == "yes":
            attrs.append("static")
        if member.get("constexpr") == "yes" and "constexpr" not in type_.split():
            attrs.append("constexpr")
        decl = " ".join([*attrs, type_, shown]).strip() + args
        return template_prefix(member) + (f"{decl} {init}" if init else decl)
    if kind in ("function", "friend"):
        attrs = []
        if kind == "friend":
            attrs.append("friend")
        if member.get("nodiscard") == "yes":
            attrs.append("[[nodiscard]]")
        if member.get("static") == "yes":
            attrs.append("static")
        if member.get("virt") in ("virtual", "pure-virtual"):
            attrs.append("virtual")
        if member.get("explicit") == "yes":
            attrs.append("explicit")
        if member.get("constexpr") == "yes" and "constexpr" not in type_.split():
            attrs.append("constexpr")
        words = [w for w in type_.split() if w not in ("friend",)]
        decl = " ".join([*attrs, *words, shown]).strip() + args
        return template_prefix(member) + decl
    return f"{kind} {shown}"


def listing(xml_dir: Path) -> str:
    index = ET.parse(xml_dir / "index.xml").getroot()
    compounds = []
    for entry in index.findall("compound"):
        root = ET.parse(xml_dir / f"{entry.get('refid')}.xml").getroot().find("compounddef")
        if root is not None:
            compounds.append(root)

    headers: set[str] = set()
    entries: dict[str, list[tuple[int, int, int, list[str]]]] = {}
    seen_members: set[str] = set()

    def add(header: str, line: int, column: int, order: int, lines: list[str]) -> None:
        entries.setdefault(header, []).append((line, column, order, lines))

    for cdef in compounds:
        kind = cdef.get("kind")
        if kind == "file":
            header = squash(text_of(cdef.find("compoundname")))
            path = location(cdef)[0] or header
            headers.add(path)
            continue
        if kind == "group":
            # Namespace-scope entities (every one is in a group: ci/doxygen_coverage.py).
            for member in cdef.iter("memberdef"):
                if member.get("id") in seen_members:
                    continue
                seen_members.add(member.get("id"))
                header, line, column = location(member)
                add(header, line, column, 0, [render_member(member, in_class=False)])
            continue
        if kind not in ("class", "struct", "union"):
            continue
        if cdef.get("prot") not in (None, "public"):
            continue
        name = squash(text_of(cdef.find("compoundname")))
        header, line, column = location(cdef)
        bases = [
            " ".join(
                w for w in (b.get("prot"), "virtual" if b.get("virt") == "virtual" else "") if w
            )
            + " "
            + squash(text_of(b))
            for b in cdef.findall("basecompoundref")
        ]
        head = template_prefix(cdef) + f"{kind} {name}"
        if cdef.get("final") == "yes":
            head += " final"
        if bases:
            head += " : " + ", ".join(bases)
        body = [head]
        members = []
        for section in cdef.findall("sectiondef"):
            for member in section.findall("memberdef"):
                if member.get("prot") not in (None, "public"):
                    continue
                m_header, m_line, m_column = location(member)
                members.append((m_line, m_column, render_member(member, in_class=True)))
        body += ["    " + text for _, _, text in sorted(members)]
        add(header, line, column, 1, body)

    out = [HEADER]
    for header in sorted(headers | set(entries)):
        if not header:
            continue
        out.append(f"\n[{header}] {status(header)}\n")
        for _, _, _, lines in sorted(entries.get(header, [])):
            for text in lines:
                out.append(f"  {text}\n")
    return "".join(out)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("--xml", type=Path, default=DEFAULT_XML, help="Doxygen XML directory")
    parser.add_argument("--baseline", type=Path, default=BASELINE, help="the committed listing")
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--update", action="store_true", help="rewrite the baseline")
    mode.add_argument("--print", action="store_true", help="print the listing")
    args = parser.parse_args(argv)

    if not (args.xml / "index.xml").exists():
        print(
            f"api-snapshot: no Doxygen XML in {args.xml}; run ci/docs.sh --doxygen-only first",
            file=sys.stderr,
        )
        return 2
    current = listing(args.xml)
    if args.print:
        sys.stdout.write(current)
        return 0
    if args.update:
        args.baseline.parent.mkdir(parents=True, exist_ok=True)
        args.baseline.write_text(current)
        print(f"api-snapshot: wrote {args.baseline}")
        return 0
    if not args.baseline.exists():
        print(
            f"api-snapshot: no baseline {args.baseline}; create it with --update", file=sys.stderr
        )
        return 1
    baseline = args.baseline.read_text()
    if baseline == current:
        declarations = sum(1 for line in current.splitlines() if line.startswith("  "))
        print(f"api-snapshot: OK ({declarations} declarations match {args.baseline.name})")
        return 0
    try:
        shown = args.baseline.relative_to(REPO)
    except ValueError:
        shown = args.baseline
    diff = difflib.unified_diff(
        baseline.splitlines(keepends=True),
        current.splitlines(keepends=True),
        fromfile=f"{shown} (baseline)",
        tofile="the public headers",
    )
    sys.stdout.writelines(diff)
    print(
        "\napi-snapshot: the public C++ API differs from the baseline (above: - baseline, "
        "+ headers).\nIf the change is intended: go through docs/developer/api_review_checklist.md,"
        " add a CHANGELOG entry and the `api-change` label, then run\n"
        "  ci/docs.sh --doxygen-only && ci/api_snapshot.py --update\n"
        "and commit the new baseline with the change (ADR 0023).",
        file=sys.stderr,
    )
    return 1


if __name__ == "__main__":
    sys.exit(main())
