// SPDX-FileCopyrightText: 2026 The dynG Authors
// SPDX-License-Identifier: Apache-2.0
// Generated by scripts/regen.py from the manifests; do not edit.
/**
 * @file registry.hpp
 * @brief The algorithms the conformance kit knows (PLAN Section 8.2): one tag per manifest, and
 *        the test_traits of every algorithm this build contains (DYNG_ALGORITHM_<NAME>, defined by
 *        cpp/tests/CMakeLists.txt for the algorithms CMake builds).
 */
#pragma once

#include "conformance/type_list.hpp"

/// The tags of the algorithms: test_traits<tags::<name>> is an algorithm's traits.
namespace dyng::conformance::tags {
/// The tag of sssp.
struct sssp;
/// The tag of cycle_count.
struct cycle_count;
}  // namespace dyng::conformance::tags

#if defined(DYNG_ALGORITHM_SSSP)
#include "algorithms/sssp/sssp_traits.hpp"
#endif
#if defined(DYNG_ALGORITHM_CYCLE_COUNT)
#include "algorithms/cycle_count/cycle_count_traits.hpp"
#endif

namespace dyng::conformance {

/// The list of the manifests, built one algorithm at a time.
namespace registry_detail {
using list_0 = type_list<>;
using list_1 = append_t<list_0, tags::sssp>;
using list_2 = append_t<list_1, tags::cycle_count>;
}  // namespace registry_detail

/// Every algorithm with a manifest, in the order of cpp/src/algorithms/CMakeLists.txt; the kit
/// keeps those whose test_traits this build defines (registered_algorithms, conformance.hpp).
using manifest_algorithms = registry_detail::list_2;

}  // namespace dyng::conformance
