#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 The dynG Authors
# SPDX-License-Identifier: Apache-2.0
"""Write the parity certificate of a release (PLAN Sections 8.3 and 10.3, steps 1-3).

    parity/certify.py check --version 0.1.0rc1 --name asan --command "ctest --preset asan" \\
                            --ctest-log asan-ctest.log [--commit <sha>]
    parity/certify.py check --version 0.1.0rc1 --name gpu_local --command ci/gpu_local.sh \\
                            --gpu-summary build/dev-cuda/gpu_local_summary.md
    parity/certify.py write --version 0.1.0rc1 [--results benchmarks/results/0.1.0rc1]

Everything the certificate states is read from files under benchmarks/results/<version>/, which
are committed with it:

  <suite>.json      the summaries parity/bench_suite.py writes (the performance gates of
                    benchmarks/paper/<suite>.yaml against the unpatched originals) and the
                    compacted harness records next to them;
  parity-*.json     the golden replays (parity/compare.py and compare.py cycle_count --json):
                    each golden set's manifest digest, the case x configuration matrix, the
                    tolerance and the verdict;
  checks.json       the other release checks (sanitizer presets, compute-sanitizer, mutation
                    CTests, check scripts), each with its command, commit, result and counts,
                    added one at a time by `certify.py check`.

`write` assembles benchmarks/results/<version>/parity.json: the commit of the release and the
commits whose builds were measured (each must have the same library and tool sources as the
release commit: `git diff <measured> <release> -- cpp tools cmake CMakeLists.txt
CMakePresets.json` is empty, or the certificate fails), the hardware, driver, CUDA and compiler
versions, the build presets of the measured builds, the pinned originals (commit, baseline SHA,
upstream, which copy serves what), every golden set of parity/goldens.toml with its manifest
SHA-256, the SHA-256 of every case and every replay's pass/fail matrix (case x backend x
configuration), the tolerances used, the performance-gate table (every gated region: medians,
ratio, gate, verdict; the recorded default-clock readings separately) and the checks. It also
rewrites the generated part of README.md (between the certify markers) from the certificate.
Exit 1 if any part failed or is missing; the certificate is written either way, with the reason.
"""

from __future__ import annotations

import argparse
import datetime
import json
import os
import platform
import re
import shutil
import subprocess
import sys
import tomllib
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
SCHEMA = 1
CODE_PATHS = ["cpp", "tools", "cmake", "CMakeLists.txt", "CMakePresets.json"]
# The golden sets of parity/goldens.toml every 0.1 certificate must replay, and the backends
# each must cover (a replay record names its configurations; "cuda" matches cuda, cuda/int64, ...).
REQUIRED_REPLAYS = {
    "sssp": ["sequential", "openmp", "cuda"],
    "cycle_count": ["sequential", "openmp"],
    "cycle_count_cuda": ["cuda"],
}
CTEST = re.compile(r"(\d+)% tests passed, (\d+) tests? failed out of (\d+)")
BEGIN = "<!-- certify:begin (generated by parity/certify.py write; do not edit by hand) -->"
END = "<!-- certify:end -->"


def git(*args: str) -> str:
    return subprocess.check_output(["git", "-C", str(REPO), *args], text=True).strip()


def head_commit() -> tuple[str, bool]:
    head = git("rev-parse", "HEAD")
    dirty = subprocess.run(["git", "-C", str(REPO), "diff", "--quiet", "HEAD"]).returncode != 0
    return head, dirty


def same_code(commit: str, head: str) -> bool | None:
    """True if `commit` has the library and tool sources of `head`; None if unknown."""
    base = commit.split("+", 1)[0]
    if not re.fullmatch(r"[0-9a-f]{7,40}", base):
        return None
    if subprocess.run(["git", "-C", str(REPO), "cat-file", "-e", f"{base}^{{commit}}"]).returncode:
        return None
    return (
        subprocess.run(
            ["git", "-C", str(REPO), "diff", "--quiet", base, head, "--", *CODE_PATHS]
        ).returncode
        == 0
    )


def tool_version(argv: list[str], line: int = 0) -> str | None:
    if not shutil.which(argv[0]) and not Path(argv[0]).is_file():
        return None
    try:
        out = subprocess.run(argv, capture_output=True, text=True, timeout=60).stdout.strip()
    except (OSError, subprocess.SubprocessError):
        return None
    lines = out.splitlines()
    return lines[line] if lines else None


def environment() -> dict:
    """The machine and the toolchain, without host or user names."""
    cpu = platform.processor()
    try:
        for row in open("/proc/cpuinfo"):
            if row.startswith("model name"):
                cpu = row.split(":", 1)[1].strip()
                break
    except OSError:
        pass
    memory_gb = None
    try:
        for row in open("/proc/meminfo"):
            if row.startswith("MemTotal"):
                memory_gb = round(int(row.split()[1]) / 1024 / 1024, 1)
    except OSError:
        pass
    gpus, driver, cuda_driver = [], None, None
    if shutil.which("nvidia-smi"):
        query = "--query-gpu=index,name,driver_version,memory.total,compute_cap"
        out = subprocess.run(
            ["nvidia-smi", query, "--format=csv,noheader"], capture_output=True, text=True
        ).stdout
        for row in out.strip().splitlines():
            idx, name, drv, mem, cap = [x.strip() for x in row.split(",")]
            gpus.append({"index": int(idx), "name": name, "memory": mem, "compute_capability": cap})
            driver = drv
        banner = subprocess.run(["nvidia-smi"], capture_output=True, text=True).stdout
        m = re.search(r"CUDA Version:\s*([0-9.]+)", banner)
        cuda_driver = m.group(1) if m else None
    nvcc = os.environ.get("CUDACXX") or shutil.which("nvcc") or "/usr/local/cuda-13.1/bin/nvcc"
    os_name = None
    try:
        for row in open("/etc/os-release"):
            if row.startswith("PRETTY_NAME="):
                os_name = row.split("=", 1)[1].strip().strip('"')
    except OSError:
        pass
    return {
        "hardware": {
            "cpu": cpu,
            "logical_cpus": os.cpu_count(),
            "memory_gb": memory_gb,
            "gpus": gpus,
        },
        "os": {"name": os_name, "kernel": platform.release()},
        "driver": {"nvidia": driver, "cuda_driver_api": cuda_driver},
        "toolchain": {
            "cxx": tool_version(["/usr/bin/c++", "--version"]),
            "nvcc": tool_version([nvcc, "--version"], -1),
            "cmake": tool_version(["cmake", "--version"]),
            "python": platform.python_version(),
        },
    }


def originals() -> list[dict]:
    doc = tomllib.loads((REPO / "parity" / "references.toml").read_text())
    return [
        {
            "name": r["name"],
            "commit": r["commit"],
            "baseline_tag": r.get("baseline_tag"),
            "baseline_commit": r.get("baseline_commit"),
            "upstream": r.get("upstream"),
            "export_patch": r.get("export_patch") or None,
            "toolchain": r.get("toolchain"),
            "use": "performance baselines from the unpatched git-archive copy; "
            "goldens from the patched copy",
        }
        for r in doc["reference"]
    ]


# --- Golden replays ------------------------------------------------------------------------------


def replay_set(record: dict) -> str:
    return record.get("set") or record.get("algorithm")


def replay_matrix(record: dict) -> tuple[dict, int, int]:
    """(matrix, compared, failed) of a compare.py record, as {row: {config: verdict}}."""
    matrix, compared, failed = {}, 0, 0
    for row, configs in record.get("matrix", {}).items():
        matrix[row] = {}
        for config, value in configs.items():
            if isinstance(value, dict):  # sssp: per group {cases, pass, fail}
                n, ok = value.get("cases", 0), value.get("pass", 0)
                compared += n
                failed += n - ok
                matrix[row][config] = f"{ok}/{n}" + (
                    f" failed: {value['fail']}" if value.get("fail") else ""
                )
            else:  # cycle_count: per case "equal" | "DIFFERENT" | ...
                compared += 1
                failed += value != "equal"
                matrix[row][config] = value
    return matrix, compared, failed


def golden_suites(results: Path, head: str, problems: list[str]) -> list[dict]:
    doc = tomllib.loads((REPO / "parity" / "goldens.toml").read_text())
    replays: dict[str, list[dict]] = {}
    for path in sorted(results.glob("parity-*.json")):
        record = json.loads(path.read_text())
        replays.setdefault(replay_set(record), []).append({"file": path.name, "record": record})
    out = []
    for name, spec in doc["sets"].items():
        entry = {
            "set": name,
            "reference": spec["reference"],
            "commit": spec["commit"],
            "generated_by": spec.get("generated_by"),
            "cases": spec["num_cases"],
            "files": spec["num_files"],
            "manifest_sha256": spec["manifest_sha256"],
            "case_sha256": {case: c["sha256"] for case, c in spec.get("cases", {}).items()},
            "replays": [],
        }
        covered = set()
        for rep in replays.get(name, []):
            record = rep["record"]
            matrix, compared, failed = replay_matrix(record)
            goldens = record.get("goldens", {})
            ok = bool(record.get("passed")) and failed == 0
            if goldens.get("manifest_sha256") != spec["manifest_sha256"]:
                problems.append(
                    f"{rep['file']}: replayed manifest {goldens.get('manifest_sha256')} "
                    f"is not goldens.toml's {spec['manifest_sha256']}"
                )
                ok = False
            commit = (record.get("port") or {}).get("commit", "unknown")
            code = same_code(commit, head)
            if code is not True:
                problems.append(
                    f"{rep['file']}: measured commit {commit} does not have the release's code "
                    f"({'differs' if code is False else 'unknown'})"
                )
                ok = False
            if commit.endswith("+dirty"):
                problems.append(f"{rep['file']}: measured from a dirty tree ({commit})")
                ok = False
            configs = record.get("configs", [])
            covered |= {c.split(":")[0].split("/")[0] for c in configs}
            entry["replays"].append(
                {
                    "record": rep["file"],
                    "date": record.get("date"),
                    "port_commit": commit,
                    "executable": record.get("executable"),
                    "build": record.get("build"),
                    "reference": record.get("reference"),
                    "configs": configs,
                    "tolerance": record.get("tolerance"),
                    "compared": compared,
                    "failed": failed,
                    "matrix": matrix,
                    "passed": ok,
                }
            )
        missing = [b for b in REQUIRED_REPLAYS.get(name, []) if b not in covered]
        if missing:
            problems.append(f"golden set {name}: no replay on {', '.join(missing)}")
        entry["required_backends"] = REQUIRED_REPLAYS.get(name, [])
        entry["passed"] = (
            bool(entry["replays"]) and not missing and all(r["passed"] for r in entry["replays"])
        )
        out.append(entry)
    return out


# --- Performance ---------------------------------------------------------------------------------


def performance(results: Path, head: str, problems: list[str]) -> list[dict]:
    suites = []
    for path in sorted(results.glob("*.json")):
        if path.name in ("parity.json", "checks.json") or path.name.startswith("parity-"):
            continue
        doc = json.loads(path.read_text())
        if (
            not isinstance(doc, dict)
            or "suite" not in doc
            or "verdict" not in doc
            or "readings" not in doc
        ):
            continue  # a harness record (the summaries name them)
        verdict = doc["verdict"]
        ok = bool(verdict.get("passed"))
        for commit in doc.get("port_commits", []):
            code = same_code(commit, head)
            if code is not True:
                problems.append(
                    f"{path.name}: measured commit {commit} does not have the release's code"
                )
                ok = False
            if commit.endswith("+dirty"):
                problems.append(f"{path.name}: measured from a dirty tree ({commit})")
                ok = False
        for reading in doc["readings"]:
            rec = reading.get("record")
            if rec and not (results / rec).is_file():
                problems.append(f"{path.name}: the record {rec} is not next to it")
                ok = False
        if not verdict.get("passed"):
            reasons = [
                *verdict.get("exceeded", []),
                *verdict.get("problems", []),
                *verdict.get("missing_or_incomplete", []),
                *verdict.get("provisional", []),
            ]
            problems.append(f"{path.name}: the suite did not pass ({'; '.join(reasons)})")
        gates, recorded = [], []
        for reading in doc["readings"]:
            for region in reading.get("regions", []):
                row = {
                    "reading": reading["reading"],
                    "backend": reading.get("backend"),
                    "clocks": reading.get("clocks"),
                    "case": region["case"],
                    "region": region["region"],
                    "ratio": region.get("ratio"),
                }
                for key in (
                    "original_ms",
                    "port_ms",
                    "original_mib",
                    "port_mib",
                    "gate",
                    "within_gate",
                    "noisy",
                ):
                    if key in region:
                        row[key] = region[key]
                if reading.get("gated") and "gate" in region:
                    gates.append(row)
                elif "gate" in region:
                    recorded.append(row)
        suites.append(
            {
                "suite": doc["suite"],
                "algorithm": doc["algorithm"],
                "summary": path.name,
                "suite_file": doc.get("suite_file"),
                "suite_sha256": doc.get("suite_sha256"),
                "port_commits": doc.get("port_commits"),
                "baselines": doc.get("baselines"),
                "tolerance": doc.get("tolerance"),
                "inputs": doc.get("inputs"),
                "readings": [
                    {
                        k: r.get(k)
                        for k in (
                            "reading",
                            "dataset",
                            "kind",
                            "backend",
                            "clocks",
                            "gated",
                            "record",
                            "date",
                            "protocol",
                            "complete",
                        )
                    }
                    for r in doc["readings"]
                ],
                "gated_regions": verdict.get("gated_regions"),
                "within_gate": verdict.get("within_gate"),
                "ratio_range": verdict.get("ratio_range"),
                "gate_table": gates,
                "recorded_not_gated": recorded,
                "passed": ok,
            }
        )
    return suites


# --- Checks --------------------------------------------------------------------------------------


def parse_ctest(text: str) -> dict | None:
    matches = CTEST.findall(text)
    if not matches:
        return None
    pct, failed, total = matches[-1]
    return {"tests": int(total), "failed": int(failed), "percent_passed": int(pct)}


def parse_gpu_summary(text: str) -> dict:
    steps = {}
    for row in text.splitlines():
        cells = [c.strip() for c in row.strip().strip("|").split("|")]
        if len(cells) == 2 and cells[0] not in ("step", "---") and not set(cells[0]) <= {"-"}:
            steps[cells[0]] = cells[1]
    return steps


def cmd_check(args: argparse.Namespace) -> int:
    results = args.results or REPO / "benchmarks" / "results" / args.version
    results.mkdir(parents=True, exist_ok=True)
    path = results / "checks.json"
    doc = json.loads(path.read_text()) if path.is_file() else {"schema": SCHEMA, "checks": []}
    entry: dict = {
        "name": args.name,
        "command": args.command,
        "commit": args.commit or head_commit()[0],
    }
    entry["date"] = args.date or datetime.datetime.now(datetime.UTC).strftime("%Y-%m-%dT%H:%M:%SZ")
    passed = True
    if args.ctest_log:
        counts = parse_ctest(Path(args.ctest_log).read_text(errors="replace"))
        if counts is None:
            raise SystemExit(f"{args.ctest_log}: no ctest summary line")
        entry["ctest"] = counts
        passed &= counts["failed"] == 0 and counts["tests"] > 0
    if args.gpu_summary:
        steps = parse_gpu_summary(Path(args.gpu_summary).read_text())
        if not steps:
            raise SystemExit(f"{args.gpu_summary}: no step table")
        entry["steps"] = steps
        passed &= all(v in ("passed", "skipped") for v in steps.values())
        if args.require_steps:
            for step in args.require_steps.split(","):
                if steps.get(step) != "passed":
                    entry.setdefault("missing_steps", []).append(step)
                    passed = False
    if args.result:
        passed &= args.result == "passed"
    if not (args.ctest_log or args.gpu_summary or args.result):
        raise SystemExit("check: give --ctest-log, --gpu-summary or --result")
    if args.details:
        entry["details"] = args.details
    entry["result"] = "passed" if passed else "FAILED"
    doc["checks"] = [c for c in doc["checks"] if c["name"] != args.name] + [entry]
    path.write_text(json.dumps(doc, indent=1) + "\n")
    print(f"{args.name}: {entry['result']}")
    return 0 if passed else 1


def checks(results: Path, head: str, problems: list[str]) -> list[dict]:
    path = results / "checks.json"
    if not path.is_file():
        problems.append("checks.json is missing (sanitizers, mutation checks: certify.py check)")
        return []
    out = json.loads(path.read_text())["checks"]
    for c in out:
        code = same_code(c.get("commit", ""), head)
        c["release_code"] = code is True
        if c.get("result") != "passed":
            problems.append(f"check {c['name']}: {c.get('result')}")
        if code is not True:
            problems.append(
                f"check {c['name']}: commit {c.get('commit')} does not have the release's code"
            )
    return out


# --- README --------------------------------------------------------------------------------------


def fmt_ratio(rows: list[dict]) -> str:
    vals = [r["ratio"] for r in rows if r.get("ratio") is not None]
    return f"{min(vals):.3f}-{max(vals):.3f}" if vals else "-"


def readme_block(cert: dict) -> str:
    lines = [BEGIN, ""]
    v = cert["verdict"]
    lines.append(
        f"**Certificate:** `parity.json` (dynG {cert['version']}, commit `{cert['commit'][:12]}`): "
        + ("**all parts passed**." if v["passed"] else "**FAILED**: " + "; ".join(v["problems"]))
    )
    lines.append("")
    env = cert["environment"]
    gpu = env["hardware"]["gpus"][0]["name"] if env["hardware"]["gpus"] else "no GPU"
    lines.append(
        f"Machine: {env['hardware']['cpu']} ({env['hardware']['logical_cpus']} threads), "
        f"{len(env['hardware']['gpus'])}x {gpu}; driver {env['driver']['nvidia']}; "
        f"{env['toolchain']['nvcc']}; {env['toolchain']['cxx']}."
    )
    lines += [
        "",
        "### Golden parity",
        "",
        "| Golden set | Original | Cases | Replays (configurations: compared / failed) | Result |",
        "|---|---|---:|---|---|",
    ]
    for g in cert["golden_suites"]:
        reps = (
            "; ".join(
                f"{', '.join(r['configs'])}: {r['compared']} / {r['failed']}" for r in g["replays"]
            )
            or "none"
        )
        lines.append(
            f"| `{g['set']}` | {g['reference']}@{g['commit'][:7]} | {g['cases']} | {reps} "
            f"| {'passed' if g['passed'] else 'FAILED'} |"
        )
    lines += ["", "### Performance gates (PLAN 8.6, against the unpatched originals)", ""]
    lines += [
        "| Suite | Reading | Backend (clocks) | Gated regions | Ratio range (port / original) "
        "| Result |",
        "|---|---|---|---:|---|---|",
    ]
    for s in cert["performance"]:
        by_reading: dict[str, list[dict]] = {}
        for row in s["gate_table"]:
            by_reading.setdefault(row["reading"], []).append(row)
        for reading, rows in by_reading.items():
            within = sum(1 for r in rows if r.get("within_gate"))
            clocks = f" ({rows[0]['clocks']})" if rows[0].get("clocks") else ""
            lines.append(
                f"| `{s['suite']}` | {reading} | {rows[0]['backend']}{clocks} "
                f"| {within} / {len(rows)} | {fmt_ratio(rows)} "
                f"| {'passed' if within == len(rows) else 'FAILED'} |"
            )
        rec: dict[str, list[dict]] = {}
        for row in s["recorded_not_gated"]:
            rec.setdefault(row["reading"], []).append(row)
        for reading, rows in rec.items():
            clocks = f" ({rows[0]['clocks']})" if rows[0].get("clocks") else ""
            lines.append(
                f"| `{s['suite']}` | {reading} | {rows[0]['backend']}{clocks} "
                f"| recorded, not gated ({len(rows)}) | {fmt_ratio(rows)} | - |"
            )
    lines += ["", "### Checks", "", "| Check | Command | Result |", "|---|---|---|"]
    for c in cert["checks"]:
        detail = ""
        if "ctest" in c:
            detail = (
                f" ({c['ctest']['tests'] - c['ctest']['failed']} / {c['ctest']['tests']} tests)"
            )
        elif "steps" in c:
            detail = " (" + ", ".join(f"{k} {v}" for k, v in c["steps"].items()) + ")"
        lines.append(f"| {c['name']} | `{c['command']}` | {c['result']}{detail} |")
    lines += ["", END]
    return "\n".join(lines)


def update_readme(path: Path, block: str) -> None:
    text = path.read_text() if path.is_file() else ""
    if BEGIN in text and END in text:
        head, rest = text.split(BEGIN, 1)
        tail = rest.split(END, 1)[1]
        text = head + block + tail
    else:
        text = (text.rstrip() + "\n\n" if text else "") + block + "\n"
    path.write_text(text)


# --- write ---------------------------------------------------------------------------------------


def cmd_write(args: argparse.Namespace) -> int:
    results = args.results or REPO / "benchmarks" / "results" / args.version
    if not results.is_dir():
        raise SystemExit(f"{results}: no results directory")
    head, dirty = head_commit()
    problems: list[str] = []
    if dirty and not args.allow_dirty:
        problems.append("the release tree is dirty (commit first, or --allow-dirty for a draft)")
    goldens = golden_suites(results, head, problems)
    perf = performance(results, head, problems)
    if not perf:
        problems.append("no performance-suite summary (parity/bench_suite.py run)")
    algorithms = {s["algorithm"] for s in perf}
    for algo in ("sssp", "cycle_count"):
        if algo not in algorithms:
            problems.append(f"no performance suite of {algo}")
    checklist = checks(results, head, problems)
    measured = sorted(
        {r["port_commit"] for g in goldens for r in g["replays"]}
        | {c for s in perf for c in (s["port_commits"] or [])}
        | {c["commit"] for c in checklist}
    )
    version_file = (REPO / "VERSION").read_text().strip()
    cert = {
        "schema": SCHEMA,
        "what": "dynG parity certificate (PLAN 8.3): golden parity with the pinned originals, "
        "the performance gates of PLAN 8.6 and the release checks",
        "version": args.version,
        "version_file": version_file,
        "date": datetime.datetime.now(datetime.UTC).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "commit": head + ("+dirty" if dirty else ""),
        "branch": git("rev-parse", "--abbrev-ref", "HEAD"),
        "measured_commits": measured,
        "code_paths": CODE_PATHS,
        "code_rule": "every measured commit has the release commit's library and tool sources "
        "(git diff <measured> <release> -- code_paths is empty)",
        "environment": environment(),
        "originals": originals(),
        "golden_suites": goldens,
        "performance": perf,
        "checks": checklist,
    }
    cert["verdict"] = {
        "golden_parity": bool(goldens) and all(g["passed"] for g in goldens),
        "performance_gates": bool(perf) and all(s["passed"] for s in perf),
        "checks": bool(checklist) and all(c.get("result") == "passed" for c in checklist),
        "problems": problems,
    }
    cert["verdict"]["passed"] = not problems and all(
        cert["verdict"][k] for k in ("golden_parity", "performance_gates", "checks")
    )
    (results / "parity.json").write_text(json.dumps(cert, indent=1) + "\n")
    update_readme(results / "README.md", readme_block(cert))
    print(f"{results / 'parity.json'}: {'PASSED' if cert['verdict']['passed'] else 'FAILED'}")
    for p in problems:
        print(f"  {p}")
    return 0 if cert["verdict"]["passed"] else 1


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    sub = parser.add_subparsers(dest="command_name", required=True)
    w = sub.add_parser("write", help="assemble parity.json and the README tables")
    w.add_argument("--version", default=(REPO / "VERSION").read_text().strip())
    w.add_argument("--results", type=Path, default=None)
    w.add_argument("--allow-dirty", action="store_true", help="a draft from an uncommitted tree")
    c = sub.add_parser("check", help="record one release check in checks.json")
    c.add_argument("--version", default=(REPO / "VERSION").read_text().strip())
    c.add_argument("--results", type=Path, default=None)
    c.add_argument("--name", required=True)
    c.add_argument("--command", required=True, help="the command that was run (recorded)")
    c.add_argument("--commit", help="the commit whose build was checked (default HEAD)")
    c.add_argument("--date", help="when it ran (ISO 8601; default now)")
    c.add_argument("--ctest-log", type=Path)
    c.add_argument("--gpu-summary", type=Path, help="ci/gpu_local.sh's gpu_local_summary.md")
    c.add_argument("--require-steps", help="with --gpu-summary: steps that must have passed")
    c.add_argument("--result", choices=["passed", "failed"])
    c.add_argument("--details")
    args = parser.parse_args(argv)
    return cmd_write(args) if args.command_name == "write" else cmd_check(args)


if __name__ == "__main__":
    sys.exit(main())
