// SPDX-FileCopyrightText: 2026 The dynG Authors
// SPDX-License-Identifier: Apache-2.0
/**
 * @file algorithm_template.hpp
 * @brief algorithm_template: compute() and update() (generated by scripts/new_algorithm.py).
 * @ingroup algorithm_template
 */
#pragma once

#include <dyng/core/array_view.hpp>
#include <dyng/core/memory.hpp>
#include <dyng/core/resources.hpp>
#include <dyng/core/stats.hpp>
#include <dyng/core/types.hpp>
#include <dyng/graph/apply_summary.hpp>
#include <dyng/graph/edge_batch.hpp>
#include <dyng/graph/graph.hpp>
#include <dyng/update.hpp>

#include <cstdint>
#include <memory>

/**
 * @defgroup algorithm_template algorithm_template
 * @brief {{title}}.
 *
 * TODO(algorithm_template): the problem, the update model and the template mapping (the page
 * docs/algorithms/algorithm_template.md has the required sections).
//@@ fixed_point
 *
 * Placeholder written by scripts/new_algorithm.py: the hop level of every vertex from
 * options::source (-1 if unreachable), a fixed-point problem. update() applies the batch and
 * recomputes from scratch (stats::fallback_used is true); make it incremental in problem.hpp.
//@@ end
//@@ aggregate_delta
 *
 * Placeholder written by scripts/new_algorithm.py: the number of reciprocal pairs
 * {u -> v, v -> u} of the graph, an aggregate-delta problem. update() applies the batch and
 * recounts from scratch (stats::fallback_used is true); make it incremental in problem.hpp.
//@@ end
 */

namespace dyng::algorithm_template {

/**
 * @brief Options of compute() and update() (an aggregate; fields are only ever appended).
 * @ingroup algorithm_template
 */
struct options {
  //@@ fixed_point
  /// The source vertex. Fixed at compute().
  std::int64_t source = 0;
  //@@ end
  //@@ aggregate_delta
  /// Reserved for the algorithm's options (options are only ever appended).
  bool validate_inputs = true;
  //@@ end
};

/**
 * @brief Counters of one update() (fields are only ever appended).
 * @ingroup algorithm_template
 */
struct stats : update_stats {
  /// Deterministic: what applying the batch did to the graph.
  apply_summary batch;
};

}  // namespace dyng::algorithm_template

namespace dyng::detail {
struct algorithm_template_state;
struct algorithm_template_access;
}  // namespace dyng::detail

namespace dyng::algorithm_template {

/**
 * @brief The result kept up to date by update() (opaque, move-only).
 *
 * The result owns its values (host memory), its options and the graph version it matches.
 * @ingroup algorithm_template
 */
class result {
 public:
  /**
   * @brief Move constructor.
   * @param[in,out] other The result to move from; it may only be assigned to or destroyed after.
   */
  result(result&& other) noexcept;

  /**
   * @brief Move assignment.
   * @param[in,out] other The result to move from; it may only be assigned to or destroyed after.
   * @return *this.
   */
  result& operator=(result&& other) noexcept;

  result(const result&) = delete;             ///< not copyable: use clone()
  result& operator=(const result&) = delete;  ///< not copyable: use clone()
  ~result();                                  ///< releases the values

  //@@ fixed_point
  /**
   * @brief The hop levels.
   * @return One level per vertex (host memory), -1 for the vertices the source does not reach.
   *         Valid until the next update() of this result.
   * @throws invalid_argument_error for a moved-from result.
   * @throws stale_result_error     if a failed update left the result unusable (poisoned).
   */
  [[nodiscard]] array_view<const std::int64_t> levels() const;
  //@@ end
  //@@ aggregate_delta
  /**
   * @brief The aggregate.
   * @return The number of reciprocal pairs.
   * @throws invalid_argument_error for a moved-from result.
   * @throws stale_result_error     if a failed update left the result unusable (poisoned).
   */
  [[nodiscard]] std::uint64_t count() const;
  //@@ end

  /**
   * @brief The options.
   * @return The options given at compute(), as changed by set_options().
   * @throws invalid_argument_error for a moved-from result.
   * @throws stale_result_error     if a failed update left the result unusable (poisoned).
   */
  [[nodiscard]] const options& get_options() const;

  /**
   * @brief Change the tunables.
   * @param[in] opt The new options; the ones fixed at compute() must stay the same.
   * @throws invalid_argument_error if a fixed option differs, or for a moved-from result.
   * @throws stale_result_error     if a failed update left the result unusable (poisoned).
   */
  void set_options(const options& opt);

  /**
   * @brief The graph version this result matches.
   * @return The version of the graph after the last compute() / update() of this result.
   */
  [[nodiscard]] std::uint64_t graph_version() const noexcept;

  /**
   * @brief The memory space of the values.
   * @return memory_space::host.
   */
  [[nodiscard]] memory_space space() const noexcept;

  /**
   * @brief A deep copy for the resources `res`.
   * @param[in] res Execution resources of the copy.
   * @return The copy.
   * @throws invalid_argument_error for a moved-from result.
   * @throws stale_result_error     if a failed update left the result unusable (poisoned).
   * @throws not_supported_error    if the backend of `res` is not available for
   *         algorithm_template.
   * @throws out_of_memory_error    if the copy cannot be allocated.
   * @sync
   */
  [[nodiscard]] result clone(const resources& res) const;

 private:
  friend struct detail::algorithm_template_access;
  explicit result(std::unique_ptr<detail::algorithm_template_state> state) noexcept;

  std::unique_ptr<detail::algorithm_template_state> impl_;
};

/**
 * @brief Compute the result of `g` (the static solve, the oracle of update()).
 * @tparam vertex_t Vertex id type.
 * @tparam edge_t   Edge offset type.
 * @tparam weight_t Weight type (ignored).
 * @param[in] res Execution resources ({{backends_doc}}).
 * @param[in] g   The graph (host storage); it is not modified.
 * @param[in] opt Options.
 * @return The result, matching `g.version()`.
 * @throws invalid_argument_error if an option is out of range or `g` is not host storage.
 * @throws not_supported_error    if the backend of `res` is not available for
 *         algorithm_template.
 * @throws out_of_memory_error    if host memory cannot be allocated.
 * @sync
 * @backends {{backends_doc}}
 * @determinism Exact: identical results on every backend and run.
 * @paper None yet (TODO(algorithm_template): the paper, and its key in docs/references.bib).
 * @ingroup algorithm_template
 */
template <typename vertex_t, typename edge_t, typename weight_t>
[[nodiscard]] result compute(const resources& res, const graph<vertex_t, edge_t, weight_t>& g,
                             const options& opt = {});

/**
 * @brief Apply a batch of edge changes to `g` and update `r`.
 *
 * Postcondition: `r` equals compute(res, g, r.get_options()) exactly.
 * @tparam vertex_t Vertex id type.
 * @tparam edge_t   Edge offset type.
 * @tparam weight_t Weight type (ignored).
 * @param[in]     res   Execution resources ({{backends_doc}}).
 * @param[in,out] g     The graph; the batch is applied to it and its version increases by one.
 * @param[in]     batch Insertions, deletions and weight changes.
 * @param[in,out] r     Result of compute() or of a previous update() on `g`.
 * @return Counters of this update.
 * @throws stale_result_error     if r.graph_version() != g.version() or `r` belongs to another
 *         graph.
 * @throws invalid_argument_error if a batch id or weight is invalid (nothing is changed).
 * @throws not_supported_error    if the backend of `res` is not available for
 *         algorithm_template.
 * @throws out_of_memory_error    if host memory cannot be allocated.
 * @sync
 * @backends {{backends_doc}}
 * @determinism Exact: identical results on every backend and run.
 * @paper None yet (TODO(algorithm_template)).
 * @ingroup algorithm_template
 */
template <typename vertex_t, typename edge_t, typename weight_t>
stats update(const resources& res, graph<vertex_t, edge_t, weight_t>& g,
             const edge_batch_view<vertex_t, weight_t>& batch, result& r);

}  // namespace dyng::algorithm_template

namespace dyng::detail {

/**
 * @brief The update participant of an algorithm_template result (used by dyng::update()).
 * @tparam vertex_t Vertex id type.
 * @tparam edge_t   Edge offset type.
 * @tparam weight_t Weight type.
 * @param[in,out] r   The result.
 * @param[out]    out Receives the stats of the update.
 * @return The participant.
 */
template <typename vertex_t, typename edge_t, typename weight_t>
std::unique_ptr<update_participant<vertex_t, edge_t, weight_t>> make_algorithm_template_participant(
    algorithm_template::result& r, algorithm_template::stats& out);

/**
 * @brief update_traits of algorithm_template::result (dyng::update() support).
 */
template <>
struct update_traits<algorithm_template::result> {
  using stats_type = algorithm_template::stats;  ///< the stats type

  /**
   * @brief Create the participant.
   * @tparam container_t The container type.
   * @param[in,out] r   The result.
   * @param[out]    out Receives the stats.
   * @return The participant.
   */
  template <typename container_t>
  static std::unique_ptr<typename participant_of<container_t>::type> make_participant(
      algorithm_template::result& r, algorithm_template::stats& out) {
    return make_algorithm_template_participant<typename container_t::vertex_type,
                                               typename container_t::edge_type,
                                               typename container_t::weight_type>(r, out);
  }
};

}  // namespace dyng::detail
